<section>
	
	<h2>Jimmy Pan</h2>

	<p class="description">A tragic prequel to a classic children's tale.</p>

	<p>Once upon a time, there was a wayward young English street boy named Jimmy. Life was hard for Jimmy, who had no parents, and scraped by begging and stealing what he could. But he found ways to make his world more beautiful, weaving clever trinkets from bits of stem and leaf with his nimble young fingers, and floating them down creeks and streams. And though life was hard, young Jimmy was free, so long as he could evade the mean old grown-ups who always wanted to catch him and punish him for his mischief.</p>
	<p>Then one day, while folding leaf-boats on a shady stream beneath a bridge, one of his creations was commandeered by a beautiful, tiny fairy. Jimmy befriended the magical creature, and taught it how to sail in his tiny ships. The fairy in turn taught him how to fly, and then took him to her enchanted land full of mystical creatures and exotic people, where people never grew old and had nothing to do but play as long as they wanted. Other, similarly lost girls and boys like him were there as well. Some of them came and went, some stayed longer; but Jimmy remained through it all, and over time became something like the prince of that land, the beloved companion of the fairies, king of the lost boys.</p>
	<p>But then one day, a special young girl named Mary came to the land. When he was with Mary, Jimmy felt feelings he had never felt before; he cared for her like he had never cared for anyone or anything else. Jimmy fell in love, and when Mary eventually decided to return to the real world, Jimmy was enticed at last to follow her back to reality. So he bid farewell to his enchanted world and the many friends he had made there, and returned again to the world he had long ago left behind.</p>
	<p>That world was now strange compared to how it had been when he had left, however many unchanging years ago, and fitting in was harder than ever for Jimmy. Mary was from a wealthy family, who took the wild lost boy in, fed and clothed and cared for him. Seeing the young romance between him and their daughter blooming, they set out to tame him and groom him to be worthy of their precious flower. For years he was drilled hard in good form at Eton College, and meanwhile apprenticed in the art of watchmaking, for which his nimble hands were particularly well-suited.</p>
	<p>The rigor of civilized life was difficult, and young master Jim chafed against it constantly; yet he pushed through it all for the sake of his love. But in their first year at University, Mary grew apart from him, and with that Jim's only connection to the civilized world was lost; as was his financial support. Faced suddenly with having to support himself, Jim was unable to cope, even with his education and craftsman's skills. Mourning as he was for his lost love, he simply could not find it in him to be the upstanding citizen he had trained for years, for her sake, to be.</p>
	<p>He returned instead to his earlier ways of living, scraping by in the margins of society; but now an adult, he was drawn into more organized crime, and soon joined the crew of a pirate ship. Throughout the years, he proved an able pirate, rising quickly through the ranks, even serving as boatswain for Blackbeard himself. Eventually he became Captain James of his own ship, the Jolly Roger; earned a reputation as the only man Long John Silver ever feared; and lived a life of comparative luxury with the treasure that he plundered.</p>
	<p>Settling at last into life, James once again took up watchmaking, now as a hobby on board his ship, and a bittersweet reminder of his lost love. Though he had hated the prospect of doing so for a living, he found working with his hands brought him back to the carefree mindset he once had, making fairy-boats by the stream. Life as a pirate captain was better than life as a serf or an industrial slave, but still this life was hard and brutal, and James longed to return to the enchanted land of his youth, regaling his crew constantly with stories of that wonderful place.</p>
	<p>That draw eventually grew too great, and James set his ship and crew off on what the men at first called a fool's errand, in search of a mermaid; who, the Captain claimed, being mystical creatures, could pass between this world and that by their own means. Despite the crew's growing skepticism, in time they finally did find a pod of merfolk, and James eloquently convinced them to take their entire ship of 'lost men' to the magical world where they might age no more and could live at last in peace.</p>
	<p>But upon arriving, the Captain found that that world too had changed in his absence. A young, brash rapscallion named Peter had come and usurped his place as fairy-friend and king of the lost boys. James and his men at first tried to befriend Peter and the boys, but in short time found themselves unwittingly falling into the condescending adult prejudice that, as a lost boy himself, Jimmy had once loathed. Peter and the lost boys thus shunned James and his crew as "mean grown-ups".</p>
	<p>In response, the Captain challenged the usurper Peter for dominance of the land. As his crew and the lost boys fought on the ground, Peter and James duelled in the sky, fighting, flying, crowing at the heavens; until Peter at last stole the Captain's favorite watch from off his person, his last keepsake of the life he almost had, and when the Captain recovered it, Peter cut off the Captain's hand, which fell into the ocean below to be eaten, watch and all, by a saltwater crocodile. Their leader crippled, the pirate crew retreated back to their ship, to tend to his grievous wound, and fit him with a prosthetic hook to replace his lost hand.</p>
	<p>With that humiliating defeat, the last happy thoughts of young Jimmy were lost forever. He forgot entirely how to fly, how to live and laugh and love, withdrawing instead into the formality and ruthlessness of the adult world he had been barred into. His nimble hand lost, and the croc which ate it now ticking with the watch that hand had made, James abandoned his hobby and shunned all clocks as unwelcome reminders of a past he would never reclaim.</p>
	<p>Thenceforth he dedicated his life to revenge against Peter, to teaching that cocky young boy the lesson he so righteously deserved: that the world is a cruel and harsh place, and the carelessness of youth is nought but a temporarily illusion. Thereafter, Captain James "Hook", as the lost boys came to call him, would be remembered as nothing but the greatest terror Neverland had ever known.</p>

</section>