<section>
	
	<h2><i>Lord of the Rings</i> Foreknowledge</h2>

	<p class="description">How might <i>The Hobbit</i> and <i>The Lord of the Rings</i> have gone if the protagonists knew at the start all of the things they learned by the end?</p>

	<p>The events of the Hobbit and LotR are for some reason slipped from Mandos to Manwe just before he sends the Istari to Endor.</p>
	<p>Knowing the events that would otherwise unfold, Manwe insists that Gandalf, despite his protests, be the White and lead the Istari on their mission to stir the peoples of Middle-Earth to oppose the return of Sauron. Gandalf is told at least enough information to carry out the following plan.</p>
	<p>The White Council is convened between the five Istari, the three Eldar Lords Galadriel, Elrond, and Cirdan, and the lost High King of Men, Aragorn son of Arathorn. Gandalf reveals that Mandos has told of Sauron's return and of a weapon that can defeat him, but it will require the alliance of all the free peoples of Middle Earth to accomplish. The bargain: the kingdoms of Dwarves and Men must commit forces to two battles to help the Elves defeat Sauron before he returns; the Elves and Men must help the Dwarves to recapture both Erebor and Moria; and the Elves and Dwarves must help to rebuild the fallen kingdom of Arnor for Men.</p>
	<p>The Elves agree right out the gate with the Maia wielding the foreknowledge of Mandos. Elrond's smiths reforge the sword of Isildur, and bearing it as proof of his right of kingship, Aragorn visits Denethor, Steward of Gondor, with the proposal.</p>
	<p>If Denethor will commit Gondor's armies to aiding in two battles to prevent Sauron's return, they will have the aid of the Elves of the three Havens in rebuilding Arnor; and if they help the Dwarves to recapture Erebor and Moria, the rebuilding will be funded from their vaults. When Arnor is rebuilt, Denethor must step down and allow Aragorn to reign as the rightful king of the Reunited Kingdom; however, Denethor's line will continue the actual ruling of the Kingdom, as not mere Stewards but as full Prince Regents under Aragorn -- Boromir over Gondor, and Faramir over Arnor. Denethor tentatively agrees, if all seven Dwarven kingdoms will actually commit to the plan.</p>
	<p>So the story begins, as in the canonical Hobbit, with Gandalf approaching the company of Thorin Oakenshield about their quest to recapture Erebor. They are promised the aid of armies of Men and Elves both, in reclaiming not only Erebor but also Moria, if they can bring the seven Dwarven kingdoms to aid in but two great battles necessary to defeat Sauron before he can return to power, and offer funding to rebuild the kingdom of Arnor. Thorin departs to his meeting with the Dwarf Lords bearing this bargain.</p>
	<p>Meanwhile, Gandalf visits Hobbiton to approach Bilbo Baggins with an entirely different kind of adventure. Instead of needing a thief, Gandalf needs a host. Someone kind and mild-mannered and capable of caring politely for even the more unruly of guests, for there is someone in great need of his care, someone not unlike a hobbit in fact, and Gandalf knows Bilbo is quite the right person for the job. He promises that they will be well guarded the entire way by a great army of Dwarves, Elves, and Men, and will have quite the safe opportunity to see the world. Bilbo is much more amenable to this proposal than the one he would canonically have received, and eagerly accepts.</p>
	<p>Gandalf then stays a while at Bag End and awaits the arrival of Thorin's company with news. They eventually arrive, much as canonically but less unexpectedly, with great news. The Dwarf Lords have agreed to the proposal, and have each dispatched regiments to the meeting grounds at Rivendell. The plan is afoot.</p>
	<p>Cirdan and an Elvish regiment from the Grey Havens arrive soon in Hobbiton to escort the company eastward. They are joined in Bree by Aragorn and a small company of Rangers from the North. These provide safe passage from Orcs, Wargs, and Trolls, until the company reaches Rivendell, where seven regiments of Dwarves and an army of Men have gathered together with the forces of Elrond and Galadriel and the rest of the Istari.</p>
	<p>Together they depart to the halls of the Goblin-King in the Misty Mountains and thoroughly scour them of all enemies with their overwhelming might. Then, alone, Gandalf and Bilbo venture into the caves beneath the goblins' lair, searching for one once known as Smeagol.</p>
	<p>Finding him, they immediately placate him with an offering of fresh fish, and offer him much more where that came from, and anything else he should wish to eat, if he will aid them. Gollum is still suspicious, and asks what it wants of them. Gandalf comes clean, and tells Gollum that someone is after his precious. That they know about the precious, but they will not take it from him. The one who made it, Sauron, wants to take it from him, and he is their enemy as well, and they need him to defeat their mutual enemy and keep him from taking Gollum's precious. Also, all the fish he can eat.</p>
	<p>Gollum is lured by hatred of anyone who would want to take his precious, and Smeagol is lured by the promise of fish, fish, fish. Bilbo is tasked with caring for Smeagol as they venture to the final battle, and seeing to it that nobody else gets ahold of the ring which Gollum bears, or even knows that he has such a thing.</p>
	<p>No one else in the company knowing any better, besides the three Elven lords, the company heads south toward the gates of Mordor. A rearguard is left behind to watch over Dor Guldur, while the rest of the company escorts Bilbo and Gollum into mostly-unoccupied Mordor, defending them from Orcs and other threats along the way, knowing only that they are seeking a weapon which can be used to defeat the Dark Lord. When they reach the Cracks of Doom, only Gandalf, Bilbo, and Gollum enter, together with the three Elven lords.</p>
	<p>Gollum is then told the untold details of the plan to defeat he who would take the precious from him, and Bilbo is told the untold details of his part in this plan. The only way to keep Sauron from taking Gollum's precious is to cast it into the fires here. Gollum will not be allowed to leave the chasm; Gandalf and the Elf-lords have barred the way, and an army lays outside with orders to stop any from leaving without orders from the Elf-lords. Bilbo's job is to make sure that the ring ends up in the fires, by whatever means necessary, for none of them can touch it.</p>
	<p>Gollum/Smeagol struggle with the apparent betrayal, appear to consider maybe doing what the nice hobbits askses if it means keeping someone else from taking the precious, but then decides that it was trickses all alongs and attacks Bilbo with the ring on. Bilbo struggles with Smeagol and attempts to pry the ring from his finger but is being strangled and bitten. At the last moment Gandalf intervenes and strikes Gollum with his staff, beating him off of Bilbo (being a Maia, Gandalf can see into the realm of shadows and so Gollum is not really invisible to him with the ring on). He beats Gollum away and pins him to the ground with his staff, and demands that Bilbo take the ring off of Gollum. He struggles to do so, even with Gollum so disabled, and poignantly considers the object he now holds in his hands. Gandalf commands him to cast it into the fires, and Bilbo seems almost not to hear, or to be distracted, but slowly does as told, and very hesitantly, confusedly, as though being unexpectedly shouted orders from two different sources and just blindly doing one of the two things told without really comprehending, lets the ring slip into the cracks.</p>
	<p>Clarity returns to Bilbo just in time for him to hear Gandalf shout "Run!" The Elf lords return to the armies outside, Bilbo with them, and command them to flee from the mountain as well. Gandalf released Gollum, who is wailing inconsolably at his loss, and flees behind them. As the caverns begin to collapse, Smeagol regains presence of mind and flees in terror as well, screaming "why, why is it gone, precious".</p>
	<p>Meanwhile, the other four Istari at the rearguard at Dor Guldur drive the suddenly-weakened "Necromancer" from there, never to be seen again.</p>
	<p>As promised, the armies of Elves and Men help the Dwarves reclaim Erebor and Moria. The five Istari jointly lend a brief hand in each of those battles, slaying both the dragon Smaug and the balrog known as Durin's Bane. Then the Elves and Dwarves help Men to rebuild Arnor. Denethor, a bit hesitantly, steps down as Steward of Gondor to allow Boromir to take his place as its first Prince Regent under King Elessar, and Faramir in Arnor likewise.</p>
	<p>Meanwhile Smeagol follows Bilbo and Gandalf, begging desperately for an explanation. He is wretchedly confused and despondent and doesn't really understand what has happened. A huge weight is lifted from him, he is now all Smeagol, no more Gollum, but he feels the profound loss of his precious as well. Bilbo stays with him under the care of the Elves in Rivendell and helps him to come to terms with things, while feeding him well; Smeagol is still a wretched mess of a creature, but he is now more broken and withered than cruel or evil, and deteriorating rapidly now that the ring no longer preserves his life. He soon dies of old age, as much at peace as could be expected, under Bilbo's care in Rivendell. Thereafter the Istari and Elves depart to the Grey Havens and then on to the Undying Lands, escorting Bilbo safely back to Hobbiton along their way, to live out the rest of his days in peace.</p>

</section>