<section>
	
	<h2>How <i>Heroes</i> Should Have Gone</h2>

	<p class="description">Tidying up the loose ends and cleaning up the technical details of how powers work for a much more streamlined story.</p>

		<section>
			<h3>Volume 1: Genesis</h3>
			<p>The first volume is left largely untouched, except for some very minor changes due to a more clear rendition of how powers are inherited, instead of the mix of "it's a crap shoot", "it's based on your personality", and "like father, like son" in canon.</p>
			<p>Naturally inherited powers are tightly linked to the Y chromosome, so you get the "like father, like son" effect when you're talking literal father and son. However, as all powers originate in the brain, the specific manifestation of any particular power is partly dependent on personality too, so the son isn't always exactly like the father; but the particular neurological inclinations are inherited patrilinearly.</p>
			<p>Powers can still be inherited from the mother, or by a daughter. Furthermore, powers are not always inherited at all: sometimes, though rarely, even a child of two powered people is powerless, just as sometimes a child of two powerless people may be powered. In cases other than father-son inheritance, you get the "crap shoot" effect: the base neurological makeup to manifest powers is inherited, but the specific inclinations to particular types of powers are not. These more random gifts of powers are also more strongly influenced by the person's personality.</p>
			<p>So Matt Parkman inherits his father Maury's power (telepathy) almost exactly. Peter Petrelli inherits a power (empathic mimicry) similar to his father Arthur (power absorption), varying by their personalities. But Nathan Petrelli doesn't inherit anything, and when he's artificially given powers, he gets something completely unrelated (flight). When Nathan Petrelli and Meredith Gordon (who has fire powers) have a daughter, Claire, she gets something unrelated to either (regeneration).</p>
			<p>The big catch here, and the only significant change to the plot, is Niki Sanders (strength), DL Sanders (phasing), and their son Micah Sanders (technopathy). To match their respective powers to the new scheme, DL instead has a power similar to Micah's technopathy, which can serve a similar story purpose to phasing: "mechanopathy", the ability to control the operation of mechanical systems via touch, which in DL's case is mostly used on locks (to accomplish similar plot effects as phasing through walls), but also made him an adept auto mechanic in an earlier life.</p>
			<p>And with the exception of that change, volume 1 goes pretty much how it did.</p>
		</section>

		<section>
			<h3>Volume 2: Generations</h3>
			<p>In the second volume, the Sanders' story is streamlined. Niki does not manifest yet another alternate personality and run off to LA; DL does not survive the end of volume one only to really die in LA chasing after Niki; and Micah is not sent off to his extended family in New Orleans. Instead, DL really died in volume one; Niki befriends the Petrelli family after the end of volume one (she already knew Nathan intimately); and when she goes in to get treatment from the Company, Micah is left in the Petrellis' care. Niki later grows closer to Nathan and ends up filling Tracy Strauss's role in later volumes, instead of dying pointlessly in New Orleans.</p>
			<p>Meanwhile, Sylar, Maya, and Alejandro's story begins much as in canon; except Alejandro, instead of having only the power of stopping Maya's power, has a useful power of his own: healing. And Maya's power, instead of "poison emission", is something with a similar effect, but a bit more to the point: "sickness", the opposite of healing. After Sylar kills Alejandro, we see Alejandro is really still (barely) alive, and automatically uses his own power on himself; he will show up again later. As in canon, Maya reaches the Company to get cured of her power, and Sylar gets his strain of the Shanti virus cured and regains his power of intuitive aptitude; but not, as in canon, his telekinesis yet.</p>
			<p>The Hiro/Kensei, Matt/Mohinder/Molly, and Peter/Adam story arcs occur pretty much as in canon, culminating as they do in grabbing the Shanti virus right before Adam can release it. Only, instead of immediately destroying it like he does in canon, Peter remembers that there's someone he has to tend to first: Caitlin, who he left stranded in the future that resulted from this virus being unleashed. After considering this, and what would happen to her if that future was unmade now, Peter throws the vial of the virus at the wall away from a shocked Matt Parkman, and teleports himself away.</p>
			<p>Peter reappears in the future where he left Caitlin, where the virus has wiped out most of mankind; only now, it's obvious that this future was his fault to begin with. He spends an episode tracking down Caitlin and being a general bad-ass against everyone who's trying to stop him. Finally he finds her, and teleports back into the past with her... right near where he left, just in time to catch the vial of the virus he had thrown, which he then destroys with radiation.</p>
			<p>Meanwhile the Claire/Noah arc continues as in canon, culminating in Nathan's press conference to announce the existence of people with powers, and subsequently getting shot by future-Peter to stop that.</p>
		</section>

		<section>
			<h3>Volume 3: Villains</h3>
			<p>The third volume begins much as in canon, future-Peter trapping present-Peter in a Level 5 cell, though without the "body insertion" gimmick. Sylar returns to hunt Claire and steal her power, then attacks the Company, accidentally freeing the prisoners on Level 5 in the process while confronting Elle; though this is played up much less than in canon and is not depicted as the major plot arc of the volume. As in canon, Sylar is told that the Petrellis are his true family, and offered a chance at redemption, working with Noah to hunt down the Level 5 escapees.</p>
			<p>Present-Peter hunts down his future-self, just missing him as he watches over a recovering Nathan as in canon, and catching up to him at his own apartment; only to find Caitlin (who had been staying with him) missing, a small pile of charred ashes in her place. Future-Peter tells Peter that he has done what he came to do, and teleports back to the future, only to be killed by future-Claire as in canon. Present-Peter mourns for Caitlin, and wonders what could prompt his future self to do such a thing.</p>
			<p>Meanwhile, as in canon, Hiro inherits the Formula from his father, only to have it stolen by Daphne (working for Arthur Petrelli); and traveling to the future looking for answers, Hiro witnesses his future-self shot with energy by an empowered Ando, just before a huge explosion destroys the city, leaving more questions than answers. At Angella Petrelli's advice, Hiro digs up Adam Monroe to help against Arthur, only for Adam to have his powers stolen, though unlike canon this merely leaves him normal and consequently mortal, in Arthur's custody, but not instantly dead.</p>
			<p>Trying to understand what his future-self was trying to do, Peter uses his precognitive powers to paint the future, but only ends up with images of the Earth exploding, leaving more questions than answers. He turns then to Sylar, who is trying to be good, and asks for his help in unlocking his intuitive aptitude (which Peter so far cannot seem to mimic), so as to better understand the complex interplay of events. Unlike in canon, this occurs in the present, and there is no "hunger" to Sylar's powers that drives Peter to evil.</p>
			<p>Using intuitive aptitude together with precognition, Peter sees the connections: unbeknownst to anyone, Caitlin had already contracted the Shanti virus in the future, and she becomes patient zero of the outbreak of it again; and if Nathan had revealed the existence of supers, the effects of the Shanti virus only killing normal people would be interpreted by the normals as an attack on them by the supers (as it actually was, in Adam's original plan), which would only add to the extent to which the supers were hunted.</p>
			<p>Peter sees that his future-self succeeded in stopping Nathan's revelation, but was too late with Caitlin: the virus has already been passed on to others, and is beginning to spread. Meanwhile, he foresees what his father Arthur is up to with the Formula and trying to create an army of supers, which the Shanti virus makes much more tempting to the general public, as giving people powers would make them immune to the virus. He sees that somewhere out there is an unstable man with powers which grow in proximity to superpowered people, and that a future world of all supers will lead to this man being so powerful he will literally destroy the world: the exploding Earth he painted before.</p>
			<p>The plot thenceforth involves two tasks: stopping Arthur from creating a world of supers, and stopping the Shanti virus from destroying all the normals. The Shanti virus arc is addressed by the Company seeking out a powerful healer, which they find in Alejandro. As only supers are immune to the virus, a team of supers is sent seeking its victims to cure them. Alejandro of course is the powerhouse of the group. Claire is sent as Noah's agent, at her insistence. And Mohinder, who has taken his proto-formula which does not seem to have granted him any powers, but which has made him immune to the virus, goes along as adult supervision, at Noah's insistence. They follow leads attempting to cure people of the virus as they find them; but the virus is spreading faster than they can track down its victims and cure them, and it looks to be a hopeless cause.</p>
			<p>Most of the Arthur arc goes as in canon: many of the Level 5 escapees come to work for him thanks to Maury's recruitment, and hunt down Claire to get the Catalyst. But a notable exception to canon is that Hiro does not get partially mind-wiped by Arthur, and when he goes back in time to get the Catalyst, his mother won't give it to him because it is lethal to its bearer, which is why she, a healer, is carrying it, and yet is dying anyway; and why baby Claire must be the one to carry it, not Hiro. (Until his conflict with the Company, Adam Monroe had been the one to carry it, and was its original possessor as far as anyone knows; Arthur Petrelli took it from him and gave it to Hiro's mother to keep.) As a result of this change, Hiro doesn't get his powers stripped and doesn't end up stranded in the past, and thus Ando and Daphne do not combine their powers to travel faster than light and save him. Instead, Arthur just gets the Catalyst from Claire in the present, and things proceed as normal.</p>
			<p>Hiro does confront Arthur in the present, and is stripped of his powers then; and Ando takes the Formula to try to save him, only to gain his supercharging power, to little help. Ando's supercharging power does come to great use, however, when the anti-virus group comes seeking Hiro to send them back in time, to give them time to cure enough victims in time to stop the pandemic. At this moment Mohinder also realizes that when he took his proto-formula, he did get a power after all: he is able to sense the change in Ando and tell what power he has just acquired. Mohinder has the power to see who has what power.</p>
			<p>Ando is united with Alejandro, and over-supercharges his healing power to cure all instances of the Shanti virus everywhere at once. However, Alejandro dies in the process; it is suspected at the time that it was merely "taking on too much sickness" which did him in (as he is normally weakened after a healing), but unbeknownst to anyone yet, Ando's supercharging power is damaging to the brain of the recipient of the charge.</p>
			<p>As in canon, Nathan (with Niki at his side in place of Tracy) sides with Arthur. Peter and Sylar together confront Arthur; Peter is stipped of his powers; and Sylar decides that Arthur's team are the real good guys. Sylar learns from Arthur how to take powers from others without cutting their heads open. As Arthur explains it, both of his sons, Peter and Sylar, have the same power as he does, just manifesting in different ways: Peter has an emotional understanding of things and so empathically absorbs peoples' powers, whereas Sylar has an intellectual understanding of things and so has to study how people's brains do what they do.</p>
			<p>Arthur's power, and Peter and Sylar's inherited versions of it, were the culmination of their work on the Formula back in the old days, attempting to perfect the mutation which underlies all super powers. (Arthur hesitatingly mentions an aside about one case that pushed the research even further, but that subject was "lost"). And both Peter and Sylar, once they mature, will learn to do what Arthur can do: not only absorb other people's powers, but take them away... or give them, as he did to Nathan.</p>
			<p>Arthur tells Sylar that Nathan is not truly a Petrelli after all; that they were mistakenly switched at birth, and Sylar is the true elder Petrelli boy. Nathan overhears this, goes berserk, and decides to take his "father"'s operation down. With Niki's super-strong help, he frees Peter, Hiro, and Adam, and storms away as they return to their friends. Adam is kept in Company custody but, now powerless, he eventually becomes a trustworthy administrative member and source of valuable knowledge.</p>
			<p>Mohinder perceives that Ando's supercharging power can not only boost powers already manifested, but can force dormant powers to surface. This is not incredibly useful for an attack though, as they can't all be running around hand-in-hand with Ando while fighting. Ando has an idea however, and tries supercharging himself; at which point, he is able to discharge the built-up power in a bolt of energy. This is draining on Ando however, and he thinks he will only be able to power up one person long enough for it to make a difference in a fight. They all decide it will be Peter.</p>
			<p>The company mounts an attack force to invade Arthur's laboratory. While the forces on either side battle, Ando supercharges Peter, who then heads straight for Arthur. Using his better-understood empathic mimicry and intuitive aptitude, he now sees how to do what Arthur does; and attacking his father, he strips him of his powers, taking them for his own. Now fully empowered for the time being, he is attacked by Sylar, and the two engage in an attempt to strip each other of their powers. A sort of feedback develops between both of them and they fly away from each other, unconscious.</p>
			<p>The battle climaxes and the facility is destroyed in the resulting fire. Arthur and most of the Level 5 escapees die, along with Elle (rather than Sylar killing her as in canon). Peter's friends drag him from the building, and Sylar is left for dead. When Peter comes to again later, he is disoriented and partially amnesiac, and doesn't remember many events of the last year, or remembers them incorrectly; in particular, he's unclear on why he doesn't have any of his usual powers. His friends and family fill him in on the details, and they all wonder what has become of Sylar.</p>
			<p>In the aftermath, Nathan reveals the existence of supers to the President, and initiates a program to see to it that they are contained and controlled, as in canon; and Sylar, as disoriented as Peter was, visits his childhood home seeking answers.</p>
		</section>

		<section>
			<h3>Volume 4: Fugitives</h3>
			<p>Volume 4 goes almost exactly as in canon, the supers running from and fighting Nathan and Danko's government anti-super agency, with some few exceptions: Daphne does not die; Matt's ex-wife and kid are not brought in out of nowhere; Matt does not have precognitive powers for just a few episodes; and the subplot with Angela's sister being alive is omitted.</p>
			<p>Hiro's partially-functioning powers and brain damage are a result of Ando repeatedly supercharging him back to an empowered state temporarily, damaging his brain in the process. Peter's partially-functioning powers are a result of taking his dad's ability to grant abilities and granting himself that ability permanently, plus the subsequent scrambling from his fight with Sylar.</p>
			<p>Sylar, disoriented from that same fight, seeks out his "father", and eventually discovers him to be a powerless misanthrope. Instead of joining Danko and becoming the Big Bad by the end of the volume, he fulfills his heroic destiny, pushed a bit by Micah/Rebel, and becomes the only person who can stop Danko and his men... in his own dark way. He pretends to side with Danko just to get the shapeshifter's power, but then kills Danko and takes his place. He begins to go crazy from the shapeshifting power and his own scrambled mind anyway, and though he shuts down the program, he becomes obsessed with becoming Nathan Petrelli, spurred on by fractured memories of Arthur's revelation to him last volume. He eventually succeeds, killing Nathan and taking his place, truly believing himself to be Nathan now; and goes on to run for President.</p>
		</section>

		<section>
			<h3>Volume 5: Redemption</h3>
			<p>Much as in canon, with some technical modifications. Samuel's power is not geomancy, but nigh-omnipotence: he can do literally anything he can imagine and understand, but with a scope and magnitude limited by the support of the supers around him. He empathically draws, not specific powers, but raw power, from those around him, and can use that power to do anything within a certain scope; he can also redirect this power to temporarily boost others' powers, or enable ordinary people to temporarily have powers, which he uses as a novelty at his super-carnival. Adam claims that Samuel has the most pure manifestation of the mutation which underlies all powers, even more pure than that possessed by the Petrelli family (as manifested variously in Arthur, Peter, and Sylar), and suspects that he is the lost test subject from their early experimentation with the Formula, the one non-super kid who survived the injection, but then mysteriously vanished.</p>
			<p>The plot builds up to Samuel possibly destroying the world by surrounding himself with enough supers. His eventual aim, once meeting our heroes, is to form a feedback loop with Ando, mutually supercharging each other while drawing power from all the supers in a widening radius, to use Peter's power to awaken the powers of everyone in the whole world, creating a world full of supers for Samuel to draw power from, making him all powerful.</p>
			<p>Samuel does not realize, however, that he will be unable to control all this power, and will end up destroying the world with it. Specifically, in a future where he has succeeded, and the world has been empowered, he eventually attempts to seize rulership of the world with his superior powers; in the face of this, President "Petrelli" reveals his dark side (as he is truly Sylar), and refusing to yield power to this newcomer, a cataclysmic war breaks out between the three. Peter attempts to intervene for everybody's sake, realizing that "Nathan" is really Sylar, and his own powers having been fully reawakened by Samuel's plot. In the resulting battle, enough power is unleashed to literally destroy the entire world. In the lead up to the battle, Sylar and Samuel both disempower many of those who oppose them, including most of the heroes, but future-Ando is able to supercharge future-Hiro again to send him back in time to stop it all.</p>
			<p>Meanwhile in the present, by using his subtle mind-control powers, Samuel's plot is about to succeed. But future-Hiro arrives from the time of the exploding Earth to stop him, having been sent back by future-Ando, and decapitates Samuel with his katana as the power-syphoning is occurring, preventing that dark future.</p>
		</section>

</section>