<section>

	<h2>Unjustified</h2>

	<p class="description">A paper for a class on Philosophy of Science, 2007.</p>

	<p>The hypothetico-deductive method is an account of the way that proper science is and ought to be conducted, as proposed by Carl Hempel in Philosophy of Natural Science. His theory is opposed to the notion that hypotheses are created by some mechanical inductive method of gathering evidence and from that evidence deriving a hypothesis by some strict set of rules. </p>
	<p>Instead, the hypothetico-deductive method begins with a hypothesis invented (non-rationally) to explan the available data, and then seeks to test that hypothesis via strictly rational means. </p>
	<p>Hempel proposes two schemas for testing a hypothesis: falsification and confirmation. In both schemas, an implication “I” is somehow derived from a hypothesis “H”, giving us a conditional statement “If H, then I.”  We then test to see whether “I” is the case. If we get a result of “not I”, then the hypothesis is falsified, which is schematised logically as “If H, then I; not I; therefore, not H.” This form is deductively valid and I do not intend to challange it. </p>
	<p>Alternately, our test result could be “I”, in which case Hempel proposes that the form “If H, then I; I; therefore, H” captures the notion that the hypothesis has been confirmed. This form is not deductively valid, which Hempel readily admits; yet he still claims that it gives some measure of rational justification for believing “H”. I intend to attack this claim on the basis that non- deductive justification is generally impossible (rendering any of this sort of confirmation impossible), and that falsification is therefore the only valid method of science. </p>
	<p>Science is merely an empirical theory of epistemology — an account of how we come to be justified to believe things. Thus it faces a problem which all epistemological theories face: the problem of justification. The problem in brief lies in the claim that in order for belief in “P” to be rational, we require some reason “Q” to justify it; yet “Q” itself then requires justification, for which we propose “R”, ad nauseum. This leads to an infinite regress, and the problem that all of our beliefs appear to be ultimately unjustifiable. There are two main proposed solutions to this problem, and though I do not have room here to elaborate on them, I can briefly describe them and their faults. The first is “foundationalism”, which holds that some particular beliefs simply do not require justification, and from them, all other beliefs can be justified. This has the fault that the choice of foundational beliefs is seemingly arbitrary. The other is “coherentism”, which holds that a belief is justified if it does not contradict the rest of the belief system of which it is a part. This has the fault of being circular, with a set of beliefs mutually justifying each other, none of them necessarily related at all to observable reality. </p>
	<p>I propose that justification thus understood is a doomed project from the start, and that instead of asking “why should we believe this?”, we should instead believe whatever we want for whatever reasons (independent of reason), and then ask only “why shouldn’t we believe this?”, subjecting those beliefs to logical and empirical criticism. If a theory is not falsified, it remains justified in the sense that we have no reason to reject it, and thus we are permitted to believe it; but no theory is ever justified in the sense of giving a particular reason that obliges us to believe it. We are permitted by reason to believe anything we wish, besides those things which are prohibited by reason; but we are never obliged by reason to believe any particular idea. We may be obliged by deductive reasoning to believe certain ideas in the condition that we believe certain others, if failure to do so would result in contradiction (and thus be prohibited by reason); but we are not obliged to believe those others in the first place. We are equally free to believe any set of meaningful propositions which, taken together, do not contradict each other or the evidence. </p>
	<p>But I imagine that Hempel still want to say that confirmation — finding new data that agrees with the predictions of a hypothesis — somehow gives us some sort of reason that obliges us (however weakly) to believe that hypothesis. With that I still disagree, as confirmation as he seems to understand it is just an instance justification in the obligatory sense, which is impossible. However, I will grant him that the gathering of new evidence does give us greater overall confidence in all theories that still, in light of that new evidence, are not falsified. That is, it allows us to be more certain that we are permitted by reason to believe those theories that are still not clearly prohibited by reason. Furthermore, the derivation of new non-falsifying implications from a theory gives us greater confidence that that theory is not in fact falsified by the evidence we have. In short, the more evidence we have at hand, the more confident we can be that we are in fact rationally permitted to believe any of our surviving theories; and the more we examine a given theory, the more confident we can be that we’ve not overlooked a problem with it. But no particular test ever confirms any one particular theory, in the sense of giving reasons that oblige us to believe that theory. </p>
	<p>Furthermore, I will grant that something like Hempel’s confirmation schema is a useful method of practice — a good way of determining what tests to perform and what new evidence to gather. In one way of doing things, we could gather new data and evidence at random, and then check each of our contending theories to see if their implications agree with this new data, discarding those that don’t, leaving us with (possibly) fewer contending theories, and greater confidence in all those that remain. But say we reverse that order: we derive an implication from a theory first, which, if upheld, would give us more confidence that we haven’t overlooked a problem with that theory. But we intentionally derive an implication for which there is yet no evidence to compare. So we gather evidence regarding that, and then double-check that the particular theory we’re concerned about has not been falsified. If it has not been, then we have the scenario which would typically be called “confirmation”. But this is not in fact directly confirming that theory in particular, in the sense of giving positive justification obliging us (however weakly) to believe it. Rather, it is simply failing to falsify a theory, while at the same time giving us greater overall confidence that we are permitted to believe any and all contending theories that remain. The focus on the theory’s implications merely gave us a better guide to what evidence would be relevant than random observation otherwise would have.</p>

</section>