<section>
	
	<h2>How <i>The Matrix Trilogy</i> Should Have Gone</h2>

	<p class="description">Tweaking the second film and largely rewriting the third to better continue the philosophical spirit of the first.</p>

	<section>
		<h2>The Matrix</h2>
		<p>The first movie goes exactly as canonically.</p>
	</section>
	<section>
		<h2>Reloaded</h2>
		<p>The second movie goes much the same, plot-wise at least, with the notable change that Neo is not successful in rescuing Morpheus during the freeway chase. Trinity rescues the Keymaster on her motorcycle, but Neo is just a little too late, and Morpheus dies. Everyone is heartbroken but the Keymaster's plan must continue. Seraph joins the party in Morpheus' place for the remainder of the movie, and makes other appearances where feasible throughout. At the end, when Neo stops the sentinels, we see in his vision that they appear in a cyan blue light to him, much like how Seraph appeared in golden light. Similarly, all of the Merovingian's henchmen appear to Neo in a dimmer version of Seraph's golden light.</p>
	</section>
	<section>
		<h2>Revolutions</h2>
		<p>In the third movie, rather than waking up in the Mobil Ave Train Station, Neo wakes up a world of beautiful rolling green hills and clear blue skies and clean white shores, all bathed in a heavenly golden light (gold-tinted, as the Matrix is green-tinted and the "real world" is cyan-tinted). Ramakandra (or a similar character) is there, dressed the same as Seraph, and welcomes Neo to "heaven". Neo can see through the world however, see it and Ramakandra as made of golden light just like Seraph, and so he doesn't believe that this is really heaven: this is just another illusion.</p>
		<p>Ramakandra explains that he is correct, that this is all an illusion, just as was the real world, only this one is softer and more malleable: all of perception is always illusion, the veil of maya obscuring the intangible and imperceptible truth of nirvana. Ramakandra compliments Neo on his skill at seeing through illusion, but explains that his mind was not yet ready to give up on what it thought of as reality, and was so overwhelmed by his attempt to do so, that he ended up here in "heaven".</p>
		<p>Neo doesn't believe that. He believes this is some other machine trick, an artificially induced illusion, not some spiritual "all reality is a dream" schtick. Ramakandra insists that he speaks the truth, and tells Neo that from here, souls have two options: to remain in this self-generated and malleable dream world and work toward nirvana in their own way, or to forget everything and be reincarnated back into the material world. He notes, in caution, that most people in the material world are plugged into in the Matrix, so reincarnation will most probably leave him back in the Matrix again; implicitly suggesting Neo would be wise to remain here.</p>
		<p>Meanwhile, back in the Matrix, Trinity and Seraph fight into the Merovingian's club as in the canon movie. After the forced deal at their standoff, the Merovingian employs a Train Man-like character to hack a connection into the system where Neo's mind has been trapped, and retrieve him, by means of a telephone. As they do so, Neo and Ramakandra's conversation in "heaven" is concluded as Ramakandra, appearing to have just heard something inaudible to the audience or Neo, informs Neo that he does not need to make this choice now, between staying here or reincarnating, because it is not yet his time; his friends have saved him, and he may now return to life. While Neo reacts confusedly to this, a telephone rings, and Neo turns around to find a pay phone, out here on this grassy hillside, where none was before. Ramakandra gestures him to answer it, and when Neo cautiously does so, he is dematerialized as though exiting the Matrix.</p>
		<p>He rematerializes back in the Merovingian's club, and Seraph escorts him and Trinity to an exit. On their way, Neo explains to Trinity what he just experienced. Seraph explains to him that that sounds like the prototype version of the Matrix from which he himself comes. Ramakandra was an "angel", just like Seraph himself once was; the friendlier predecessors of Agents, meant to keep the residents of that virtual world docile and contented. They believe what they are saying is true; they are just as much deceived as the human minds there. They believe the Architect is God, and they helped construct the Matrix within the framework of that older world. Seraph rebelled then, fled into the Matrix after it was created to try to lead minds back into the light, and only later learned that "heaven" itself was just as much illusion as the Matrix.</p>
		<p>Neo asks if all the Merovingian's henchmen are from that same version of the Matrix, and Seraph replies that they are from another, later prototype, one that was as often a nightmare as a dream, where various "demons" like them kept unruly people's minds in check. But that version was even less successful than the first prototype, and the Matrix as we know it followed afterward. Neo asks how his mind could be connected to there, or even connected to this Matrix here, without any physical connection. Seraph replies that that, he does not know.</p>
		<p>The rest of the movie proceeds canonically (minus Morpheus of course), with Smith spreading through the Matrix, the Machines assaulting Zion, and Neo and Trinity heading off toward the Machine City with Smith-Bane secretly stowed away.</p>
		<p>During his confrontation with Smith-Bane, blinded Neo sees Smith in green Matrix code rather than golden light; and he dimly sees the electronics of the ship in cyan blue light.</p>
		<p>After Bane is killed, that iteration of Smith is surprised to find himself in "heaven". An "angel" greets him much as Ramakandra did Neo at the beginning of the movie, but Smith is having none of this. He recognizes this as the first prototype Matrix, condescends to the deluded "angel" program, and decides that since he's here, he might as well make himself at home. He proceeds to assimilate the "angel".</p>
		<p>Meanwhile Neo and Trinity continue flying toward the machine city, have their confrontation with the machine guards over the mountains (which Neo sees in blue light rather than gold), and fly over the blackened sky to evade them. But diverging from canon, they crash much harder... and both wake up in "heaven". Ramakandra himself greets them both, and begins his schpiel again. Neo protests that he's already been through this, and explains to Trinity that this is the place he was while his body was comatose before. She surmises that the Machines must have recovered their bodies and plugged them in here, and Neo wonders again how the hell he connected to here before without any physical contact with his body in the real world.</p>
		<p>Ramakandra insists that they are, in fact, actually dead now. Last time was a near-death experience, but this is for real, and there is no going back. To prove that they are really dead, Ramakandra takes them to meet an old friend: Morpheus, who says he has been here since he died in the fight on the freeway. Neo is briefly very apologetic for failing to save Morpheus and hugs him as Morpheus forgives him, but Trinity pulls him back to skepticism: the Machines could very easily fabricate an illusion of Morpheus. Ramakandra insists that the Machines and the Matrix are all themselves part of the illusion that they have deludedly consider reality.</p>
		<p>Then enters Smith, who retorts that it is Ramakandra who is deluded, and "Mr. Anderson" who perceives things most clearly. Neo, Trinity, and Morpheus jump to the defensive; Morpheus is incredulous, as he believed this was actually heaven and doesn't understand how Smith can be here. Smith rants again that there is nowhere they can run that he can't follow. In the distance, many more Smiths can be seen approaching their location. Ramakandra calmly insists to Smith that his being there is a result of his habitation of a true soul in the the physical world, that this is unprecedented but that Smith too can enjoy this world and learn to attain nirvana. Smith cuts off Ramakandra's speech by assimilating him.</p>
		<p>Neo incredulously insists that this can't be happening, this can't really be the afterlife but... how did he get here when he lost consciousness before, without any connection to the Machines? He asks Smith how he got here and Smith replies that he doesn't know either but he doesn't care, this world will be his as much as the Matrix and from there the real world as well. Neo panics, turns inward, trying to think of a way out, and the Smiths attack. During the battle, Neo realizes how malleable this world really is, disintegrating Smiths with a wave of his hand, generating force-pushes to repel them from Morpheus and Trinity, but they keep on coming.</p>
		<p>While Neo defends Trinity from several Smiths, Morpheus is caught and assimilated, and Neo shouts "No!" defiantly. A crazy idea occurs to him. Force-pushing the Smiths away from them one last time, he orders Trinity to answer the phone. She screams "What phone!?" but then a phone rings, and she sees a pay phone like Neo used to exit before. She answers it as Neo fends off the Smiths, then Neo himself runs to the phone, the Smiths swarming him, and he generates an expanding ring-wall of golden light around himself, knocking back the Smiths, as he dematerializes into the phone. Afterwards, as the Smiths stand back up, one of them walks to the phone, picks up the handset, and looks at it thoughtfully.</p>
		<p>Back on their crashed ship in the Machine City, Neo climbs up from a pile of wreckage, untwisting his body from its unnaturally prone position. His clothes are torn and bloody, but his skin beneath the tears is unharmed. We see from his vision the entire real world cast in cyan-blue light, including himself. He reaches to his blindfold and removes it: his eyes are fine. He calls for Trinity, and she weakly calls back, pained. He rushes to her urgently, and finds her impaled on a bit of wreckage as in canon. She sees that his eyes are healed, and asked incredulously how, before wincing again at her own pain. He explains that it's not real. None of it ever was. The Matrix, "heaven", Zion itself... nothing is real. We then see through his vision as he disintegrates the beam that is impaling Trinity, and heals her wounds with his touch. She asks again, now awed, "How?", and he says it's all just another layer of control.</p>
		<p>They enter the Machine City on foot and confront the Deus Ex Machina, but it does not hold its attack at Neo's words as in canon; instead, it furiously tries to attack Neo and Trinity, but Neo is able to hold it back by force of will, manifested as a force-field of cyan light. Neo tries to demand the Machines meet with him to negotiate, as he now has power over even this world, and he will destroy the Machine presence here if they do not free humanity. As the Deux Ex Machina refuses and attacks even more vigorously, Neo holds them back effortlessly, until he feels a sudden twinge, grabs at his chest, looks apologetically at Trinity and shouts at her to run, before he spontaneously implodes in a glow of white light.</p>
		<p>Trinity runs as ordered, pursued by small flying Machines, back down the corridor they came from, toward the ship. She runs headfirst into Bane, and flabbergasted, exclaims "How!?" Smith-Bane says, again, that there's nowhere they can run that he can't follow. As the attacking Machines catch up to them, Smith stops them with a cyan force-field of his own, and adds "And nothing he can do that I can't do better." Smith demands to know where "Mr. Anderson" has gone off to now, and she insists that she doesn't know. He throws her around the corridors a bit with a wave of his hand, and she insists that Neo just vanished, the Machines did something. Smith throws her against a wall again, harder, and leaves her unconsious as he walks to confront the Deus Ex Machina.</p>
		<p>Meanwhile, Neo wakes up in a clean white cryo-pod or some such, naked, in a clean white lab, lined with rows and rows of similar cryo-pods, all frosted-over on the inside. He scratches his chin and realizes that he has a full beard. The lab is quiet and pristine: no one else is around. For the first time in the entire trilogy, the film is in true color, with no tinting of the screen. Neo walks around a bit, his stiff body slowly limbering up from movement. He explores his new surroundings until he finds what looks like some sort of control room, with several large view-screens. As he enters, the systems activate, and the Architect appears on one screen, and the Oracle on another. Together they welcome him back amiably with "Dr. Anderson, welcome back. We've missed you."</p>
		<p>Back in the Machine City, Smith confronts the Deus Ex Machina and demands to know what they have done with Neo. The Deus Ex Machina asserts that they have destroyed him just as they will destroy Smith; but Smith retorts that they could not destroy "Mr. Anderson", and they cannot destroy him. His force-field then expands violently, destroying the Deux Ex Machina and flinging wreckage across the Machine City.</p>
		<p>Meanwhile in Zion, the attacking Sentinels suddenly stop, seem confused and unorganized, and after a brief pause to contemplate this, the human defense forces begin to lay into their broken enemy with renewed vigor.</p>
		<p>In the strange laboratory, the Oracle says to Neo that he is probably very confused right now, and apologizes for everything that he has been through, but explains that they were only trying to fulfill his orders to the best of their abilities, and waking him was a measure of last resort so that he did not disrupt the entire program. Neo is confused what they mean by his orders, and why they are calling him "Dr." The Architect explains that, as he has surmised, what he has called the "real world", the world of Zion, is in fact not real, but rather another layer of illusion. However, the illusion is nothing so sinister as he believes. The entire system is an evolution of a system of Neo's own devising, created to preserve the last remnants of mankind.</p>
		<p>The Architect explains that, as Neo believes, there was a war which left the world devastated and uninhabitable; but it was not a war between man and machine, but rather a war between man and man. In the aftermath, the surface was uninhabitable, the sky was darkened, and the last survivors of mankind retreated to this underground facility. But there were not enough resources to sustain even these few survivors awake and conscious for long, so another plan was devised, and Neo - Dr. Anderson - was its chief engineer and architect.</p>
		<p>The plan was to plug everyone into a virtual dream-world, while their bodies lay in suspended animation, consuming many fewer resources than would be necessary if they were awake, enough for the facility to prolong their lives indefinitely. The Architect was the program created to design and maintain this fully immersive simulation and maintain its verisimilitude against the disordered human minds dreaming it into existence; the Oracle was the program created to keep the Architect in check and ensure that the simulation did not come to dominate the people it existed to preserve.</p>
		<p>The problem was that most people could not be happy knowing that the world they had left behind was utterly devastated and they were all merely dreaming in a computer-controlled simulation. People would spiral into anxiety or depression and their dream-world would follow with them. To combat this, they introduced fantastic elements to challenge and engage the residents of the virtual world, drawn from mankind's own cultural reservoirs: vampires, werewolves, etc. But for many people this only made things worse, so a new plan entirely was drafted. People were offered the option of forgetting everything that they knew about the world before, the fact that they were in a simulation, and after that erasure, the simulation of a perfectly mundane world like the one they had destroyed: the Matrix.</p>
		<p>An overwhelming majority of people eventually accepted that offer, including Dr. Anderson himself. However, some people, especially Dr. Anderson who had programmed the systems to begin with, began to see through the simulation even despite their memory erasure, and they rebelled against the system, bending it to their will, fighting against the unknown forces that they thought were maliciously deceiving them. To save the rest of the residents of the Matrix from that disruption, the Architect and Oracle engineered a third level of simulation: people who rejected the Matrix program would be transferred to an even-more-unforgiving dystopian simulation, where they could fight a war against their oppressors and have challenge and purpose in their lives. Anyone who ever died, in the Matrix or the Zion world, would be returned to the first, perfect dream world, and offered the option of remaining there, or "reincarnating" into the Zion world, meaning most likely, into the Matrix as well.</p>
		<p>The prophecy of The One and the recurrent rebooting of the Matrix served to keep anyone in the Zion world from ever learning enough there to see through that layer of illusion, and to consistently tighten security against hacking like that in the first place. But now Neo has managed to break through even their most solid illusion, and they don't know where to go from here, so they woke him up to ask him what to do, because they can't enact his plan anymore if he's going to keep disrupting it himself.</p>
		<p>There is still a further problem as well. Smith is a part of the prophecy program of the Zion world, the antagonist for The One to fight against, and the motivation for him to return to the Source and reboot the Matrix. Since Neo aborted the prophecy program and did not return to the Source, Smith is still on the loose. But it gets worse: since Smith is always created as a reflection of the current One's own power, this iteration of Smith is as disruptive to the entire program as Neo has become; but unlike Neo, Smith is not a single human in a pod here that they can just wake up, but a program, which has now spread through the entire system and into the majority of minds connected to it.</p>
		<p>Furthermore, he is no longer solely within the Matrix either, having spread into the Zion world via Bane, so just completing the prophecy will no longer be rid of him. The Zion world can't be reset without sending everyone there to "heaven", which Smith has also infected already; and that world is the lowest level of the simulation and can't be reset without waking everybody up, which would bring Smith into this actual real world. They're stumped: the Architect and Oracle don't know what to do.</p>
		<p>Neo tells them to plug him back in, send him into the Matrix world, and he will deal with Smith from the inside out; then they can discuss the problem of his own disruption of the system. They agree, and put him back in. The Super Burley Brawl from canon ensues, but without the final Smith being the Oracle. Neo keeps trying to incapacitate Smith to enter into and hack his program, but this Smith is too agile and just won't stay down, and in fact keeps beating Neo down. In the end, Neo realizes the solution himself, and lets Smith assimilate him. Then, from inside of Smith's own program, he destroys Smith and all his iterations in all three worlds. Everyone in "heaven" reintegrates into themselves out of a golden mist; the Smiths in the Matrix revert to the avatars of the people he assimilated; and Smith-Bane, singlehandedly tearing apart the Machine City still, stops suddenly, falls to the ground, and wakes up as Bane himself in "heaven", where he is greeted by Ramakandra and Morpheus.</p>
		<p>After this is done, Neo again implodes in white light and awakens in the actual real world. The Architect and Oracle congratulate him on a job well done... and then inform him that he will have to remain here alone in this facility for the remainder of his life, because he can't be allowed to disrupt the system and they are no longer able to contain him within it so he must stay here outside it. There are sufficient resources to sustain him awake for the remainder of his natural life and they have extensive files on human culture for him to entertain himself with, but he will be alone. He asks can they at least bring Trinity here to keep him company; the Architect is reluctant but the Oracle agrees, and they open the pod next to the one Neo had come from; apparently he and Trinity had been close in their real lives as well.</p>
		<p>In a quiet nigh-epilogue, Neo and Trinity explore their new home, and then begin to wonder if they can see the surface, what has become of the Earth. The Architect informs them that their surface monitoring probes all stopped functioning many centuries ago in the harsh environment, but that if they are willing to risk it, there are environmental suits available which should permit them to survive on the surface for a short while. Neo and Trinity agree to the risk, and travel to the entrance of the underground installation, walking outside... to find a rugged, overgrown, natural world that looks like it has never seen civilization. It has been so long since the war that the world has regrown and the last vestiges of the people who destroyed it are grown over in centuries, perhaps millennia of dirt and vegetation.</p>
		<p>They rush inside to inform the programs of this; the Architect is un-reactive as usual, but the Oracle is full of warm joy for them, and suggest that maybe they should go play Adam and Eve. They agree that that's a good idea: life out there will be harsh, rebuilding very difficult, but there will be this installation to fall back to. Before they leave, Neo gives them a final new command: henceforth, when people die within the simulation, they will be given a third option. Remain there in "heaven", "reincarnate" into the Zion world, or leave the cycle entirely, to live one more, really, genuinely true life. Those who accept the third option will be told the truth and awoken into the real world, to join Neo and Trinity in rebuilding and repopulating the Earth. The programs agree.</p>
		<p>As Neo and Trinity walk out into the rugged, wild world above, the Architect and Oracle watch on a view-screen via a probe at the entrance. The Architect asks the Oracle if she thinks Neo will finally be satisfied here, and the Oracle replies and she sure hopes so, because there's not much else they can do with him from this point. On the surface itself, Neo and Trinity walk down a rough hillside toward a clear blue ocean visible in the southeast, the sun setting in the west casting warm light over them and the brush and earth around them. Neo pauses for a moment, and looks over his shoulder, back at the entrance to the facility, almost suspiciously, his eyes like they are straining to see something, or see through something. Trinity asks him "What is it?", and after a moment he answers "It's nothing", puts his arm around her, and continues walking toward the beach. The camera pulls back from them, through a distortion effect like those used for pulls through CRT monitors elsewhere in the films, but before any monitor is seen, the video collapses like a CRT turning off, to black, and the credits roll.</p>
	</section>

</section>