Search.appendIndex(
    [
                {
            "fqsen": "\\crumbs_from_segments\u0028\u0029",
            "name": "crumbs_from_segments",
            "summary": "Generate\u0020an\u0020array\u0020of\u0020crumbs\u0020from\u0020path\u0020segments",
            "url": "namespaces/default.html#function_crumbs_from_segments"
        },                {
            "fqsen": "\\path_from_url\u0028\u0029",
            "name": "path_from_url",
            "summary": "Extract\u0020and\u0020normalize\u0020the\u0020path\u0020portion\u0020of\u0020a\u0020request\u0020URL.",
            "url": "namespaces/default.html#function_path_from_url"
        },                {
            "fqsen": "\\root_determination\u0028\u0029",
            "name": "root_determination",
            "summary": "Determine\u0020the\u0020project\u0020root\u0020directory\u0020based\u0020on\u0020the\u0020server\u0020API.",
            "url": "namespaces/default.html#function_root_determination"
        },                {
            "fqsen": "\\segments_from_path\u0028\u0029",
            "name": "segments_from_path",
            "summary": "Convert\u0020a\u0020path\u0020string\u0020into\u0020an\u0020array\u0020of\u0020its\u0020segments.",
            "url": "namespaces/default.html#function_segments_from_path"
        },                {
            "fqsen": "\\head_for_crumb\u0028\u0029",
            "name": "head_for_crumb",
            "summary": "Extracts\u0020metadata\u0020from\u0020the\u0020head\u0020file\u0020for\u0020a\u0020given\u0020crumb.",
            "url": "namespaces/default.html#function_head_for_crumb"
        },                {
            "fqsen": "\\image_path_resolution\u0028\u0029",
            "name": "image_path_resolution",
            "summary": "Resolve\u0020the\u0020correct\u0020image\u0020path,\u0020checking\u0020both\u0020the\u0020provided\u0020path\nand\u0020the\u0020fallback\u0020_media\/images\/\u0020directory.",
            "url": "namespaces/default.html#function_image_path_resolution"
        },                {
            "fqsen": "\\images_discovered\u0028\u0029",
            "name": "images_discovered",
            "summary": "Discover\u0020images\u0020in\u0020a\u0020directory.",
            "url": "namespaces/default.html#function_images_discovered"
        },                {
            "fqsen": "\\is_image_file\u0028\u0029",
            "name": "is_image_file",
            "summary": "Check\u0020if\u0020a\u0020given\u0020file\u0020is\u0020an\u0020image\u0020file",
            "url": "namespaces/default.html#function_is_image_file"
        },                {
            "fqsen": "\\lightbox_navigation\u0028\u0029",
            "name": "lightbox_navigation",
            "summary": "Determine\u0020the\u0020navigation\u0020\u0028previous\u0020and\u0020next\u0020images\u0029\u0020for\u0020a\u0020lightbox.",
            "url": "namespaces/default.html#function_lightbox_navigation"
        },                {
            "fqsen": "\\main_resolution\u0028\u0029",
            "name": "main_resolution",
            "summary": "Resolve\u0020the\u0020main\u0020type\u0020for\u0020a\u0020given\u0020route.",
            "url": "namespaces/default.html#function_main_resolution"
        },                {
            "fqsen": "\\scripts_for_crumb\u0028\u0029",
            "name": "scripts_for_crumb",
            "summary": "Renders\u0020the\u0020script\u0020links\u0020for\u0020a\u0020given\u0020crumb\u0020if\u0020a\u0020scripts.js\u0020file\u0020exists\nin\u0020the\u0020__scripts\/\u0020subdirectory\u0020of\u0020that\u0020crumb.",
            "url": "namespaces/default.html#function_scripts_for_crumb"
        },                {
            "fqsen": "\\styles_for_crumb\u0028\u0029",
            "name": "styles_for_crumb",
            "summary": "Renders\u0020the\u0020style\u0020links\u0020for\u0020a\u0020given\u0020crumb\u0020if\u0020a\u0020styles.css\u0020file\u0020exists\nin\u0020the\u0020__styles\/\u0020subdirectory\u0020of\u0020that\u0020crumb.",
            "url": "namespaces/default.html#function_styles_for_crumb"
        },                {
            "fqsen": "\\subgallery_image_count\u0028\u0029",
            "name": "subgallery_image_count",
            "summary": "Recursively\u0020count\u0020all\u0020images\u0020in\u0020a\u0020subgallery.",
            "url": "namespaces/default.html#function_subgallery_image_count"
        },                {
            "fqsen": "\\title_resolution\u0028\u0029",
            "name": "title_resolution",
            "summary": "Resolve\u0020the\u0020page\u0020title\u0020based\u0020on\u0020various\u0020inputs.",
            "url": "namespaces/default.html#function_title_resolution"
        },                {
            "fqsen": "\\render_gallery\u0028\u0029",
            "name": "render_gallery",
            "summary": "Render\u0020a\u0020gallery\u0020of\u0020images.",
            "url": "namespaces/default.html#function_render_gallery"
        },                {
            "fqsen": "\\PROJECT_ROOT",
            "name": "PROJECT_ROOT",
            "summary": "The\u0020root\u0020of\u0020the\u0020project",
            "url": "namespaces/default.html#constant_PROJECT_ROOT"
        },                {
            "fqsen": "\\CrumbsFromSegmentsTest",
            "name": "CrumbsFromSegmentsTest",
            "summary": "Tests\u0020for\u0020crumbs_from_segments",
            "url": "classes/CrumbsFromSegmentsTest.html"
        },                {
            "fqsen": "\\CrumbsFromSegmentsTest\u003A\u003Atest_simple_segments\u0028\u0029",
            "name": "test_simple_segments",
            "summary": "",
            "url": "classes/CrumbsFromSegmentsTest.html#method_test_simple_segments"
        },                {
            "fqsen": "\\PathFromURLTest",
            "name": "PathFromURLTest",
            "summary": "Tests\u0020for\u0020path_from_url",
            "url": "classes/PathFromURLTest.html"
        },                {
            "fqsen": "\\PathFromURLTest\u003A\u003Atest_root_path\u0028\u0029",
            "name": "test_root_path",
            "summary": "",
            "url": "classes/PathFromURLTest.html#method_test_root_path"
        },                {
            "fqsen": "\\PathFromURLTest\u003A\u003Atest_strips_query_string\u0028\u0029",
            "name": "test_strips_query_string",
            "summary": "",
            "url": "classes/PathFromURLTest.html#method_test_strips_query_string"
        },                {
            "fqsen": "\\PathFromURLTest\u003A\u003Atest_preserves_file_path\u0028\u0029",
            "name": "test_preserves_file_path",
            "summary": "",
            "url": "classes/PathFromURLTest.html#method_test_preserves_file_path"
        },                {
            "fqsen": "\\PathFromURLTest\u003A\u003Atest_no_query_string\u0028\u0029",
            "name": "test_no_query_string",
            "summary": "",
            "url": "classes/PathFromURLTest.html#method_test_no_query_string"
        },                {
            "fqsen": "\\PathFromURLTest\u003A\u003Atest_empty_query_only\u0028\u0029",
            "name": "test_empty_query_only",
            "summary": "",
            "url": "classes/PathFromURLTest.html#method_test_empty_query_only"
        },                {
            "fqsen": "\\RootDeterminationTest",
            "name": "RootDeterminationTest",
            "summary": "Tests\u0020for\u0020root_determination",
            "url": "classes/RootDeterminationTest.html"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_cli_server_uses_parent_directory\u0028\u0029",
            "name": "test_cli_server_uses_parent_directory",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_cli_server_uses_parent_directory"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_cli_server_handles_trailing_slash\u0028\u0029",
            "name": "test_cli_server_handles_trailing_slash",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_cli_server_handles_trailing_slash"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_cli_server_root_directory_remains_root\u0028\u0029",
            "name": "test_cli_server_root_directory_remains_root",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_cli_server_root_directory_remains_root"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_cli_server_empty_current_dir_returns_dot\u0028\u0029",
            "name": "test_cli_server_empty_current_dir_returns_dot",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_cli_server_empty_current_dir_returns_dot"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_non_cli_server_uses_document_root\u0028\u0029",
            "name": "test_non_cli_server_uses_document_root",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_non_cli_server_uses_document_root"
        },                {
            "fqsen": "\\RootDeterminationTest\u003A\u003Atest_empty_document_root_is_returned_as_is\u0028\u0029",
            "name": "test_empty_document_root_is_returned_as_is",
            "summary": "",
            "url": "classes/RootDeterminationTest.html#method_test_empty_document_root_is_returned_as_is"
        },                {
            "fqsen": "\\SegmentsFromPathTest",
            "name": "SegmentsFromPathTest",
            "summary": "Tests\u0020for\u0020segments_from_path",
            "url": "classes/SegmentsFromPathTest.html"
        },                {
            "fqsen": "\\SegmentsFromPathTest\u003A\u003Atest_root_path_has_no_segments\u0028\u0029",
            "name": "test_root_path_has_no_segments",
            "summary": "",
            "url": "classes/SegmentsFromPathTest.html#method_test_root_path_has_no_segments"
        },                {
            "fqsen": "\\SegmentsFromPathTest\u003A\u003Atest_single_segment\u0028\u0029",
            "name": "test_single_segment",
            "summary": "",
            "url": "classes/SegmentsFromPathTest.html#method_test_single_segment"
        },                {
            "fqsen": "\\SegmentsFromPathTest\u003A\u003Atest_multiple_segments\u0028\u0029",
            "name": "test_multiple_segments",
            "summary": "",
            "url": "classes/SegmentsFromPathTest.html#method_test_multiple_segments"
        },                {
            "fqsen": "\\SegmentsFromPathTest\u003A\u003Atest_redundant_slashes_are_removed\u0028\u0029",
            "name": "test_redundant_slashes_are_removed",
            "summary": "",
            "url": "classes/SegmentsFromPathTest.html#method_test_redundant_slashes_are_removed"
        },                {
            "fqsen": "\\SegmentsFromPathTest\u003A\u003Atest_empty_string\u0028\u0029",
            "name": "test_empty_string",
            "summary": "",
            "url": "classes/SegmentsFromPathTest.html#method_test_empty_string"
        },                {
            "fqsen": "\\DummyTest",
            "name": "DummyTest",
            "summary": "Dummy\u0020test\u0020to\u0020make\u0020sure\u0020PHPUnit\u0020is\u0020working",
            "url": "classes/DummyTest.html"
        },                {
            "fqsen": "\\DummyTest\u003A\u003AtestAlwaysPasses\u0028\u0029",
            "name": "testAlwaysPasses",
            "summary": "",
            "url": "classes/DummyTest.html#method_testAlwaysPasses"
        },                {
            "fqsen": "\\HeadForCrumbTest",
            "name": "HeadForCrumbTest",
            "summary": "Tests\u0020for\u0020head_for_crumb",
            "url": "classes/HeadForCrumbTest.html"
        },                {
            "fqsen": "\\HeadForCrumbTest\u003A\u003Atest_returns_empty_array_when_head_missing\u0028\u0029",
            "name": "test_returns_empty_array_when_head_missing",
            "summary": "",
            "url": "classes/HeadForCrumbTest.html#method_test_returns_empty_array_when_head_missing"
        },                {
            "fqsen": "\\HeadForCrumbTest\u003A\u003Atest_extracts_title_from_head_file\u0028\u0029",
            "name": "test_extracts_title_from_head_file",
            "summary": "",
            "url": "classes/HeadForCrumbTest.html#method_test_extracts_title_from_head_file"
        },                {
            "fqsen": "\\HeadForCrumbTest\u003A\u003Atest_extracts_multiple_metadata_fields\u0028\u0029",
            "name": "test_extracts_multiple_metadata_fields",
            "summary": "",
            "url": "classes/HeadForCrumbTest.html#method_test_extracts_multiple_metadata_fields"
        },                {
            "fqsen": "\\HeadForCrumbTest\u003A\u003Atest_deeper_crumb_overrides_shallow\u0028\u0029",
            "name": "test_deeper_crumb_overrides_shallow",
            "summary": "",
            "url": "classes/HeadForCrumbTest.html#method_test_deeper_crumb_overrides_shallow"
        },                {
            "fqsen": "\\ImagesDiscoveredTest",
            "name": "ImagesDiscoveredTest",
            "summary": "Tests\u0020for\u0020images_discovered",
            "url": "classes/ImagesDiscoveredTest.html"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_setUp"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003Atest_leaf_directory_returns_all_images\u0028\u0029",
            "name": "test_leaf_directory_returns_all_images",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_test_leaf_directory_returns_all_images"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003Atest_single_subgallery_rolls_up_count\u0028\u0029",
            "name": "test_single_subgallery_rolls_up_count",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_test_single_subgallery_rolls_up_count"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003Atest_grandchildren_are_counted_recursively\u0028\u0029",
            "name": "test_grandchildren_are_counted_recursively",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_test_grandchildren_are_counted_recursively"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003Atest_empty_directories_do_not_create_tiles\u0028\u0029",
            "name": "test_empty_directories_do_not_create_tiles",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_test_empty_directories_do_not_create_tiles"
        },                {
            "fqsen": "\\ImagesDiscoveredTest\u003A\u003Atest_mixed_leaf_and_subgallery\u0028\u0029",
            "name": "test_mixed_leaf_and_subgallery",
            "summary": "",
            "url": "classes/ImagesDiscoveredTest.html#method_test_mixed_leaf_and_subgallery"
        },                {
            "fqsen": "\\MainResolutionTest",
            "name": "MainResolutionTest",
            "summary": "Tests\u0020for\u0020main_resolution",
            "url": "classes/MainResolutionTest.html"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_main_php_file_takes_precedence\u0028\u0029",
            "name": "test_main_php_file_takes_precedence",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_main_php_file_takes_precedence"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_index_php_redirects\u0028\u0029",
            "name": "test_index_php_redirects",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_index_php_redirects"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_index_html_redirects\u0028\u0029",
            "name": "test_index_html_redirects",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_index_html_redirects"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_directory_listing_when_indexes_enabled\u0028\u0029",
            "name": "test_directory_listing_when_indexes_enabled",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_directory_listing_when_indexes_enabled"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_directory_without_indexes_is_error\u0028\u0029",
            "name": "test_directory_without_indexes_is_error",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_directory_without_indexes_is_error"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_missing_path_is_error\u0028\u0029",
            "name": "test_missing_path_is_error",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_missing_path_is_error"
        },                {
            "fqsen": "\\MainResolutionTest\u003A\u003Atest_main_php_overrides_index_files\u0028\u0029",
            "name": "test_main_php_overrides_index_files",
            "summary": "",
            "url": "classes/MainResolutionTest.html#method_test_main_php_overrides_index_files"
        },                {
            "fqsen": "\\RenderScriptsForCrumbTest",
            "name": "RenderScriptsForCrumbTest",
            "summary": "Tests\u0020for\u0020scripts_for_crumb",
            "url": "classes/RenderScriptsForCrumbTest.html"
        },                {
            "fqsen": "\\RenderScriptsForCrumbTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/RenderScriptsForCrumbTest.html#method_setUp"
        },                {
            "fqsen": "\\RenderScriptsForCrumbTest\u003A\u003Atest_returns_empty_when_no_file\u0028\u0029",
            "name": "test_returns_empty_when_no_file",
            "summary": "",
            "url": "classes/RenderScriptsForCrumbTest.html#method_test_returns_empty_when_no_file"
        },                {
            "fqsen": "\\RenderScriptsForCrumbTest\u003A\u003Atest_returns_script_tag_for_existing_file\u0028\u0029",
            "name": "test_returns_script_tag_for_existing_file",
            "summary": "",
            "url": "classes/RenderScriptsForCrumbTest.html#method_test_returns_script_tag_for_existing_file"
        },                {
            "fqsen": "\\RenderStylesForCrumbTest",
            "name": "RenderStylesForCrumbTest",
            "summary": "Tests\u0020for\u0020styles_for_crumb",
            "url": "classes/RenderStylesForCrumbTest.html"
        },                {
            "fqsen": "\\RenderStylesForCrumbTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/RenderStylesForCrumbTest.html#method_setUp"
        },                {
            "fqsen": "\\RenderStylesForCrumbTest\u003A\u003Atest_returns_empty_when_no_file\u0028\u0029",
            "name": "test_returns_empty_when_no_file",
            "summary": "",
            "url": "classes/RenderStylesForCrumbTest.html#method_test_returns_empty_when_no_file"
        },                {
            "fqsen": "\\RenderStylesForCrumbTest\u003A\u003Atest_returns_link_tags_for_existing_file\u0028\u0029",
            "name": "test_returns_link_tags_for_existing_file",
            "summary": "",
            "url": "classes/RenderStylesForCrumbTest.html#method_test_returns_link_tags_for_existing_file"
        },                {
            "fqsen": "\\TitleResolutionTest",
            "name": "TitleResolutionTest",
            "summary": "Tests\u0020for\u0020title_resolution",
            "url": "classes/TitleResolutionTest.html"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_query_string_wins\u0028\u0029",
            "name": "test_query_string_wins",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_query_string_wins"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_meta_used_when_no_query\u0028\u0029",
            "name": "test_meta_used_when_no_query",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_meta_used_when_no_query"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_segments_used_when_no_meta\u0028\u0029",
            "name": "test_segments_used_when_no_meta",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_segments_used_when_no_meta"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_domain_used_when_no_segments\u0028\u0029",
            "name": "test_domain_used_when_no_segments",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_domain_used_when_no_segments"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_untitled_fallback\u0028\u0029",
            "name": "test_untitled_fallback",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_untitled_fallback"
        },                {
            "fqsen": "\\TitleResolutionTest\u003A\u003Atest_tagline_suffix_is_appended\u0028\u0029",
            "name": "test_tagline_suffix_is_appended",
            "summary": "",
            "url": "classes/TitleResolutionTest.html#method_test_tagline_suffix_is_appended"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot",
            "name": "TestCaseWithTmpRoot",
            "summary": "Extends\u0020PHPUnit\u0027s\u0020TestCase\u0020to\u0020set\u0020up\u0020a\u0020temporary\u0020root\u0020directory\u0020for\u0020testing",
            "url": "classes/TestCaseWithTmpRoot.html"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/TestCaseWithTmpRoot.html#method_setUp"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003AtearDown\u0028\u0029",
            "name": "tearDown",
            "summary": "",
            "url": "classes/TestCaseWithTmpRoot.html#method_tearDown"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003AcreateTmpFile\u0028\u0029",
            "name": "createTmpFile",
            "summary": "Creates\u0020a\u0020file\u0020under\u0020tmpRoot,\u0020creating\u0020intermediate\u0020directories\u0020as\u0020needed.",
            "url": "classes/TestCaseWithTmpRoot.html#method_createTmpFile"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003AcreateTmpImage\u0028\u0029",
            "name": "createTmpImage",
            "summary": "Creates\u0020a\u0020minimal\u0020PNG\u0020image\u0020file\u0020under\u0020tmpRoot,\u0020creating\u0020intermediate\u0020directories\u0020as\u0020needed.",
            "url": "classes/TestCaseWithTmpRoot.html#method_createTmpImage"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003A\u0024originalGlobals",
            "name": "originalGlobals",
            "summary": "",
            "url": "classes/TestCaseWithTmpRoot.html#property_originalGlobals"
        },                {
            "fqsen": "\\TestCaseWithTmpRoot\u003A\u003A\u0024tmpRoot",
            "name": "tmpRoot",
            "summary": "",
            "url": "classes/TestCaseWithTmpRoot.html#property_tmpRoot"
        },                {
            "fqsen": "\\RenderGalleryTest",
            "name": "RenderGalleryTest",
            "summary": "Tests\u0020for\u0020render_gallery",
            "url": "classes/RenderGalleryTest.html"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_setUp"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_returns_gallery_container\u0028\u0029",
            "name": "test_returns_gallery_container",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_returns_gallery_container"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_renders_one_item_per_image\u0028\u0029",
            "name": "test_renders_one_item_per_image",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_renders_one_item_per_image"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_item_ids_use_array_index\u0028\u0029",
            "name": "test_item_ids_use_array_index",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_item_ids_use_array_index"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_renders_title_and_description\u0028\u0029",
            "name": "test_renders_title_and_description",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_renders_title_and_description"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_renders_image_src\u0028\u0029",
            "name": "test_renders_image_src",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_renders_image_src"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_renders_more_link_only_when_present\u0028\u0029",
            "name": "test_renders_more_link_only_when_present",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_renders_more_link_only_when_present"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_always_renders_cover_link\u0028\u0029",
            "name": "test_always_renders_cover_link",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_always_renders_cover_link"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003Atest_empty_images_renders_empty_gallery\u0028\u0029",
            "name": "test_empty_images_renders_empty_gallery",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#method_test_empty_images_renders_empty_gallery"
        },                {
            "fqsen": "\\RenderGalleryTest\u003A\u003A\u0024images",
            "name": "images",
            "summary": "",
            "url": "classes/RenderGalleryTest.html#property_images"
        },                {
            "fqsen": "\\TestLightbox",
            "name": "TestLightbox",
            "summary": "Tests\u0020for\u0020lightbox",
            "url": "classes/TestLightbox.html"
        },                {
            "fqsen": "\\TestLightbox\u003A\u003ArenderLightbox\u0028\u0029",
            "name": "renderLightbox",
            "summary": "",
            "url": "classes/TestLightbox.html#method_renderLightbox"
        },                {
            "fqsen": "\\TestLightbox\u003A\u003Atest_middle_image_prev_and_next\u0028\u0029",
            "name": "test_middle_image_prev_and_next",
            "summary": "",
            "url": "classes/TestLightbox.html#method_test_middle_image_prev_and_next"
        },                {
            "fqsen": "\\TestLightbox\u003A\u003Atest_wraparound_prev_from_first\u0028\u0029",
            "name": "test_wraparound_prev_from_first",
            "summary": "",
            "url": "classes/TestLightbox.html#method_test_wraparound_prev_from_first"
        },                {
            "fqsen": "\\TestLightbox\u003A\u003Atest_no_images_renders_without_navigation\u0028\u0029",
            "name": "test_no_images_renders_without_navigation",
            "summary": "",
            "url": "classes/TestLightbox.html#method_test_no_images_renders_without_navigation"
        },                {
            "fqsen": "\\TestLightbox\u003A\u003Atest_imagepath_falls_back_to_media_directory\u0028\u0029",
            "name": "test_imagepath_falls_back_to_media_directory",
            "summary": "",
            "url": "classes/TestLightbox.html#method_test_imagepath_falls_back_to_media_directory"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
