<section>
	
	<h2>Moebius: A Movie About Itself</h2>

	<p class="description">An outline of a script for a film like this one.</p>

	<p>The film opens with a handheld camera shot of a neurotic writer and hotshot director getting out of a limo and walking down the red carpet to see the premier of their new film, "Moebius: A Movie About Itself" (this movie), at the historic Chinese Theater in Hollywood. They answer some questions about it to (real) entertainment news reporters (playing themselves) on the carpet, and we get a feel for each of the duo's characters and their dynamic before they go inside to watch the premier. </p>
	<p>Inside the theater they occasionally talk in hushed tones through the trailers and the first few scenes of the movie, including this scene, reminiscing on what it took to get this far, foreshadowing things that have yet to happen in the film. Time in this scene elapses faster than the actual time the movie thus far has taken, and as events in the movie-within-a-movie catch up to the present in the movie, the director apparently breaks the fourth wall and directs the cameraman (who is there in the theater with them, and apologizes nervously) to focus not on them, but on the movie screen instead.</p>
	<p>As the camera centers on the screen, we see the "hallway" effect of the screen framing an image of the screen framing an image of the screen framing an image of ... the screen framing an image of itself, recursively. As the camera zooms in to maximize the screen within its own image frame, the recursive frames converge, and as they match perfectly, the image, naturally, goes black.</p>
	<hr />
	<p>As the next scene begins, over the black, the writer's voiceover is heard saying "A Movie About Itself", and the image illuminates to show the writer and director having lunch together somewhere at a Hollywood cafe. The director asks "What?", and the writer begins to describe the concept of a movie whose plot is nothing more than the story of its own production, over the director's incredulous reception of the idea. Within this conversation is a description of how this conversation itself will be a scene in the movie, "the first scene, well maybe some kind of foreshadowing epilogue thing first and then we cut to this scene...".</p>
	<p>The writer (played e.g. by Edward Norton) describes how people will see, in this scene, themselves having this conversation about how people will see them having this conversation... etc, "Except it won't be US, you know, the audience won't see actual ME sitting here reading these lines, they'll see like, Brad Pitt..." -- the director (played e.g. by Brad Pitt) interrupts, "Or Edward Norton" -- "What? God no, I'm not having Edward Norton play me. You can have Edward Norton play yourself" -- "Nah man, I'm Brad Pitt. You're Edward Norton." -- "Whatever. The point is, the audience will see those actors sitting here reading a dramatization of this conversation, and not actually us." The director replies, "So the audience will see those actors saying that the audience is going to see themselves instead of... themselves? And... saying this line that I'm saying about that, right now?". The writer concedes, "Yeah, or, you know, a dramatization thereof, I mean I'm not transcribing this right now or anything."</p>
	<p>The director is eventually sold on the idea and goes in on it. The writer goes home and writes a draft of those two scenes, and then realizes that there's nothing more that they can write, because he doesn't know where the plot goes next because it hasn't happened yet. He realizes that they've got to pitch the movie with a barely-begun script before they can write any more, because the script of the movie is about the making of the movie. So they go to try to pitch it to a studio, without much of a script yet, telling the studio that this pitch they're giving right now will be a scene in the movie, the next scene that they haven't written yet, or part of a montage of such scenes at least, if they end up having to pitch it to a bunch of different studios.</p>
	<p>That first studio rejects them, and we're treated to a montage of the writer and director trying unsuccessfully to pitch their incomplete script to a bunch of different studios, finally getting success at one (whichever one actually produces this movie), who agrees to it on the condition that working with them is depicted in a positive light in the movie... and some important executive in the studio (played by himself) wants to play himself in this scene in the movie. Thereafter, people saying superfluously superlative things about the studio they're working for becomes a running gag throughout the rest of the film.</p>
	<p>Next they go through casting, and have to deal with how they are going to show themselves picking the people who are going to play themselves when the people playing them will need to play both them and themselves. They consider having themselves play the actors who are in turn playing themselves, just for these scenes, but decide against that as nobody would recognize them as themselves and so nobody would get the joke.</p>
	<p>However, in the following scene, the actual writer and director of this movie do play other random actors applying for the position, who get turned away for having absolutely no resemblance to the writer and director. As they are dismissed, the actor played by the writer comments that he is not actually a real actor anyways, he just played one in a movie once... and it was only one short scene anyway, more of a walk-on role. Those characters are never seen again.</p>
	<p>Instead, the writer and director favor having the actors who are playing them play both themselves and... themselves -- both the actors and the writer and director -- "via CGI or blue screen or something" as the writer puts it. So we see e.g. Brad Pitt as the director eventually hiring Brad Pitt (as himself) to play himself. Some comments are made about the close resemblance and good visual match, as the actor (as the director) closely examines his own face (as himself) via CGI or blue screen or something.</p>
	<p>Now that they have the world's most awesome studio backing them and an all-star cast who looks just like them, they set about filming the scenes that have already happened thus far in the movie. This is depicted in a montage of actual behind-the-scenes footage of the filming of this actual movie, spliced with recreated shots with the actors who play the writer and director, as the actual writer and director in the actual behind-the-scenes footage cannot be featured, of course. The montage finishes with a montage version of itself containing a montage version of itself and so forth eventually blurring into an indiscernable smear of video of video of video of video, marking the center of the film.</p>
	<hr />
	<p>In the next scene, filmed again with a handheld camera and from some distance on the edge of the set like behind-the-scenes footage, we see wrap-up of filming of the last scene before the montage. After the cast and crew are dismissed, the writer walks up to the director in his chair, and says "Great! So now, when we get to post-production we just insert a montage right here of behind-the-scenes footage, including a montage of the montage itself and so on and so forth until..." He is interrupted by the director, who looks dour and states "We have a problem."</p>
	<p>"What problem?" asks the writer. "The problem of how do we film the filming of the scene that we are filming the filming of?" replies the director. The writer isn't sure he understands, and the director explains that they have now completed filming of everything that has already happened, and the next scene to film, after the montage they'll insert in post, is the present, the one that's happening right now. "What", he asks, growing angry, "do we use behind-the-scenes footage of this conversation, and then have..." he waves at the distant camera, and the cameraman approaches them, whereupon the director asks his name (let us say it's 'Charles') "...do we have Charles here fucking film himself filming himself filming himself and on and on and on like that? What, do we put him between two fucking mirrors or something? And then what?" The cameraman speaks nervously from behind the camera, "I uh, I'm not supposed to be a character in this film, I'm just documenting production for the studio." The writer comments something in high praise of the studio, and gently informs the cameraman that like it or not he is a character in the film now, but so long as he hangs on to that camera he doesn't actually have to appear on screen. The cameraman shyly concedes to that.</p>
	<p>The producer suddenly realizes something even worse, and shouts "Post!" as if it were an expletive. Over the writer's confused look, the director continues "How the fuck are we supposed to film the post-production of the film which will be post-produced, before we've even filmed it to send it to post?" The writer begins to reply timidly, "Uh, I dunno...", and the director shouts at him "Well you're the fucking writer! Fucking... write your way out of this mess you wrote us into! We can't just end the movie here! What about the prologue, epilogue, foreshadowy shit at the start, at the premier? We break the whole setup of that if we don't have something between principal and release, and that something is post!" The writer looks despondent, and resignedly says "Well, I guess I'll just have to make something up. I mean, it's either that or we invent time travel!" he laughs.</p>
	<p>A look of revelation comes over both their faces, and they look directly into the camera as though they just got an idea and they want the audience to realize what it is too. The cameraman asks, as they stare, "What? Do I... is there something on the lens or something?"</p>
	<p>We cut to the next scene, where Stephen Hawking (playing himself) replies in his signature artificial voice with an incredulous flat "What." The writer, director beside him, explains again to Hawking about their predicament and why they need him to invent a means of time travel for them so that they can find out about the postproduction of their film, so they can film a dramatization of it to send for postproduction. Hawking explains, in his own words that he can ad-lib here, both why time travel is impossible and why their idea is ridiculous and stupid, and also asks how did they manage to get an interview with him under these pretenses anyway. The writer stammers that he's not actually sure, he didn't think to write those scenes, they just cut straight from the revelation to here.</p>
	<p>Hawking throws them out, with a comically musclebound bodyguard physically expelling them outside the gates of his mansion (regardless of whether Hawking really has a mansion or not, never mind that this would all take place in Britain anyway), whereupon dogs are released to keep them out.</p>
	<p>Next we see a montage of other famous living physicists that might be recognizable to an intelligent audience, like Neil Degrasse Tyson, telling them time travel is impossible and their idea is stupid and to go away. Eventually they end up asking Bill Nye ("the Science Guy"), who informs them that he's not even a physicist at all, he's just a mechanical engineer... and even he knows that time travel is impossible and their idea is stupid and go away.</p>
	<p>Back at the director's house, they are disheartened, and the writer laments that he's just going to have to make up something crazy for their ending, "unless the secrets to time travel magically show up in the mail!" At that moment, a courier arrives with an express delivery package from their studio. Suspicious, they sign for it and open it, and inside it is a device with three date and time displays in red, yellow, and green, reminiscent of the DeLorean's displays from "Back to the Future"; small buttons to change the date of the green display; a single large translucent button inside of which is what looks like the three-pronged shape of a Flux Capacitor; and three spoke-like handles protruding from the whole device. Though incredulous, they realize that somehow their studio has procured for them a time machine, and figuratively sing their praises. (Bonus gag if this film is produced by Universal, who of course have a time machine already, in the DeLorean).</p>
	<p>Thrilled, the director takes out his camera phone and snaps a shot of himself and the writer posing with their new time machine. They then take a wild guess at how long they think it will take them to complete post-production, program those dates into their device, and jump into the future. Not finding either of themselves there to ask their questions about their postproduction process, they try calling themselves, and each other, but the calls just go to voicemail, which they attribute to time travel shenanigans. They set out toward their studio in the director's car (which he wonders why it is still there if he is gone somewhere), to see if they can find themselves there or at least find out something about the future of their movie. But on the way, they drive past a billboard announcing the premier of their movie today at the historic Chinese Theater in Hollywood.</p>
	<p>The director wonders how they hell they went from principal to release this quickly, there's no way they completed post and marketing and distribution all in so little time. The writer realizes that if they are this far in the future, they can get not only the information on how to end their film, but they can get the actual film itself and save tons of time and money on postproduction by just bringing the finished film back from the future! And that that must be what they have done, or are about to do, since it's the only explanation for how there's a release this soon.</p>
	<p>They drive to the Chinese Theater, but upon arrival at the premier are not let in, as they have already been let in, and are suspected of being imposters. They run from the bouncers down into an alleyway, and the director says "Well great! Now how are we supposed to... fulfill our destiny, or whatever. If we don't get that film, do we disappear in some kind of paradox like Marty McFly because the movie never gets made and so the premier is never here for us to steal it from? And if I see myself in there, does the universe explode or something? How does this time travel shit work?"</p>
	<p>The writer, programming some numbers into the time machine, says "Relax, I got this." The director asks "Where are we..." -- only to be corrected, "when" -- "...when are we going, er, now?" The writer replies "This morning, before we got here. To take a look at the projection room." The director looks at him funny, then takes hold of one of the spokes as they disappear. The camera doesn't move, but the lighting in the alley set cuts from evening to morning, as a bum wanders the alley, and the duo appear in the same pose, holding the time machine, frightening the bum into a panicked run.</p>
	<p>The writer programs another date into the time machine, then puts it in is pocket, as far as it will fit at least. They compose themselves, check their hair and so on, and then walk calmly out of the alley back to the Chinese Theater, the writer leading, uncharacteristically calm and confident. They introduce themselves, and make sure that the manager there recognizes them and knows who they are. They say they would like to take a quick look at the projection room before their premier this evening. The manager assures them that everything is in top condition, but concedes to show them around.</p>
	<p>As he shows them the projection room, the writer acts as though the time machine has caught his attention somehow, pulls it out of his pocket, looks concerned at its screen, and asks the theater manager, "Would you mind leaving us for a moment? I've got to take this in private". The manager, though confused, excuses himself to let the writer take his "phone call". Once he is gone, the writer quickly offers the other spoke of it to the director, mashes the engage button, and the two vanish.</p>
	<p>The lighting changes to that evening during the premier. The duo reappears, scaring the bejezus out of the projector operator, who runs screaming from the room. The writer tells the director to grab the film reels quickly, while he reprograms the time machine again. As both do their duty, visible in the background through the projector window are the opening shots of their movie, as seen in the first scene. Right as the "hallway" effect of frames zooming into frames zooming into frames, etc, culminates, as the frames converge and the screen goes black, right then the director unplugs the projector, and takes the currently playing reel off of it. The projector operator runs back into the room with the theater manager in tow, and points alarmedly at the duo, right as the writer finishes reprogramming the time machine, offers a spoke of it to the director, and mashes the engage button.</p>
	<p>They vanish, the lighting changes back to earlier that morning, and they reappear. They leave the projection room, the writer putting his "phone" back in his pocket, and thank the theater manager for the tour but they have to run now, urgent last minute business, and they're sure the rest of the theater is fine. The manager is confused about why the director is now carrying film reels when he didn't enter with them, but the director insists that he did enter with them, and demonstrates that they are, in fact, the reels of his own film. The manager, though confused and suspicious, lets them leave when the writer insists that they really are in a hurry and need to take care of some things before tonight.</p>
	<p>They run back to the alley, reprogram the time machine again to take them back to the moment they left premier night. As they make their way back to car, a commotion is visible outside the theater behind them, and security comes running after them. The director comments that this is an awfully disproportionate response to a couple of imposters trying to bluff their way into a premier! But they get to the car in plenty of time and drive off, laughing and excited at accomplishing their caper. They arrive back at the director's house, and the writer realizes that they no longer have the precise coordinates of the moment they left, since the device only shows the last time departed, the present time, and the destination time. He's afraid of "crossing our own time streams, or something", and doesn't want to go back to the wrong time and risk that.</p>
	<p>The director relieves him, however, by pointing out that he has a photo showing the time machine and its then-present time, which is thus moments before their time of departure. They program the machine for five minutes after that, and jump back to their present. They are excited and thrilled at the idea that they don't even have to go through postproduction, that they have a completed film here and just have to turn it over to the studio for marketing and distribution! </p>
	<p>Suddenly, they are congratulated in a sinister tone by other versions of themselves, hiding around the corner in a hallway. The director exclaims "Oh shit! We crossed the streams after all!" The other-writer makes some sinister-sounding remarks affirming the danger of doing so, something about how they must touch now and mutually annihilate to prevent the universe-threatening paradox that looms in their future due to this unholy violation of causality! As the duo are frightened by this foreboding doom, the other-writer suddenly lightens in tone and says "Nah I'm just shitting you, I'm just you from a few hours from now... ago... whatever."</p>
	<p>The other-duo explain to this duo that they must now travel back in time to earlier that day in order to complete the causal loop and prevent a real paradox, "No seriously I'm not shitting you this time", as the time machine was actually sent to themselves from themselves, using the wonderfully cooperative studio's mailroom as cover. But, the other-writer emphasizes, they must go back in time to the exact time that they (the other-duo) went back to, or else they will break the causal loop and cause a real serious no-shit universe-destroying paradox of doom. The writer asks the other-writer how did he become such an expect on temporal mechanics in just a few hours, and the other writer replies "You... er, I... told, uh, myself, that is, you, in the future, just now, earlier, er, how it all works..."</p>
	<p>The director interrupts the stammering to point out that they have no way of knowing the exact time that the other duo arrived in the past. The other-director pulls his phone out of his pocket and waves it meaningfully; the director pulls his own phone out of his pocket, still with the picture of the time machine up, and realizes that the destination date showing on it when they received it would be the time it had arrived in that timeline, and thus the time they had to go to now.</p>
	<p>The writer begins punching those numbers into the time machine, as the director waves goodbye. "Bye us! See you... er, you'll see us... when we're you... now... but, later..." The writer cuts him off by shoving the time machine into his hands and jamming the engage button.</p>
	<p>The two arrive earlier that day, while their earlier selves were still out getting rejected by Bill Nye the Science Guy. They run to the driveway, and as the director insists as usual that they take his car, they realize their earlier selves are out in it now, and they'll have to take the writer's car... and be back before their other selves get back, since it was already here and they were apparently hiding in the house when they got in earlier... er, later that day.</p>
	<p>A few quick establishing shots later and we're at the studio, as they thank the wonderfully cooperative mailroom staff for obliging them this weird request to ship something same-day express delivery to themselves in company packaging. As they leave the mailroom, the writer comments on how they've got to get back quickly in time for him to freak their earlier selves out.</p>
	<hr />
	<p>The next scene opens with a handheld camera shot of the writer and director getting out of a limo and walking down the red carpet to see the premier of their film at the historic Chinese Theater in Hollywood. They answer some questions about it to entertainment news reporters on the carpet, before they go inside to watch the premier. </p>
	<p>Inside the theater they occasionally talk in hushed tones through the trailers and the first few scenes of the movie, reminiscing on what it took to get this far. As events in the movie-within-a-movie catch up to the present in the movie (again), the director apparently breaks the fourth wall and directs the cameraman (who is there in the theater with them, and apologizes nervously) to focus not on them, but on the movie screen instead.</p>
	<p>As the camera centers on the screen, we see the "hallway" effect of the screen framing an image of the screen framing an image of the screen framing an image of ... the screen framing an image of itself, recursively. As the camera zooms in to maximize the screen within its own image frame, the recursive frames converge, and as they match perfectly, the image, naturally, goes black.</p>
	<p>Everyone in the audience sighs because someone has just cut the projector, and we hear the director shout "oh goddamnit" as he realizes what they've just done.</p>

</section>