<section>
	
	<h2>How <i>Stargate Atlantis</i> Should Have Gone</h2>

	<p class="description">An earlier ending for <i>Stargate SG-1</i> leading into a merger of canon <i>Stargate Atlantis</i> with the later seasons of <i>SG-1</i> plus some original material.</p>

	<section>
		<h3>SG1 Alterations</h3>
		<p>The events of canon SG1 S5:"Meanace" do not happen, leaving the Replicators of unknown origin. The events of SG1 S6:"Unnatural Selection" are instead replaced with a plot to summon the Replicators to one place with the promise of access to an Ancient Repository of Knowledge (requiring a human with the ATA gene, e.g. O'Neill, to prime it, hence SG1's involvement); and then trapping them in the time dilation field, with no human-form Replicators yet to be seen.</p>
		
		<hr />

		<p>Jonas Quinn's role as "the new Daniel" in S6 is greatly downplayed, and ascended Daniel makes many more cameos. Jonas is never listed as main cast, and Daniel is never delisted as such, providing for a much less jarring departure/return of Daniel's character and introduction/departure of Jonas's. But after the events of SG1 S7:"Fallout", Jonas returns to the SGC, though not SG1, and remains a supporting or recurring character for the remainder of the season.</p>

		<hr />

		<p>While Anubis is busy attacking Earth in SG1 S7:"Lost City", the Jaffa rebellion takes off earlier than in canon, and lead by Teal'c they move to capture Dakara (instead of in canon SG1 S8:"Reckoning"). They succeed.</p>
		<p>The Tok'ra simultaneously stage uprisings against the remaining System Lords, which are less successful. Jacob/Selmak, already on their last legs, are overextended by this effort, and die at the end of this season (instead of in canon SG1 S8:"Threads"). But the Tok'ra have a memory-transfer technology that can give one person another person's complete memories. It is usually fatal to the memory donor (used only for extracting information from enemies), but since Jacon/Selmak are dying anyway, they use it... to give their entire memories to Sam.</p>
		<p>Daniel receives the Ancient repository of knowledge (instead of Jack as in canon), and after defeating Anubis, instead of going into stasis (as Jack does in canon), he is overwhelmed by the knowledge and dies... but in the process unlocks his memories of ascension, and ascends himself again.</p>
		<p>The outpost in Antarctica is Atlantis (unlike in canon), submerged beneath the Ross Ice Shelf, and Weir is brought in not to replace Hammond (as in canon), but as IOA civilian oversight of the relocated, internationalized SGC there. Hammond is promoted to head of the new department of Homeworld Security at the United Nations, and Jack is promoted to Hammond's old position as military head of the new SGC.</p>
	</section>
	
	<section>
		<h3>Alt-SGA Season 1</h3>
		<p>Cameron Mitchell, leader of the F-302 squadron which defended SG1 during S7:"Lost City", is brought in to his new assignment on SG1, but finds the old team disbanded (as in canon SG1 S9:"Avalon"). Sam is now permanent liaison to the Tok'ra like her father before her, Teal'c is a leader amongst the new Jaffa High Council on Dakara, and Daniel has not been heard from since his ascension. Cam is tasked with selecting a new SG1 for himself to lead, a task which he is not happy with. He travels through the gate to visit Sam and Teal'c on their new worlds and convince them to rejoin SG1, but they value their new positions and the important alliance being built between the Tau'ri, Tok'ra, and Jaffa, too much to abandon them. Cam is heartbroken that the team he came to join is gone forever, but all else failing, he selects Jonas to be the first member of his new SG1, as he is the only previous member of SG1 available.</p>
		<p>But soon thereafter, the Stargate at Atlantis activates, and Chaka of the Unas walks through, followed shortly by Daniel Jackson! According to Chaka, who has learned to speak broken English, while ascended Daniel has been teaching and "uplifting" the Unas, who are apparently of lesser concern to the ascended Ancients than humans are. However, for reasons he himself does not yet know, Daniel has apparently descended again into human form, with little memory of anything since his ascension. He has brought Chaka here to serve as liaison between the Unas and the Tau'ri, for the Unas to join the burgeoning alliance against the Goa'uld, and requests Jack to give him a place on an SG team. Jack suggests that Cam's crew "could use a burly alien warrior guy", lampshading Chaka's role as the new Teal'c; and adds "you've already got a nerd", eliciting a sheepish grin from Jonas and a mildly scolding glare from Daniel.</p>
		<p>Cam agrees to accept Chaka to his team, and pleads for Daniel to join as well; but Daniel is hesitant, stating that he thinks his place is still amongst the Unas, as he has so much more to learn about their history and the early history of the galaxy. He says, for example, that the Unas have myths of human-like gods from before the rise of the Goa'uld, and he believes this means that the Ancients may have had contact with the prehistoric Unas, and that may have something to do with why they do not enforce their policy of non-interference over them. Chaka adds that they still have much to learn from Daniel as well, and makes a gesture of reverence toward him.</p>
		
		<hr />

		<p>But more importantly than just introducing Chaka to SG1, and more urgently, Daniel has come suggesting an expedition. Apparently while ascended he had Chaka memorize an eight-symbol Stargate address, and told him that on that world they would find Taonas, the Ancient city-ship which once resided on the planet Proclarush, which they visited last year seeking the ZPM needed to bring Atlantis' systems online against Anubis. Taonas fled the Milky Way during the plague which destroyed the Ancients, and so should hopefully still have live, unascended Ancients living there.</p>
		<p>However, the ZPM from Proclarush is now too depleted after the battle with Anubis to dial intergalactically; and Atlantis' own ZPM is barely able to keep Atlantis' shield operational under the sea, so to dial out would flood the city. So instead they contact the Asgard, to ask for their assistance in getting there.</p>
		<p>They find to their surprise that the Asgard now have much more humanoid bodies, thanks to research conducted on the old clones recovered from stasis in canon SG1 S5:"Revelations". Reintroducing themselves to Thor in his new body, a slightly awkward conversation occurs where Thor finally corrects a long-standing mistake: their species is not called "the Asgard"; rather, "Asgard" is the name of their home; when he first introduced himself as "High Commander of the Asgard Fleet", it was akin to if a human had called himself "High Commander of the Earth Fleet", and the Tau'ri's persistence in calling his species "Asgards" is akin to if Thor referred to humans as "Earths". When asked what he should be called then, Thor replies "I am an Aes", pronounced like "ass", prompting an awkward silence, before Thor continues, "My people are the Aesir. Our home is Asgard."</p>
		<p>Back on to business, Thor reveals that the Replicators have not only escaped, but have developed into humanoid forms (similar to canon SG1 S6:"Unnatural Selection" and S8:"New Order"), and so they, the Aesir, are too busy fighting their own battles to help the Tau'ri right now. The production of ZPMs is very expensive and their entire industry is dedicated to combatting the Replicator threat, but they suggest that in exchange for the Tau'ri's assistance, they may be able to help.</p>
		<p>The Aesir request the use of Prometheus, Earth's first deep-space battlecruiser, for a mission similar to canon SG1 S8:"Unnatural Selection". The ship and its crew are commanded by General Landry, and towed by Thor to the Aesir's home galaxy of Ida (not having moved to the Othala galaxy as in canon). There they help the Aesir win a battle, but not the war, against the Replicator threat. Thereafter, Prometheus is returned to Earth, but arrangements are made for the team to be permanantly stationed in Ida to collaborate with the Aesir, with the promise of shared technology such as ZPMs as we prove ourselves worthy of it.</p>
		
		<hr />

		<p>Back on task with the mission to Taonas, SG1 (still having no ZPM) reason that since the Aesir were able to whisk Prometheus between the Milky Way and Ida so easily, perhaps they would be willing to send it to the new location of Taonas, which as it turns out resides in the Pegasus galaxy. But the Aesir are hesitant and evasive on the subject, and vaguely advise against contact with the Pegasus galaxy, but will not speak more on the matter. Undeterred, but frustrated, SG1 take Prometheus, at its own slow hyperspeed, without the assistance of the Aesir. But en route, Vala Mal Doran tries to capture the ship, as in canon SG1 S8:"Prometheus Unbound"; however, unlike canon, she does not escape at the end. Prometheus returns to Earth with her as their prisoner.</p>
		<p>While in custody at the SGC, she offers intel about the "Clava Thessara Infinitus", the Ancient repository at Glastonbury Tor (as in canon SG1 S9:"Avalon"), with the hook for the Tau'ri being that it supposedly contains a ZPM. Vala joins herself to Cam (rather than Daniel as in canon), and thereby becomes an unofficial fourth team member. The mission to Glastonbury is a go anyway, and on it Vala proves herself remarkably competent with science and technology, a skill belied by her affectations and personality, to which Jonas remarks that "I guess we have our science gal", eliciting naive confusion on the part of Vala and a roll of the eyes from Cam.</p>
		<p>Unlike canon, the mission to Glastonbury does not result in contact with the Ori, although records of the Ancients' distant origins and flight from a powerful do enemy foreshadow later events. In the end, the ZPM there is recovered as Vala promised, and Atlantis comes alive again.</p>

		<hr />

 		<p>Because Cam is bound to Vala, SG1 is not a part of the Pegasus Expedition: instead Shepperd and his team are sent. Upon arrival in Taonas, which appears abandoned, they test dial back to Earth, and in the process accidentally force the city to surface by depleting its very old ZPM with the intergalactic connection, leaving them unexpectedly unable to dial home thenceforth. Dialing out to other worlds in hope of a solution, they encounter Ronon Dex (much earlier than in canon), and awaken the Wraith early (as in canon SGA S1:"Rising"). Upon returning to Taonas, they are accosted by the seemingly-primitive mainland natives (in lieu of the canon Athosians), who reveal themselves to be the Furlings (or "Far-lings"), the offshoot of the Ancients who originally fled to Pegasus in Taonas. Though evolutionarily advanced with mild psychic abilities (similar to Teyla's abilities in canon), they now live voluntarily primitive lives, keeping their city-ship submerged to avoid attracting the Wraith, and retreating into it during cullings. They are thus very unhappy at the Expedition's arrival; but simultaneously thrilled to discover that human life has survived or re-evolved in the Milky Way.</p>
		<p>Realizing that the Expedition are not the Ancients themselves and thus know little of their history, the Furlings explain the Wraith. Though they had made themselves immune to the plague, the Furlings still carried it with them as they migrated to Pegasus. There, as they settled new worlds across that galaxy, the plague bacterium evolved at an unnatural rate into a blight which ravaged the ecosystems of their new worlds. Becoming masters of biotechnology, the Furlings engineered blight-resistant crops, and stalled their downfall again; but the microscopic blight evolved still further into a macroscopic pestilence known in the Ancient tongue as "Iratus". This pestilence devoured plant and animal alike, and no simple genetic immunity to it could be devised, and it adapted quickly to their counter-bioweapons. But still the Furlings were vigilant, driving off or containing the pestilence, moving on to new worlds, and continuing to build their civilization across the Pegasus galaxy.</p>
		<p>But the Iratus pest evolved still further, into parasitic creatures which somehow fed on an energy created only by sapient beings, and so hunted the Furlings specifically. After these creatures broke containment, the Furlings created a retroviral gene treatment which inserted some of the Iratus DNA into their own DNA, so the pests would identify them as their own, and not attack them (just as they did not feed on each other for their own stores of life-energy), allowing the Furlings to go forth and exterminate them. But this treatment backfired.</p>
		<p>Though at first it seemed to work as planned, and the treatment began to be widely administered, those treated with it very gradually lost all appetite, and any ability to derive nutrition from mere food. They developed grotesque abnormalities of the skin, hair, and eyes, and eventually developed a kind of pathological lust for... something about other people, which eventually manifested as the need, and ability, to drain the very life-energy of other sapient beings, just as the Iratus had. At first treated as a medical catastrophe, with those afflicted largely seeking treatment before it was too late, a few deranged individuals considered their affliction a form of evolution, and claiming themselves a superior race. They fought against any cure, and called those similarly afflicted to their side as the new masters of their civilization, casting the unaffected in the light of mere cattle for them to prey upon.</p>
		<p>Thus a civil war developed among the Furlings, between the unaffected and the new mutants they dubbed Wraiths. Being immune to the life-draining attacks of the Iratus and unperturbed by its continued ravishing of their crops (having no use for ordinary food), the Wraith quickly overran the already-weakened Furling civilization. Their cousins in the Alliance of Four were unable or unwilling to come to their aid; the Nox being too pacifist to wage a galactic war, the Ancients on Earth focusing all their energies on ascension, and the Aesir being occupied with the Replicators; on this last point the Furlings seem especially remorseful, but will not speak more. And so the Wraith assumed the mantle of all the Furling's biotechnological supremacy, and the civilization of the unaffected Furlings collapsed across the galaxy, in most places back to pre-industrial levels, living merely as cattle for the Wraith to feed upon. And as the Wraith feed on the life-energy of sapience, the same energy harnessed by the advancing evolution of the Furlings on the path toward ascension, they culled from their herd those with advanced abilities that frittered away such energy, leaving Furlings largely no more evolved than the humans of the Milky Way.</p>
		<p>Only in a few places, like here at Taonas, has any remnant of advanced Furling civilization survived, carefully hidden from the Wraith. And though the Tau'ri's arrival has severely jeopardized that survival strategy, they are at least nominally happy to have allies once again, however powerless the Tau'ri may be to help them, and they welcome the Expedition to their world, hoping soon to reestablish contact with Earth.</p>
		
		<hr />

		<p>Meanwhile on Earth, SG1 must deal with the sudden reappearance of Anubis (as in canon SG1 S8:"Lockdown"). As in canon, the disembodied spirit of Anubis possesses various members of the SGC, before being sent offworld in his last captured host, to an ice planet presumedly to freeze to death. But even that is not expected to stop him completely, and Sam and Teal'c are contacted to alert the Tok'ra and Jaffa that Anubis has returned.</p>
		
		<hr />

		<p>Thenceforth SGA involves an ensemble of three teams:</p>
		<ul>
			<li>One, aboard the Daedelus in the Ida galaxy (consisting primarily of bridge crew Col. Steven Caldwell, Lt. Kevin Marks, engineer Lindsey Novak, and the Aes Hermiod), help the Aesir against the Replicators, and have to cope with the emergence of human-form Replicators, including the entire Fifth-RepliCarter arc, similar to that of canon SG1 S8, but with the Asurans Oberoth and Niam from canon SGA merged in to the characters of First and Fifth respectively.</li>
			<li>Another, on Taonas in the Pegasus galaxy (consisting primarily of Sheppard, McKay, Ronon, and Teyla, who is a Furling unlike canon), help the Furlings against the Wraith, recapping pieces of canon SGA S1 and S2, particularly the retrovirus-Michael arc.</li>
			<li>And SG1, in the Milky Way, consisting of Cam, Jonas, Chaka, and Vala, lead a growing coalition of the Tau'ri (under Jack), Tok'ra (under Sam), Jaffa (under Teal'c), and Unas (under Daniel), against the remaining human, Jaffa, and Kull Warrior forces of the surviving System Lords, regrouping under Anubis' leadership. The internal strife between these vastly different factions is eventually ameliorated by mediation by the Nox (who, as seen in SG1 S1:"The Nox", have their own equivalent of a city-ship flying and cloaked on their homeworld, which we learn is an earlier version of Taonas and Atlantis, and becomes the neutral court of the growing Milky Way alliance).</li>
		</ul>
		<p>The season concludes with first a decisive victory against the Replicators in Ida, concurrent with the recovery of another ZPM via the events of canon SG1 S8:"Moebius". Now freed from the urgency of their mission in Ida, the Daedelus makes its way back to the Milky Way and then on to Pegasus to bring the new ZPM to Taonas to finally allow the Expedition to return home. But shortly after its arrival, events similar to canon SGA S1:"The Siege" occur...</p>
	</section>

	<section>
		<h3>Alt-SGA Season 2</h3>
		<p>Taonas is captured by Wraith forces lead by Michael, and with the arrival of the ZPM from Earth, Taonas can now dial intergalactically, allowing the Wraith to invade the Milky Way. Darts are sent through the Taonas gate, used to capture a few worlds in the Milky Way, and on those worlds Hive-Ships are grown, giving the Wraith the foothold they need in the Milky Way. Michael travels between Taonas and the Wraith foothold in the Milky Way regularly to oversee the invasion.</p>
		<p>A battle of three armies commences, as the remaining System Lords under Anubis and the new Tau'ri coalition continue to battle each other as well as the Wraith. As the Wraith make headway a very tenuous truce is formed between the System Lords and the Coalition, resulting in the Wraith invasion forces in the Milky Way being defeated. But the Goa'uld prove more interested in taking the Wraith as hosts and using them to bolster their own forces in the Milky Way, and betray the Tau'ri coalition as soon as the Wraith's lines are broken. Only Anubis himself manages to take a Wraith host, namely Michael, and uses the Wraith feeding abilities to regenerate that host. The rest of the Wraith in the Milky Way die fighting the Coalition and the Goa'uld, returning the galaxy to the status quo before their invasion.</p>

		<hr />

		<p>Meanwhile in Pegasus, the Expedition, displaced from Taonas and wandering the galaxy on the Daedelus, encounters other Furling colonies such as the Genii, Satedans, and Travellers, makes occasional enemies but eventual allies with them, and together finally recapture Taonas from the Wraith after Michael is defeated in the Milky Way. The intergalactic gate is secured, sealing off the Wraith from being able to invade the Milky Way galaxy again. With a working intergalactic gate in Taonas, two-way travel between all three galaxies is now possible (the Aesir and Atlantis already being able to dial out). The Pegasus Expedition returns to Earth and gets its supplies and membership replenished. The Furlings are ecstatic to re-establish contact with their long-lost allies from the Alliance of Four Races, the Aesir and the Nox, though the Aesir are not so ecstatic to be back in contact with the Furlings, about which the Furlings seem very remorseful. Nevertheless the reunion is civil, and words are whispered about the Tau'ri and their progress toward becoming the Fifth Race, taking the place of the lost Ancients.</p>
		<p>It is revealed in the reunion excitement between these ancient races that they are all related. It turns out that the Ancients are not from this galaxy to begin with, but from one called Orilla (which is not, as in canon, the Aesir's present homeworld), and that all three of these races were related to them. The Aesir are the cloning-mutated descendants of much earlier explorers from Orilla, who settled in the Ida galaxy long before the Ancients left Orilla. The Nox are the withdrawn descendants of what remained of the unascended Ancients in the Milky Way after the plague. And the Furlings, as we know, are Ancients who migrated from the Milky Way to the Pegasus galaxy and thus escaped the plague entirely.</p>
	</section>
	
	<section>
		<h3>Alt-SGA Season 3</h3>
		<p>Via infiltration by RepliCarter, the Replicators find out about Atlantis and, seeking it's advanced technology, invade the Milky Way.</p>
		<p>Unable to conquer Atlantis immediately, the Replicators build their forces in the Milky Way and try to conquer the rest of the galaxy first. The System Lords slowly fall to the Replicators. The Tau'ri coalition tries to mitigate the Replicators' spread and is forced to ally with the System Lords yet again.</p>

		<hr />

		<p>Meanwhile the Aesir take this opportunity to press back against the Replicators in Ida, taking advantage of their split attention. Many old Aesir worlds are taken back from the Replicators, and many Aesir minds are downloaded into new bodies for the first time in millenia. Though the war goes on, Aesir civilization is at last resurging once more, instead of slowly declining as it has done for ages.</p>

		<hr />

		<p>Simultaneously, the Furlings apologize greatly to the Tau'ri and the Aesir for all the trouble they are having with the Replicators, explaining to the Tau'ri that the Replicator threat is ultimately their fault to begin with. Their "cure" for the ancient plague, their way of becoming immune to it, had been in the form a nanovirus which automatically repaired any damage to their bodies which the plague inflicted. This was adapted to combat the blight which the plague evolved into, and adapted further still into self-replicating mechanical creatures in order to combat the Iratus bug. In response to the Wraith threat, the ancient Furlings reprogrammed these replicators into a purely artificial life form which was immune to the Wraith's biological attacks: the Asurans.</p>
		<p>The Asurans battled the Wraith for some time as Furling civilization continued to collapse amidst the carnage of the war. In time, the Wraith managed to hack the Asuran base code, stripping them of all intelligence and direction, leaving only mindless self-replicating technological blocks, which posed more of an annoyance than a threat to the biotechnology of the Wraith. Eventually, the Aesir arrived in Pegasus to aid their Furling cousins, but while they easily outmatched the Wraith in technological might, the replicator blocks proved a much greater threat to the technologically advanced Aesir. The Aesir were forced to retreat after losing several ships and their associated technology to the Replicators, which followed them in their retreat back to the Ida galaxy, leaving Pegasus dominated by the Wraith, and the Aesir mired in an ongoing war against an implacable enemy.</p>
		<p>Upon learning of this, Rodney McKay has the brilliant idea of reinstating the Asuran code into the network of the Replicators still active in Ida, restoring them to their previous, friendly disposition, and turning an enemy in Ida into an ally against the Wraith in Pegasus. While the Aesir and the Tau'ri Coalition hold off the Replicators' advances, McKay and the Furlings work on a more permanent solution, which the Wraith of course fight vigorously to prevent.</p>

		<hr />

		<p>The season ends with events similar to canon SG1 S8:"Reckoning": the remaining System Lords are defeated by the Replicators, leaving only Anubis, his underling Ba'al, and their Kull Warriors. The Replicators are eliminated from the Milky Way via the Dakara superweapon, but then Anubis and his forces begin to move to capture the weapon for their own use, now that the Jaffa there are weakened from their battle with the Replicators.</p>
		<p>Daniel is killed in the battle for Dakara, but ascends; apparently a failsafe he built into himself when he descended himself again. As in canon SG1 S8:"Threads", Daniel must call on Oma Desala's help to deal with Anubis, as the Others will not let him intervene; but rather than being locked in perpetual combat as in canon, Oma's perpetual vigilance drives Anubis into exile from our galaxy. Daniel is allowed to return to human form, again with no memory of his time while ascended; in fact no one is even aware that he had died, and he thinks he must have just lost consciousness somehow during the battle.</p>
		<p>Not knowing that Daniel is busy fighting to stop Anubis himself, the Tau'ri move to destroy the Dakara superweapon rather than let it fall into his hands. They succeed, and lose their trump card as the Aesir continue to battle the Replicators in Ida.</p>
	</section>
	
	<section>
		<h3>Alt-SGA Season 4</h3>
		<p>McKay's plan to reactivate the Asuran base code is implemented. While the Replicators are reminded that the Wraith exist, and are drawn to Pegasus to fight them, they retain also their own memory of animosity toward the humans and Aesir and by association the Furlings. But just like Atlantis in the Milky Way, Taonas, with a fully charged ZPM, is more than a match for the Replicators.</p>
		<p>A fraction of Wraith lead by Todd, having seen Taonas repel the Replicators as easily as Atlantis, turn to the Furlings and humans for help, consenting to the treatment which removes their need to feed on humans, in exchange for salvation from the Replicators. The Wraith help locate ZPMs sufficient to fully power Taonas, and with an armed and ready city-ship at their disposal, the Replicators in Pegasus are destroyed.</p>
		<p>Also in response to the Asuran base code, some of the Replicators still in Ida have their old allegiance to the Furlings (and by association the Humans and Aesir) reawakened, and a rebel faction forms under Niam/Fifth, which allies against their antagonistic brethren under Oberon/First. With the help of this rebel faction (which later comes to seek ascension, similar to the Asurans of canon SGA), the Aesir are finally saved from the war which has plagued them for ten thousand years.</p>
		<p>Victory appears to be at hand. The Goa'uld empire is broken and its freed peoples united with the Tau'ri, the Wraith and Replicators are turned to allies or else destroyed, and the last three of the Four Races are united once again. Peace across the three galaxies between the all of the nine species that inhabit them seems to be imminent: the Tau'ri, the uplifted Unas, the rebel Jaffa, the Tok'ra, even the converted Wraith and Replicators, all living together under the guidance of the Aesir, Furlings, and Nox. But meanwhile, minor incidents with Ba'al continue to occur in the Milky Way galaxy, and he hints that Anubis is regrouping somehow, and we we will all need to be prepared for what is coming.</p>
	</section>
	
	<section>
		<h3>Alt-SGA Season 5</h3>
		<p>Priors of the Ori begin to visit the Milky Way, similar to canon SG1 S9; except the Ori arrive unannounced, having been alerted to our existence by Anubis, who came to join their ranks, rather than by an intergalactic communicator (as in canon SG1 S9:"Avalon"). "You were betrayed by one of your own, one called Anubis." He was destroyed for his efforts. "The Ori do not suffer false gods to live."</p>
		<p>The Priors also invade Pegasus; the Furlings there ally with the surviving Wraith (e.g. Todd) against them. It is revealed that the plague which exterminated the Ancients, which evolved into the blight and pestilence and eventual walking death that are the Wraith, is of Ori origin, and their Priors unleash it upon the Milky Way again. When it is discovered that the Ori draw power from their followers, it is revealed that they used to manifest physically and sap the whole life-force from their victims like the Wraith do; their present method of inducing mass voluntary surrender of free will is a more sophisticated version of the same process. This is why the Wraith feed on humanoids: the energy they draw derives from sapience, and is the same energy which creates the potential for ascension.</p>
		<p>In the Milky Way, Daniel discovers that he has somehow retained some of his ascended powers, when they unexpectedly manifest in a battle against the Priors. He theorizes that he bound himself upon descension to only match force for force, to spare him the wrath of the other ascended beings. This development delays the Ori's invasion of the Milky Way, with Daniel able to help counteract their attempts to redeploy the plague, blight, and pestilence there, and they instead focus their efforts first on Pegasus, which eventually falls. The Wraith are systematically exterminated as "unholy demons", and the scattered Furlings about the galaxy convert, die, or retreat to Taonas and depart for Ida to consult with the Aesir about reinstituting the Alliance of Four Great Races to finally take down the threat which broke it in the first place.</p>
	</section>
	
	<section>
		<h3>Alt-SGA Season 6</h3>
		<p>The Ori follow Taonas on its journey to Ida and discover the Aesir for the first time, who they had previously been unaware of. Priors are dispatched to Ida as well, and are predictably unpersuasive on the Aesir; but the good Replicators, seeking ascension, are temporarily persuaded to side with the Ori, who promise it to them in exchange for their service. Bolstered by Ori technology, they make great headway against the Furlings and Aesir who resist. But when they learn that their promises of ascension are false, the Replicators turn against the Ori in force.</p>
		<p>The Replicators die fighting the Ori to the last man, very nearly defeating them, but being overpowered in the end. The last Aesir world is destroyed, but their minds are uploaded into the computers of Taonas, and they seek out their last refuge: the city-ship called Asgard, a gift from the Ancients during the time of their Alliance, kept cloaked and always in motion, so that it cannot be found except by those who know where it is. This is where the Aesir cloning operations are based, and where the minds of the many Aesir who have gone ages bodiless are stored. After downloading the Aesir into new bodies, Asgard and Taonas together flee to the Milky Way, and Ida is left essentially uninhabited.</p>
		<p>Meanwhile in the Milky Way, SG1 seeks out and deploys the Sangraal to Orilla; and Ba'al's plot to take over Adria (as in canon SG1 S10:"Dominion") succeeds.</p>
	</section>

	<section>
		<h3>Alt-SGA Season 7</h3>
		<p>This season begins as at the beginning of The Ark of Truth, with Tomin defecting from the Ori. After learning of Adria's infestation by Ba'al, he leads a "rebel" Ori force, together with the Tau'ri alliance (Humans, Jaffa, Tok'ra, and Unas), and the last of the Aesir and Furlings, against the "faithful" forces of Ba'al-infested-Adria for most of the season. Simultaneously, the Tau'ri search for the Ark of Truth.</p>
		<p>The surviving Aesir and Furlings beg the powerful but pacifistic Nox to intercede in this war, as the Ori are the ones who destroyed their (mutual) civilization aeons ago. Their pleas are persuasive; though the Nox still refuse to engage in open combat against Ori ships, they counteract the powers of the Priors as they travel world to world, and use cloaking and similar stealth effects to aid in certain missions.</p>
		<p>As in the later events of Ark of Truth, the Tau'ri realize the Ark is in the Orilla galaxy. Unlike canon, Atlantis travels there rather than the Daedelus, because only a city-ship could stand up to Ori ships long enough to complete the mission, and Taonas and Asgard are the last refuges of their respective races. In Orilla, they find that the Ori keep Wraith-like "demons" hiding in the shadows of every world, appeased by a constant feed of life-energy directly from the Ori, unless the people are impious at which point the Wraith are left to hunt for themselves, driving the people back to piety for their salvation. Since the death of the Ori, the feed of life-energy has ceased, and these Wraith have been wreaking havoc on the humans of Orilla. When the expedition encounters them in their search for the Ark of Truth, a new breed of Replicators are fabricated to combat them. There is much protest over this plan as everyone expects it to backfire, but for now it goes off without a hitch and the Replicators lay into the Wraith.</p>
		<p>As the expedition searches for the Ark, a force of Nox accompany them, and defend them spectacularly against the 'magical' attacks of the Priors in the Ori army. When some Nox die in battle, and no others are nearby to heal them, we learn that all Nox are always capable of ascension, but choose to live mortal lives until they have experienced all there is to experience of the material world; upon tiring of life, or on rare occasion when they die, all Nox ascend. But when these Nox ascend upon their deaths, they find themselves suddenly cast back down into mortal form; something, another ascended being or beings of immense power, is fighting them, unable to kill them as ascended beings cannot simply kill each other, but able to keep them from entering the higher planes.</p>
		<p>Meanwhile in the Milky Way, Adria-Ba'al is eventually captured by Tomin's forces, and the symbiote removed by the Tok'ra, segueing into the events of Continuum, with the subtle difference that not only the inhabitants of the new timeline, but even SG1 themselves, are unsure whether the new timeline is really worse off, as there is no Ori threat in it. However, after Ba'al's conquest of the galaxy and invasion of Earth, the point is made moot. After restoring the timeline, Adria dies from complications during the extraction, and ascends (as in canon SG1 S10:"Dominion").</p>
		<p>When they finally reach Celestis, they are brought before the fires of the Ori, and left alone to face them, where they find to their horror that Anubis has not been destroyed, for "Gods cannot die" (as he claims); he was instead imprisoned in a mortal body (still wearing the face of Michael the Wraith-hybrid, his last host), held incarnate by the power of the Ori, and that body physically imprisoned. When the Ori were destroyed by the Sangraal, Anubis was spared by being trapped in such mortal form; and then, with the Ori gone, he was free to take ascended form again, assuming all the power put forth by the Ori worshippers, and finally became the terror he has always dreamt of being. He has since intentionally let the Wraith run free to feed on the life-energy of the humans of Orilla, and he in turn feeds directly on them; a much more efficient process, except in the case of the few most pious of humans, who are spared by Anubis' direct intervention. The humans in turn pray all the harder for salvation from the "demons", taking the cue from the pious few who were spared, further increasing Anubis' power.</p>
		<p>He is now intent on torturing the Tau'ri to death and reviving them eternally until they accept him as the one true God he claims to be. But his plans begin to falter, at first slowly as the Replicators make headway against the Wraith, slower still as Anubis causes the Replicators to turn on the humans as well, but then more quickly as whole armies of Wraith and Replicators alike are annihilated by an unknown force. That unknown party grows in power, making its way across the galaxy, until at last it reaches Celestis and reveals itself to be ascended Adria, feeding on the Wraith to bolster her strength and weaken Anubis, and come to take her rightful place where the Ori once stood. As the Ori worshippers recognize her as their Orici, she draws more power from their prayers than Anubis can, and seems primed to cast him back down and assume control of the galaxy. But in the commotion, the Ark of Truth is deployed against the Doci (as in canon), and the power of the Ori worshippers is withdrawn from Adria. Anubis then makes his move against her, and the two are drawn into an evenly matched eternal battle on the higher planes. The contingent of Nox in Orilla then ascend themselves as well, and promise to see to it that those two remain neutralized, and the people of this galaxy free from interference from the higher planes from now on.</p>
		<p>After the Ori are defeated, Asgard and Taonas return to Ida and Pegasus respectively, to repopulate the Aesir and Furlings. The Tau'ri at Atlantis are dubbed the Fifth Race of the old Alliance, and continue their leadership of the Milky Way Coalition, which jointly begins to explore the worlds now open to discovery in the Orilla galaxy.</p>
	</section>

	<figure class="solo invertible">
		<picture>
			<source srcset="_media/images/stargate-atlantis.svg" />
			<source srcset="_media/images/stargate-atlantis.png" />
			<img src="_media/images/stargate-atlantis.jpg" alt="The Four Galaxies" />
		</picture>
	</figure>

	<p>(To be continued in <a href="../stargate-universe"><i>How Stargate Universe Should Have Gone</i></a>).</p>

</section>