<?php $title = "Evolution and Altruism &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>

				<section>

					<h2>Evolution and Altruism</h2>
				
					<p class="description">A paper for a class on Moral Psychology, 2007.</p>

					<p>In this essay, I intend to explore the concept of altruism and it’s relation to so-called “evolutionary altruism”. This will include both an exposition of what evolutionary altruism is and how it could persist over time, and an attempt to determine whether altruistic behavior is evolutionarily altruistic, which will require an in-depth look at how to characterize altruism. </p>
					<p>A trait is defined by biologists as “evolutionarily altruistic” if and only if it diminishes the reproductive fitness of the individual with that trait, while increasing the reproductive fitness of conspecifics (other members of the same species). This includes both traits which actively aid the survival or reproductive abilities of others at a risk to the survival or reproductive ability of the individual with the trait, such as the whistling behavior of certain species of squirrels at the sight of predators (which draws the attention of said predators to the whistling individual, while simultaneously warning other squirrels of the danger), as well as traits which merely hinder the fitness of the individual while leaving them an otherwise productive member of the social group, such as sterility in worker ants (which reduces their individual reproductive fitness to zero, yet still provides valuable labor for the colony). As to our common notion of altruism as a psychological characteristic, I will present a more thorough investigation of that later in this essay; for now let us say merely that it has something to do with acting to benefit others regardless of any perceived benefits to oneself. Examples of this would be giving to charity, helping an old lady cross the street, or throwing oneself on a grenade in battle. </p>
					<p>Thus at first glance, there appears to be some obvious similarities between evolutionary altruism and psychological altruism: both involve some sort of benefit to another and detriment to oneself. However, a simple counterexample can easily prove that they are not one and the same concept. Consider a woman who has herself sterilized for the selfish reason that she does not like children and does not wish to risk being burdened with them. Such behavior is by definition evolutionarily altruistic (as it reduces her reproductive ability to zero), yet does not seem to qualify as altruism by our common understanding of it. Nevertheless, there is still the possibility that the tendency to act altruistically may be an evolutionarily altruistic trait; that is, doing nice things for others for free could perhaps incur a cost in terms of reproductive fitness on the person doing those nice things, in which case the present existence of altruistic behavior in human populations requires an explanation — if indeed such behavior is even heritable. </p>
					<p>By a simple understanding of the theory of natural selection, whereby those individuals with greater reproductive fitness are expected to survive and propagate their genes while those with lesser genes are expected to die out, evolutionarily altruistic traits would be expected to gradually disappear from populations, as the number of those with the trait dwindled to eventual extinction. Thus the evident persistence of some such traits over great periods of time (as in sterile ants and whistling squirrels) requires a further sort of explanation beyond the level of individual selection. One proposed explanation for the persistence of such traits is group selection, which claims that isolated groups of individuals of a given species which contain individuals with evolutionarily altruistic traits will out-compete groups of the same species which do not contain such individuals, and thus over time the species will come to be dominated by groups with such individuals in them. However, this theory suffers from the problem that evolutionarily altruistic individuals within a given group would be out-competed by other individuals within that group, and thus evolutionarily altruistic traits would still be expected to vanish over time. An alternative solution is kin selection, which is similar to group selection in that it involves competition between groups; however, the theory of kin selection states that an evolutionarily altruistic trait will persist only if it benefits those conspecifics who carry the gene coding for that trait (even if it is only recessive) more than it does those who do not carry that trait. Thus, if the evolutionarily altruistic trait promotes the propagation of the genes coding for it in individuals other than the ones in which the gene is expressed, it will persist over time. </p>
					<p>But whether the presence of psychological altruism today can or needs to be explained this way, and indeed whether it requires any evolutionary explanation at all, depends entirely on whether a tendency to act in such ways is even heritable. This in turn depends on what psychological mechanisms, and corresponding neurological structures, are responsible for altruistic behavior, and whether those mechanisms are innate and completely determined by genetics, or developed only in response to certain environmental factors, i.e. learned. However, a proper answer to this question would require extensive empirical research, and thus I will leave the answering of it to others who are capable of performing such research. </p>
					<p>But the most pressing question here for one interested in ethics is whether psychological altruism is an evolutionarily altruistic trait. The answer to that question depends on precisely how we are to characterize “altruism”. Our working definition thus far has been roughly thus: A person acts altruistically in performing some action if and only if he intends to benefit some other person by doing so, and he disregards any potential impact on himself in his decision to do so. </p>
					<p>The answer to our question hinges mostly on whether we accept the second of these two conditions. Consider: the tendency of any animal (including a human) to ignore it’s own self- interest is clearly bad for it’s survival, inasmuch as traits such as being bad at gathering food, bad at defending oneself, and so forth are bad for one’s survival. Such traits are of course also bad for one’s own reproductive fitness, for if you can’t survive long enough to find a mate, breed, and raise your offspring, then the odds of passing on your genes are nil. Addictive tendencies which cause people to disregard their own wellbeing in pursuit of some trivial object of desire are examples of this sort of character trait, but any object of desire  — including the wellbeing of others — which causes a person to disregard their own wellbeing would be such a trait as well. </p>
					<p>Thus, if altruism as a character trait is to be regarded as a tendency to act from a concern for the wellbeing of others and a disregard for the wellbeing of oneself — in other words, if in order for a deed to be altruistic, the person must not let any thoughts about the consequences of the action upon his own wellbeing bear any weight on his decision-making process  — then altruism is clearly an evolutionarily altruistic trait. On the other hand, if altruism is to be regarded simply as a tendency to act from a concern for the wellbeing of others — that is, a tendency to do nice things for other people just for their own sake, but allowing for the possibility that other motivations may be factored into the decision-making process and thus sometimes overpower that concern for others — then altruism is not an evolutionarily altruistic trait. I believe that first sort of “altruism” is exceedingly rare as a character trait, as most people evidently factor in some concern for themselves into their decision-making process; few if any people work hard all the time and take only the bare minimum of their earnings that they need to keep alive and working, just so that they can give the rest to charity. Further, isolated acts which are thus motivated also seem rare, occurring only in heat-of-the-moment snap decisions where concern for oneself is simply not taken into account — but had the person longer to think about it, they may not have made that same decision. People may throw themselves on grenades in the heat of the battle, or jump into a flooding river to save a drowning person before they are washed out of sight, but it is rare if not unheard of that a someone should wake up one day in a generous mood and give his entire estate to charity, when there is no pressing need to make such a decision quickly. </p>
					<p>But many people do give something to charity, or perform volunteer service, or just do random nice things for strangers out of the kindness of their hearts, simply out of a desire to benefit others. But there is in these common cases some self-interested consideration involved, as evidenced by the fact that most people do not give all they have to charity and devote their entire lives to the service of others. The intention behind such lesser acts, which I at least am still inclined to call altruistic, seems to be “to do good for someone else, so long as it doesn’t cost me too much”. Thus I would define an altruistic act simply as one which has the benefit of another as an ultimate aim; an act which you would do just for the sake of another, even if it had no impact on you at all, though impact on you may still be a factor in your decision-making process. </p>
					<p>Consider an example to illustrate. Say that as I am leaving the grocery store, I find an old lady carrying out her heavy bags of groceries with some difficulty, and I offer to carry them to her car for her. I expect that this act won’t earn me anything but perhaps gratitude, and it will costs me a few moments of my time and some extra calories; but I don’t really care about the gratitude, just about helping little old ladies, and that cost to me is not much at all, so I decide that I will offer my services to her. However, if upon making my offer I learned that she was taking the groceries not just to her car in the parking lot, but to her house many miles away, I would likely rescind my offer, indicating that there was some hidden selfish consideration in there all along. I was willing to help her, so long as the cost to me wasn’t too great, which the time and effort need to carry her groceries many miles would be. Even if she was in fact merely taking them to her car, and thus I did decide to help her, if it was still counterfactually true that I would not have helped her carry them all the way to her house, that is evidence that there was some selfish consideration at work there. My desire was not simply “to help the old lady” (unconditionally), but “to help her on the condition that it not cost me too much”. So even though this is a paradigm example of a small altruistic act, it is not devoid of concern for myself, and thus I cannot consent to a definition of altruism that requires that the object of the desire motivating the act not include any reference to oneself. Instead, all that is necessary is that the benefit of another be an ultimate aim of the act; that nothing else be needed to cause the actor to want to do it, though other factors may cause him to want more strongly not to do it. </p>
					<p>Altruism, understood in this sense, is clearly not at all evolutionarily altruistic, for the desire to benefit others by itself does not incur any cost on one’s own reproductive fitness (though a disregard for oneself would). Thus even if such behavior is an inherited trait — a question still left unanswered in this essay — it’s existence in modern humans requires no special evolutionary explanation.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
