<?php $title = "Inconceivable &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>

				<h2>Inconceivable</h2>
				
					<p class="description">A paper for a class on Philosophy of Mind, 2006.</p>

					<blockquote><p>You keep using that word. I do not think it means what you think it means.</p></blockquote>
					<p>In his Meditations, Descartes lays out an argument intended to show that minds could possibly exist without bodies, and thus that minds are not identical with or reducible to material bodies, or parts or functions thereof. This argument centers on a thought experiment involving a deceptive "evil genius", meant to show that disembodied (purely mental) existence is conceivable, and thus logically possible, from which it would rightly follow that minds must not be reducible to material bodies. In this paper I intend to show that Descartes' argument, while valid, is unsound, by presenting an exposition that proves either, depending on your interpretation of conceivability, that the premise that 'disembodied existence is conceivable' must be false (my preferred interpretation), or that the premise that 'conceivability entails possibility' is false (a seemingly more common interpretation). </p>
					<p>The gist of my argument is that conceiving of some sensations, which you interpret as being due to a certain hypothetical state of affairs, does not entail that that state of affairs is logically possible, but only that the experience of those conceived sensations is logically possible. </p>
					<p>That is to say that just because I can conceive of certain pictures and sounds and such, which I associate with some hypothetical state of affairs, does not mean that the state of affairs I associate with them is possible, only that some state of affairs is possible which would produce such experiences. I prefer to see this such that conceivability does in fact entail logical possibility, but that people such as Descartes quite often are not conceiving of what they think they are. But you may, if you like, take this to mean that conceivability, understood the way Descartes seems to, does not in fact entail logical possibility. </p>
					<p>Let us examine Descartes argument itself. First, as already stated, he uses premise that conceivability entails logical possibility, albiet implicitly. He qualifies this that such conception must be "clear and distinct" for this premise to be true, a qualification which I not only accept but further emphasize to the detriment of Descartes' own conclusion. He also uses an implicit and obviously true premise that if some thing X (such as a mind) can possibly exist without the existence of another thing Y (such as material bodies), then X is not identical with, a part of, a function of, or in any other way reducible to Y. Thus, if Descartes can show that disembodied minds are clearly and distinctly conceivable, and that such conceivability does in fact entail logical possibility, then it must follow that disembodied minds are logically possible, and thus that minds are not reducible to bodies. Descartes simply assumes that clear and distinct conception does entail logical possibility, and with that I do not intend to argue, though I argue that Descartes himself is not "clearly and distinctly" perceiving what he thinks he is. </p>
					<p>To show that disembodied minds are conceivable, Descartes turns to a thought experiment involving an "evil genius". He claims to be conceiving of a possible world where he has the all same experiences that he does in the real world, but all of these experiences are simply deceptive images transmitted to his disembodied mind by another, more powerful disembodied entity, which he calls an "evil genius". In this conception, Descartes claims to imagine that no physical world actually exists, and that the entire universe consists simply of him, a disembodied mind,  being deceived by this malevolent being. Thus, as Descartes thinks he can conceive of this situation, he concludes that it is logically possible for no physical world to exist, while he, a mind, does exist, and therefore that minds are not reducible to bodies but rather entirely independent of them. </p>
					<p>My response to Descartes would be to ask what exactly it is that he is conceiving, for to me it is neither clear nor distinct. I honestly cannot see any significant difference between his description of what he is conceiving and the real world. The root of this problem is that I can only conceive of that which I could hypothetically perceive. That is to say that, if asked to conceive of something with no perceptual qualities, I am as unable to do that as I am unable to conceive of square circles — I don't even know where to begin trying. So, as Descartes' description of this thought experiment has no perceptual qualities different from the real world, it seems that all I am conceiving of is just the real world itself. But let us attempt, for the sake of charity, to put some more effort into conceiving of a situation where all my normal perceptions are false. </p>
					<p>I could perhaps conceive of the real world, plus the ostensible belief that all of my perceptions are false. That is, I could conceive of myself apparently here in my room, writing this essay, and being disposed to say things like "all perception is deception", or thinking those words, or agreeing with such statements. I can imagine how I might behave if I believed such a thing, other thoughts that I might think because of those beliefs, and so forth. Perhaps I would, as a result of those beliefs, become a religious person and start to attend church regularly. But as things in themselves, separated from our experience or perception of them, by definition have no perceptual qualities (being so separated from them), I cannot conceive of such things directly, and thus I cannot "clearly and distinctly" conceive of it being the case that something is in fact true or false. I can only conceive of what such a thing might look, sound, smell, taste, or feel like, and in this case the only differences as such between this conceived world and the real world are differences in my own behavior. It seems that all I have conceived here, and thus, all I have shown to be logically possible, is that I could believe that my experiences are entirely deceptive. </p>
					<p>That is non-controversial, as anyone can believe practically anything they want, and showing that a belief is possible — merely that it would be possible to believe something, not that the thing believed is itself possible — is not helpful to Descartes' argument. </p>
					<p>Let's try this again then, another attempt to conceive of all of my perceptions being false. </p>
					<p>I suppose that I could conceive of myself apparently here in this room, writing this essay, and then suddenly, all my perceptions stop. I lose all vision, hearing, senses of touch and taste and smell, even my sense of kinesthesia or proprioception, even the residual images in my eyes and the sound of my own blood flowing in my ears. I imagine that I utterly cease to experience anything. But in conceiving of such a thing, it seems that all I am conceiving of is nothing at all. </p>
					<p>As I can only conceive of things which I could perceive, when I conceive of not perceiving anything I have simply stopped conceiving entirely. This lack of conception — not inconceivability, but simply willful lack of conception — clearly does not prove anything. So let us modify this thought experiment. I do not imagine that this is what Descartes had in mind, but I feel obligated out of charity to give my best support to his argument, and in doing so thoroughly dismiss it when it still fails. </p>
					<p>So I will now imagine that I am sitting here in this room, writing this essay, when suddenly my vision grows dark, my ears ring out into a dull monotone, my skin grows numb, and my sense of balance and space becomes skewed. Then my senses become refined again, and I find myself lying on a floor in a vast dark room, with a small, lanky, muscled figure grinning an evil grin at me. I imagine that he tells me that he is The Evil Genius, and that all of my experiences up until and including this very moment as I lie here before him are and always have been entirely false, that there is no material universe, and he and I are all that exists, utterly disembodied — even his visage before me now is a deception, as even he has no physical form. I imagine then that he tells me he will now return the normal stream of experiences, and I feel the sensation of rushing through the darkness above me as the little figure recedes into the distance and vanishes, and suddenly I feel a hard jolt as I am once again in my chair. </p>
					<p>I imagine that I would then begin to wonder who had laced my food with drugs this evening. And I would be right to doubt the veracity of that experience, as even Descartes would agree, although for different reasons. I would doubt it because, on the surface, it seems utterly incompatible with my other experiences, and would require either a fantastic explanation such as those to be described below, or a more mundane explanation such as hallucinogenic drugs. In short, I can agree with Descartes at least that any individual experiences, or at least our interpretations thereof, are dubious. Descartes would likely doubt such a thing because he finds experience on the whole to be dubious. Either way, this imaginary me would find himself doubting the veracity of these extraordinary experiences, and though perhaps they might be the thing which planted the notion of universal deception in his mind, the fact remains that all that I am imagining when I conceive of this doubtful self is the possibility that I might, for some reason, believe all my experiences to be false. I still have not directly conceived of my experiences being false, and thus have not proven that to be logically possible. At this point I can still find no means by which to doubt that some material universe exists, even though my beliefs about the specifics of that material universe are dubious. </p>
					<p>But I can imagine a situation which could demonstrate with irrefutable mountains of evidence that all my experiences up to the point of revelation had been false. I can imagine that as I sit here writing this, I once again become blind, numb and disoriented and wake up in a room with this lanky Evil Genius, yet instead of returning me to my normal set of experiences, he takes me out of this large dark room and shows me the world as it really is. I can imagine seeing nightmarish landscapes and ominous buildings, and being told that I am to live here now until I die, for he and I are the only people in this desolate world, and everything up until now has been signals fed into my brain to allow me to believe that I was living a life on Earth. I can even imagine that I am not human, that I have a small form like his, as we are perhaps the last of some dying alien race. Perhaps Earth and humanity never existed and were merely a fantasy conjured up to spare me this hideous existence. I concede that it is entirely conceivable, and thus logically possible, that the world which I am in fact experiencing right now is not the real world. But even in conceiving this, I have not conceived that the physical world does not exist. Merely, I have conceived that the physical world is nothing like what I thought it was. But still I am conceiving of it existing. I can even conceive that the above world might itself be a deception, that perhaps I am a really brain in a vat being experimented on by scientists. Perhaps those scientists and my vat are themselves not real, and that entire world is in fact inside the Matrix. I can imagine as many layers as I like, but at some point I must always conceive that some physical world exists. </p>
					<p>To do otherwise is simply to conceive nothing, as shown earlier, which does not prove anything. </p>
					<p>It seems that I simply cannot conceive of no material world existing at all. </p>
					<p>The long and short of it is that I, at least, cannot conceive of a world which is "actually real" and yet is utterly inaccessible to experience. To speak of a thing which supposedly exists yet is in principle beyond any ability to experience, even with the aid of the greatest imaginable scientific instruments, seems to me utter nonsense. For example, I might be asked to conceive of a "moncupator" existing here in my room, a thing which interacts with no physical forces and is thus invisible, odorless, tasteless, soundless, and utterly incorporeal. I can conceive of saying or thinking things like "I have a moncupator in my room", or answering "yes" if someone asked me if I had one, but I simply cannot conceive of the moncupator itself. The word "moncupator" does not connect to any sensible ideas, any experiential or perceptible qualities; it is empty and without any real meaning. </p>
					<p>And what is it to say that something is physical or material if not that it is in some way accessible to the senses? Not that it is being sensed, or ever has been or will be sensed, but that, if someone were to make the appropriate observations, it would be observed. If we were to take a highly skeptical position that the "real world" is not in fact accessible to the senses, then the notion of the "real world" would become as vapid and meaningless as the notion of a moncupator. It seems to me that the only meaningful use of the term "reality" is to refer to that which we can experience: not merely the subjective set of things which we do experience or have experienced or will experience, but all things which could possibly be experienced. </p>
					<p>Understood in this way, I can no more doubt the existence of the world than I can doubt my own existence. In some sense, I can doubt the both of them, inasmuch as I cannot conceive of a universe beyond experience, nor can I conceive of myself not experiencing anything, and thus it might seem that all that is really real is the experience. Georg Lichtenberg once criticized, in that vein, that Descartes' cogito ergo sum went to far, and all we can really conclude from that Meditation is that there is some thinking going on, not that a thinking thing exists. But just as subjects and objects of experience are inconceivable without experience itself, so too those experiences come part and parcel with the indubitable notions of a subject and an object — a self and a world. If any experience occurs, someone must exist to experience it, and something must exist to be experienced (though not necessarily the thing which the subject of experience thinks is being experienced). These things are inconceivable without each other, and thus it is impossible that they could be distinctly different and separable things.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
