<?php $title = "Moral Foundations &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>

					<h2>Moral Foundations</h2>
				
					<p class="description">A paper for a class on Moral Psychology, 2007.</p>

					<p>In this essay I intend to look at issues regarding infinite regress problems for justification, first in the more commonly discussed case of epistemic justification (that of beliefs) and later in the case of practical or moral justification (that of actions or desires). In particular I will examine the classical foundationalist answer to the problem of infinite regress, and the alternative constructivist answer put forth by Joseph Heath in “Foundationalism and Practical Reason”. </p>
					<p>The problem of infinite regress as it regards epistemic issues is thus: for every belief, it seems rational to ask what the justification for holding that belief is, i.e. why is it right to believe that, what reason is there to believe that and not something contrary to it? However, the reason given to justify those beliefs is usually another belief — for example, I believe that my girlfriend is at home right now because I believe that she got off work two hours ago and has nowhere else to be tonight — and the question can then be asked again, “Why are you justified in believing that?” In the above example, my response would be another belief: I believe she told me her plans and work schedule last weekend when she came to visit me. The problem of infinite regress is that every belief seemingly requires another belief to justify it, which in turn requires another, and so forth; and if this regress continues forever, we are forced to conclude that no beliefs can be justified, or in other words, that nobody can truly know anything. </p>
					<p>There are several responses to this problem of regress. The skeptic will simply throw up his hands, say “Oh well, I guess we can’t know anything”, and be done with it; but that is at best an unproductive response, to be polite. The coherentist solution is to say that beliefs can somehow justify each other in a circle, together forming a mutually justifying coherent set of beliefs; but among other problems with such an approach, circularity is generally frowned upon in any argument, so coherentism seems untenable as well. The traditional foundationalist response is to say that the regress does not continue forever because there are some beliefs, called basic beliefs, which are either self-evident and thus do not require justification, or which are justified not merely by other beliefs, but by something such as perception, which does not itself require justification. To continue the example, my belief that my girlfriend told me her plans and schedule last weekend is justified, on a foundationalist account, simply by my memory of having that conversation with her; and no justification for believing what I remember is required. </p>
					<p>The practical or moral version of this regress argument is very similar. It seems that one may rationally ask why a person desires to do some action, that is, what reason they have for doing that action; but as with the epistemic case, the answer is usually in the form of another desire. For example, a student may desire to study in order to fulfill his desire to do well on an exam, which he may in turn desire in order to pass that class, which he may desire so that he will graduate and earn his degree, which he may desire because it will afford him opportunities for higher-paying jobs, which he may desire for money, which he may desire so that he can afford a house and a comfortable life, and so forth. The responses to this practical regress seem quite similar: either this must continue forever, and no desires are ultimately justified, thus all action is wanton and without good reason; or some sort of circular justification is possible; or there are some desires which are basic, not requiring justification, or justified by things other than desires, such as pleasure or some sort of practical reason, which themselves do not require justification. </p>
					<p>Heath claims that both Humean and Kantian accounts of rational motivation assume this sort of traditional foundationalism. In the case of the Humean, who argues that all actions are motivated by a combination of a desire for something and a belief that acting in such a way will bring about that thing, the foundationalism is fairly clear. If one is asked why he desires something, the response is always (according to the Humean) another desire, and the reason he desires that is in order to achieve something else he desires, until it comes down to simply desiring something, period, with no need for justification. On the other hand, the Kantian, who claims that actions can be motivated (or desires justified) simply by beliefs or some process of practical reasoning, also assumes a sort of traditional foundationalism. The appeal to beliefs about moral facts merely turns the regress into an epistemic one, pushing the problem back to one of how to determine what is intrinsically good. Alternatively, a Kantian process of practical reasoning (about categorical imperatives and such) may be taken as somewhat analogous to a self- evident truth, and duty thus discovered can itself serve as a foundation for practical reasoning. </p>
					<p>But there are significant objections to this traditional foundationalist account, in either the epistemic or the moral cases; first among them being the apparently arbitrary choice of where to draw the line dividing basic beliefs or desires from non-basic ones. So Heath has an alternative to traditional foundationalism, in the form of a sort of constructivism. Heath is also a foundationalist, but he does not hold that there is any special class of beliefs or desires, such as those justified by perception or pleasure, which must form the ultimate foundation of any line of theoretical or practical reasoning. Instead, he holds that a belief or a desire is justified simply by appeal to whatever standard of justification is socially accepted. In some religious societies, the ultimate standard of justification may be some holy text, and “our holy text says I ought to believe (or desire) this” is good enough reason to believe (or desire) it. In modern societies, epistemic justification may appeal to some sort of empirical basis, or to more elaborate scientific justifications such as abductive reasoning (i.e. that some hypothesis is the “best explanation” for some observed phenomena is taken as good reason to believe it). Likewise, practical justification may appeal ultimately to some sort of hedonism, as in utilitarianism, or to some notion of rights and obligations. But one way or another, the specific ground of justification is not important to Heath — it merely matters that there be some socially accepted standard to appeal to. </p>
					<p>At first glance this account of justification would seem to be implausibly relativistic, leaving truth or goodness merely a matter of popular opinion, which of course varies between different societies in different places and times. But Heath distinguishes — to focus here on practical or moral reasoning — between something being morally justifiable, and something being morally right. His account of moral rightness is also constructivist, but it aims for much more objectivity than his account of justification. For something to be morally right, it must be not only justifiable to society today, but it must continue to be so justifiable (or become so justifiable if it is not now) as improvements are made to a society’s moral standards. “Improvement”, in turn, is understood to mean the result of a process of open, public deliberation, where everyone has a say, everyone’s case is considered, and no one is coerced. In other words, something is morally right if it is justifiable by the standards of an ideal society, where such an ideal society is the eventual end product of a (perhaps infinite) process of non-coerced public deliberation. </p>
					<p>I find Heath’s solution to be unexpectedly satisfying for a constructivist account (the likes of which I am normally opposed to on the grounds of their relativistic implications). By placing morality not at the whims of any particular society at any place or time, but rather in the hands of some hypothetical future society, which may never in fact actually come about (contingent upon unknown future developments), his account circumvents, as far as I can tell, all the relativistic problems which usually arise by implication of a constructivist account. It is somewhat akin to saying that the absolute truth is whatever is in accordance with the theories toward which proper epistemic processes converge. Such an account of truth would not allow any society at any point in time to rightly proclaim that their beliefs are known to be true with absolute certainty; but it does not fall victim to relativism because the believers of more advanced theories can still look down upon lesser theories and rightly judge them to be further from the truth on account of thing such as contradictory phenomena or faulty inferences. </p>
					<p>Likewise, under an account like Heath’s, a more advanced society can look down upon lesser ones for their failure to take into account the rights of particular minorities or individuals, the undesirable long-term consequences of a particular policy on the whole society, and so forth; restating the arguments made in the public deliberations which moved the more advanced society forward. In short, the more advanced society can look back and rightly say “we’ve been there before, and have since realized the error of our old ways; our new ways may not be perfect either, but we’ve improved”. It is of course possible that a society may improve in one way while degrading in another, or that two societies should improve in different ways and both feel, correctly, that they have a moral advantage over the other. But similarly, two different, incompatible theories may each have strengths where the other has weaknesses (take for example quantum mechanics and general relativity) and the process of trying to reconcile these complementary theories, or replace them, drives the improvement of our theoretical knowledge. </p>
					<p>Likewise, while two societies may both be right in claiming superiority to each other in one way or another, that just means that both societies have some room for improvement; not merely that they have differences of opinion and there is no objective right and wrong about the matter. Thus while Heath’s account of justification is highly relativistic, his account of morality, in the sense of right and wrong, is perfectly objective.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
