<?php $title = "Normal Science &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>

					<h2>Normal Science</h2>
				
					<p class="description">A paper for a class on Philosophy of Science, 2007.</p>

					<p>In The Structure of Scientific Revolutions, Thomas Kuhn gives an account of what he deems ‘normal science’, as differentiated from ‘pre-science’ and ‘revolutionary science’. His entire account of science focuses on the concept of a ‘paradigm’, which I will describe in further detail shortly; and normal science according to Kuhn is simply research conducted within the context of an established paradigm. In contrast, pre-science is the investigation and theorizing that happens in some field of inquiry before the establishment of a paradigm, and revolutionary science is the activity which occurs during a shift from one paradigm to another. In this paper I intend to lay out a brief summary of Kuhn’s account of normal science, and then to critically evaluate it’s strengths and it’s weaknesses. </p>
					<p>Normal science is perhaps best understood in contrast to pre-science. In pre-science, researchers go about investigating various interesting phenomena, measuring them, recording data about them, and trying to explain them with rudimentary theories. But in pre-science, there are often nearly as many theories as there are researchers, none of which are particularly impressive to other researchers (who have equally good alternate theories of their own), and none of which thoroughly accounts for most of the available data. What makes an area of investigation turn truly scientific is the emergence of a theory which establishes what Kuhn describes as a “paradigm”. A paradigm is a sort of explanatory framework established by an exemplarily good theory, one which explains large portions of the data at hand, and in particular explains very well some piece of a phenomenon that has been especially hard to explain. This exemplary theory and the research that led up to it’s creation lay out not only accurate generalizations of data regarding the phenomena in question, but also the types of instruments and techniques useful in it’s investigation, and the quasi-metaphysical assumptions that underlie the explanation of the data.</p>
					<p>Such a theory proves so powerful and useful that it is adopted by the rest of the pre- scientific community, and their efforts cease being a myriad of attempts to come up with new, all-inclusive theories from scratch, and instead turn to the concerted effort of fleshing out the details and problems of this new paradigmatic theory. With such a paradigm in place, more detailed scientific work can progress in a guided, nonrandom fashion. By deriving implications from the paradigmatic theory, scientists can be guided to what relevant data would confirm or falsify the theory. If they find new data which agrees with their theory, the scientists then have the go-ahead to search for more and more specific data, seeking to verify the more interesting implications of the theory, confident that theory as thus far tested is free of error. Alternately, if the data disagrees with the theory, the scientists then face the challenge of either creatively interpreting the data and their related assumptions to fit it within the paradigm, or somehow modifying their working theories within the paradigm in order to account for the new data. </p>
					<p>In this last way it is made most clear that a paradigm is not itself a particular theory, but rather a sort of family of theories, techniques, and assumptions; a general way of approaching a set of problems. While particular theories within the same paradigm may come and go and change as new experimental results come in, all effort is made to maintain the foundational assumptions of the paradigm, until eventually some anomalous data proves so difficult to explain from within that paradigm that some of those basic assumptions must be thrown out, and a new paradigm created. But between the first invention of a paradigm and the crisis which eventually destroys it, the paradigm serves to guide the process of normal scientific inquiry, and leads to many detailed discoveries that likely would not have been made without the paradigm, and often even outlive it. </p>
					<p>Kuhn explicitly acknowledges that his account of science blurs the distinction between descriptive and normative, and he seems to imply something along the lines of “this is how real scientists work, and they have had great success working this way, therefore this must be the correct way to work”. I do not intend to question his descriptive account of how scientists actually work — it tracks reasonably well with my limited experience of professional science, and as a professional scientist himself Kuhn is eminently more qualified to describe his profession than I am. However, I would protest several elements of his account as normative prescriptions of how scientists ought to think, and what ought to be thought of as science. Even so, these objections are really more of qualified acceptance of his overall program, where though I do not accept his description of science as epistemologically normative (that is, giving people good, strictly theoretical reasons why they ought to be believe something over something else), it does seem to be a useful and pragmatically reasonable investigational methodology. </p>
					<p>My objection is that it seems demeaning to call the work done prior to an established paradigm “pre-science”, or research done outside of the commonly accepted paradigm somehow less than scientific, if science is to be understood in any sort of normative sense. That is, if labeling something unscientific is to be considered an attack on it’s epistemological integrity, implying that the reasons for believing it are not quite good enough (which I imagine Kuhn, as a scientist, would say), then boxing science entirely within the definition of “research conducted in the context of an established paradigm” seems to unfairly rule against some cases of perfectly good, empirical, and what I would call scientific, reasoning. I make this claim even while acknowledging that having an established paradigm through which scientists can work in concerted effort together is pragmatically beneficial to the discovery of new knowledge. I mean only to refute the claim Kuhn seems to imply, that work done outside of the social establishment of “science” is somehow less legitimate than work done within that context. </p>
					<p>The root of my objection lies in the social aspects of Kuhn’s definition of a paradigm; that a theory must gain wide acceptance and impress researchers in a field in order to establish a paradigm. While it seems perfectly normal and right that a very good theory will become widely accepted and popular, it does not follow conversely that widely accepted or popular theories are somehow better (in the sense of more epistemologically justified) than less popular theories. The only thing that a rational person with no other bias ought to consider when choosing between two theories (presuming that both meet the same criteria of rationality, empiricism, mathematical rigor, etc.) is which better explains the available data. This does not necessarily mean simply which explains the most experimental results; some data may be weighted differently than others, such that failure to account for certain experimental results reflects more poorly on a theory than failure to account for other results would. But if no determination could be made on any such epistemological criteria, then any choice would necessarily be made on some other basis: a purely aesthetic decision, by some criteria such as elegance; or a pragmatic decision based not on theoretical reasoning suggesting that one theory is more true or accurate (or less false) than the others, but on practical reasoning suggesting that it may be more useful (e.g. for the purposes of furthering research activities) to work with one theory than the other. </p>
					<p>A billionaire super genius with an independent education and his own research facilities could hypothetically come up with an alternate theory of something which is every bit as good at explaining those phenomena as the prevalent paradigmatic theory that the rest of the scientific communities adheres to, and thus just as epistemologically valid. But if his theory is really just as good, not impressively better than the standard paradigm (thus possibly establishing a new paradigm, if there were some critical anomaly that the existing paradigm failed to explain and the new one did), then it would be a good practical decision to run with the established paradigm, just so that further research efforts could be conduced in concert with one another. Here, Kuhn’s account holds up strong. By coming to agreement on the bigger questions of a field of inquiry, researchers are freed to focus on the smaller and more intricate details of the phenomena in question than otherwise would be investigated by a lone researcher. The data gathered in such activity is often useful even beyond the paradigm in which it was conducted, and may ultimately contribute to the creation of a newer and better paradigm — perhaps even one similar to some of the fringe theories which were disregarded during the life of the original paradigm.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
