<?php $title = "Oh Dear God No &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>

					<h2>Oh Dear God No</h2>
				
					<p class="description">A paper for a class on Philosophy of Religion, 2007.</p>

					<p>In this essay I will reconstruct and refute a short argument (composed by an "unknown" author) purporting to prove the existence of God. This argument is composed of three sub-arguments, one of which is supposed to prove the existence of an eternal being, and the other two of which are supposed to prove this being all-powerful (or at least, "most powerful") and all-knowing (or at least, "most knowing"), respectively; leading us to conclude that said being is God as commonly characterized by western theists. I will look at each of these individually.</p>
					<p>In the first sub-argument, it is posited than any individual ought to be able to construct for his or herself an argument along the following lines. Given the premises that I exist, that I am something, and that something cannot come from nothing, I can conclude that something exists (if nothing else, I do), and from that and the third premise, that something has always existed. From here, we are encouraged to conclude that the existence of an eternal being (implied to be God) has been proven, i.e. that "something has always existed" (which is a sound conclusion to this argument), is equivalent to "there is some thing which has always existed". However, these are clearly not equivalent, and the latter is not what is proven by this argument. This argument merely proves that at any given point in the past, the statement "something exists" must have been true, for if at any time nothing at all existed, then what exists now must have been (or have descended from something which was) created from nothing, which is ruled out by our third premise. But this does not mean that there must be any one thing which has at all times existed; what existed at one time may be entirely different from what existed at a later time, the former having given rise to the latter and then passed away itself.</p>
					<p>Now it is trivial to prove in one sense that there is some "being" which has always existed, if we take the universe itself - the sum of all things which exist - to count as a "being". Given the above proof that it has at all times in the past been true that something exists, then it has at all times in the past been true that the universe exists; though still, what constitutes the universe at any given time may be drastically different from what constitutes it at other times.</p>
					<p>Further, if we were to allow as a premise the modern scientific principle that mass-energy can never be created or destroyed, merely changed from one form to another, then it must be true in some sense that everything which currently exists has always existed, only in radically different forms. However, these sorts of arguments are of no religious interest to anyone but pantheists, and are of little use in proving the existence of any God as conceived of by traditional theists.</p>
					<p>Though I have already stalled this whole argument right out of the gate, let us grant for the sake of argument the conclusion of this first sub-argument (which could perhaps be proved some other way), and look at the other two sub-arguments, which purport to prove, respectively, that such an eternal being is the most powerful and most knowing being. The second sub-argument is the one regarding power. It claims that as all other beings owe their existence to this eternal being (that is, they were created by it or from it), all attributes they have must stem from this eternal being; and as powers are attributes, this eternal being has all the powers of all lesser beings, and is thus the most powerful being. This argument breaks down roughly as follows: An eternal being exists. All other beings have been created by this eternal being (or in turn created by those created beings). All attributes which a created being has, its creator has. Therefore, all attributes which any being has, this eternal being has. Therefore, all powers which may be attributed to any being, may be attributed to this eternal being. Thus, this eternal being is the most powerful being.</p>
					<p>This argument has many flaws, the first being the assumption of an eternal being; though as I have granted that premise for the sake of argument, I will let it slide. The second premise, however, is also refuted by my line of reasoning above: even if it were possible to prove an eternal being, it would not follow that all other beings owe their existence to that being. They could be created in an infinite series which never has its roots in the eternal being, merely existing alongside it. Further, even if all finite beings owe their existence to an eternal one, we still do not know that there is simply one eternal being; there could be many, none of which is by itself the sole origin of all other beings. But the fatal flaw of this sub-argument is the premise that all attributes which a created thing has, its creator has. A creator can clearly create things with properties it does not have; humans regularly create machines which are nothing like us, and often far more powerful in one way or another. So it stands to reason that any sort of creator-being need not be all powerful or even the most powerful; it need not have any other powers than some sort of creative spark which got the ball rolling, and all created things since may have been slowly creating more and more powerful (and otherwise different) things in successive generations.</p>
					<p>The third sub-argument is the most poorly constructed of all. It purports to show that this eternal being (which I will again grant the existence of for the sake of argument) is the most knowing being. This argument proceeds similarly to the first, in that it is claimed that any given person may reason that as he or she knows some things, a knowing being exists; and then, that either knowledge (and knowing beings) came into being from a previous state when there was no knowledge, or there has always been knowledge (and a knowing being). Further, as something cannot come from nothing, the creation of knowledge from non-knowledge is impossible, and therefore a most knowing being, from whom all knowledge derives, must have always existed.</p>
					<p>This is implied to be the same eternal being earlier "proven" in the first sub-argument.</p>
					<p>Where to begin? Yes, certainly a knowing being exists - I do - and given that fact, then either knowing beings have always existed or they came at some point to exist from out of a previous time when they did not exist. However, the denial of the second of these two disjuncts is not at all a valid inference. Even if we accept that something cannot come from nothing, that does not rule out a knowing thing coming from a non-knowing thing, for the non-knowing thing is still something, and thus the knowing thing has not come from nothing. This seems to be supported only by the previously disproven premise of the second sub-argument that all creators must have all the properties of the things they create, thus ruling out knowledge arising where there previously was none. However, not only is that premise disproven, but it would lead to the absurd consequence that learning, except from another knowledgable being, is impossible; but I am intimately familiar with this process of learning new things directly from experience, not being taught them by other knowledgable beings, so unless we are to beg the question and simply assume that the world was created by a knowledgable being specifically to convey its knowledge to us mere humans, this inference that knowledge and knowing beings must have always existed is egregiously invalid.</p>
					<p>However, even if we were to accept that conclusion (and the picture of knowledge transfer and acquisition associated with it), it still does not follow that there is one ultimate source of all knowledge, or even if there was, that there must have been one eternal being carrying all that knowledge alone until it decided to share it with others. There could have always been an assortment of finite knowing beings, passing down knowledge between each other and to new beings, such that there is no single ultimate source of all knowledge. Even if there were in fact one single source of knowledge at some point in the past, it does not follow that that being must be eternal and have always known all that; it could have acquired that knowledge from a previous being or several previous beings, who could in turn have acquired it from its or their predecessor(s) and so forth ad infinitum.</p>
					<p>Thus I feel I have shown that these sub-arguments for the existence of an eternal being, and its supreme power and knowledge, are all unsound. However, even if these arguments were all sound, and they could prove that there existed at some moment in the past an ancestral being which had existed for eternity before then, and was the source of all power and knowledge and all other things in the world today, they still do not form together a sound argument for the present existence of God. For one, they do not prove that such a powerful and knowledgeable being exists now, today. That being, if it ever exited, could have created everything from itself and then been itself no more, pan-deistically; or merely created the world as in traditional deism and then simply died. Nothing here has proven that this being is logically necessary or even simply immortal; merely that it has (or at least had, up to the moment of Creation) existed for all past time. Further, even if such a being does exists in the present, we may still ask the question, "Is that being God?" There is the minor question of whether "most powerful" and "most knowing" are enough to count as God - the traditional conception is "all powerful" and "all knowing", which may not be the same thing. Further, nothing thus said about this being implies that it is at all good, much less perfectly good, which is another attribute of the normal conception of God. If such a being existed today, it could be a malicious demon such as Descartes' "Evil Genius" or the Gnostics' "Demiurge". And thus not only do none of the sub-arguments in this argument succeed, but even if they had, the argument as a whole still would not succeed in its aim at proving the present existence of the common western conception of God.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
