<?php $title = "Reconstructing Gender &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>

					<h2>Reconstructing Gender</h2>
				
					<p class="description">An analysis of gender identity concepts, 2013.</p>

					<p>Though I am wholly supportive of all forms of gender variance, I take philosophical issue with the language and conceptual structures usually used to frame gender identity issues today. Because of this, I am frequently distressed that I cannot speak of my own atypical gender identity succinctly without either offending people with whom I sympathize and whose choices and causes I support, or sacrificing my own intellectual integrity by conceding to a conceptual framework I disagree with.</p>
					<p>The purpose of this essay is to defend the legitimacy of the framework within which I construct my own gender identity. But before I continue, I wish to first express my support in the substantial matters of gender identity issues (e.g. moral and political matters, in contrast to the comparatively trivial philosophical and linguistic matters I contest), in verbose and hopefully neutral language; and also to give a similarly verbose and hopefully neutral description and history of my own gender identity for reference.</p>
					<hr />
					<p>Broadly speaking, I support anyone's right to do anything which doesn't harm another person, in all matters. As specific applications of that broad stance, I support everyone's rights both to partake in any social role without discrimination, and to do whatever they wish with their own bodies. As specific applications of <em>those</em> principles to issues of sex and gender, I support everyone's rights both to partake of any gender role regardless of their anatomic sex, and to alter their anatomic sex in any way they see fit. To be clear, I hold these two rights to be wholly independent of one another: social roles should not be linked to anatomy or vice versa; a change in sexual anatomy should not be mandatory to a change in social role, nor a change in role mandatory to a change in anatomy.</p>
					<p>More than merely supporting these as rights, in a sense of "it's not my place to judge" or "I'll agree to disagree", I think there is <em>absolutely nothing wrong in any sense</em> with anyone for any reason wanting to live any social role or do anything with their own bodies. Nobody is weird, deviant, perverted, unnatural, or abnormal for wanting to do so. In another sense further I even think it is not just acceptable but a downright positive thing for people to push the boundaries of society and medicine in the pursuit of being whoever they want to be.</p>
					<p>I recognize that "want" may not feel like an accurate verb for many people who have highly conflicted feelings about their sex; feelings about their feelings, people who may feel one way and also feel distressed <em>about</em> feeling that way, who may on one level want something but on another level want not to want it. I recognize that there are often irresistible biological causes for some of these feelings; that not every want implies a conscious choice. I recognize that for many, having these feelings to deal with in one way or another is a huge burden, and that they would prefer to simply not have the feelings rather than to act in some way to resolve them. The sentiment I mean to express here is merely this: whatever anyone decides is best for themselves, whatever their reasons behind that decision, whatever the causes of those reasons pertaining, I support their decision.</p>
					<p>I do not want "a cookie" or "brownie points" for any of this. I am not saying this to make myself out to be some kind of special great person deserving praise for being so inclusive and tolerant. I think this should be the sensible default position of every sane person and should not need saying at all. But unfortunately the world is full of crazy bigots who do not think so, and I want to make absolutely clear before I say anything else that I am not one of them. I say this only so that I do not get mistaken for one merely for disagreeing on the far more trivial linguistic and philosophical issues I wish ultimately to discuss.</p>
					<hr />
					<p>But before we get to those issues, let me now tell you a little about myself, again in overly verbose and hopefully neutral language to avoid prematurely raising the issues I am to discuss later. I want to be clear that I am not representing my experience as reflective of anyone else's; this is merely my own narrative.</p>
					<p>Mentally, I am highly androgynous with equal masculine and feminine streaks. This is according to two independent gender role tests taken in two separate classes on human sexuality (one psychology and one sociology), both of which scored several traits in three categories of masculine, feminine, and androgynous; both times I had nearly equal points in all three categories, with androgyny pulling ahead by a hair and masculinity and femininity equal. I do not myself see my personality so subdivided into such categories however, because I do not see personality traits and social roles as inherently appropriate for one sex or another. I see myself as merely a well-rounded person, unconfined by expectations of my sex.</p>
					<p>Physically, I was born with unambiguously male sexual anatomy. That's never bothered me enough to be worth changing, but I've never been especially attached to that fact, and I do not in any way define myself by it. Most people assume, unless I say otherwise, that I am heterosexual and cisgendered. That rarely bothers me enough to be worth correcting them, especially as the practical import of that assumption seems to be that I have male anatomy and am attracted to people with female anatomy; and that is true, but not the whole truth, so that assumption is strictly inaccurate.</p>
					<p>But I don't bother correcting people because, in almost every aspect of life, I am and have always been completely indifferent to what sex I am or what sex anyone else is. I do not mind when people assume I am anything, because I would not object to being anything, and I am not attached to being anything; and I do not look at other people and see them first and foremost as a member of their sex, or as potential sexual partners or competitors, but just as people who may as well be sexless for all I care. For the most part, sex and gender are irrelevant to me, and in that regard I might almost be considered agendered and asexual.</p>
					<p>I recognize that being able to disregard sex to this extent is largely a privilege of being of an advantaged sex myself; that if I were born female, many more people would make a much bigger deal out of what sex I was and I would not so easily be able to ignore it. However I do not accept that this makes such disregard for sex a bad thing, an oppressive attitude of an advantaged class; rather, it is an attitude which disadvantaged classes are wrongly robbed of, and which should be open to them as much as to the advantaged class.</p>
					<p>I consider it a positive attitude, to think of people as individual people first and not as a member of one sex or another, unless their sex is somehow relevant; and I am uncomfortable when someone else makes an irrelevant point of what sex I am or they are or someone else is, whether to compare or to contrast, to praise or condemn. In any case, it feels discriminatory and wrong, such as when a man assumes some sort of fraternity with me (in opposition to women) just because I am male and so is he, <em>or</em> when a woman assumes an antagonistic relationship to me (in unity with other women) just because I am male and she is female. Or when someone makes a loud point about how sexually attractive <em>or</em> unattractive another person of any sex is. Or when someone either lauds <em>or</em> criticizes anyone's behavior either for conforming to <em>or</em> for transgressing gender roles.</p>
					<p>As a child I often unknowingly and uncaringly transgressed traditional gender roles, got mocked for it, and just thought the other kids stupid for adhering to such arbitrary social conventions. Sometimes I was mistaken for a girl (easy to happen before puberty without the "right" gender performance), and I never cared unless someone made that out to be something bad. As an adult I am more aware of and more acquiescent toward gender role expectations, but when I do feel free to transgress them I have occasionally been mistaken for a woman (much to my surprise as I don't think I pass well at all) and felt perfectly fine about that, a little pleased even at being able to transcend gender lines like that. I have even occasionally confused my own pronouns, not to make a point of performing any gender, but just because I wasn't paying attention to consistently marking my own in my speech, and absent-mindedly continued using the gender of my interlocutor.</p>
					<p>When I <em>am</em> thinking in a sexual context, however, I find the ideas of both being with and <em>being</em> a person of any sex appealing in its own right, and as this is the only context in which sex matters to me at all, I find my true gender identity and sexual orientation here.</p>
					<p>I find both male and female sexual characteristics attractive, both in their usual binary configurations, but especially in combinations of both binary sexes, e.g. I find femininity (such as sleek figures and little body hair) attractive in men, and masculinity (such as height and strength) attractive in women, and the concept of a person embodying all that I find attractive about men and women both in one body the ideal fantasy. (I mention only physical characteristics here because, again, I do not consider personality traits to be the exclusive domain of any one sex, e.g. logic is not the exclusive domain of men and emotions are not the exclusive domain of women, both rightly belong to anyone of any sex; and I expect anyone of interest to me of any sex to be a well-rounded person in that regard).</p>
					<p>And I find the thought of myself in a body I would find attractive, of any sex, both arousing and also empowering, whether directing my attention to attractive features of the body I have, or imagining different ones. By "empowering" I mean emotionally satisfying in more than merely a sexual way, the same way that good grades in school, a good review at work, earning a lot of money, or creating something masterful are: it makes me feel like someone I can feel proud to be. And that feeling of pride, worth, and empowerment seems to underlie my sexual arousal; it makes me feel sexy, attractive, beautiful. The ideal body I would most like to have, the one which makes me feel the best in this way to imagine having, is one combining all the sexual characteristics I find most attractive: the smooth and sleek curves of a woman, with the height and strength of a man; the broad shoulders of a man, with the large breasts of a woman; and the long legs, round hips, and vulva of a woman, but with the penis of a man in place of a clitoris.</p>
					<p>While that would be my ideal if I had the free choice of body with no cost and risk to weigh against it, being an attractive ordinary man with no feminine features has also felt empowering like that, in times when I was satisfied with my figure; and being an attractive ordinary woman with no masculine features has become a similarly fulfilling fantasy. I have always identified with attractive characters both male and female since before even puberty; as a child I wanted to be a cowboy or a ninja, sure, but I also wanted to be Ariel the Little Mermaid, or Cheetara from Thundercats. Also since before puberty I found the idea of being able to switch between sexes fascinating, and that continues to this day. I'm not only <em>comfortable</em> with the thought of being any sex, but being either binary sex is <em>appealing</em> in its own way, and being a combination of the best of both even more so. Thus I call myself, in the terms already well-known in the queer community, pangendered and pansexual.</p>
					<p>The combination of this with being able to tacitly pass as a heterosexual cisgendered man presents challenges of its own in integrating with mainstream queer communities. It seems there are several hierarchies of gender-related privilege: men are privileged over women, heterosexuals are privileged over homosexuals, cis are privileged over trans, and all are privileged over those who don't fit neatly on either side of their respective divides; plus the the disadvantaged side of each divide is often hostile to the disadvantaged side of other divides for in one way or another diluting or appropriating their struggle. If I keep my mouth shut, everyone assumes I'm a heterosexual cisgendered man, and I get to enjoy maximal privilege. But as soon as I open my mouth and reveal I'm a pangendered pansexual who would prefer to be an idealized true hermaphrodite, not only do the bulk of all the privileged groups look down on me for revealing my nonconformity to them, but many in all the disadvantaged groups look down on me not only for blurring the lines, appropriating part of their identity while maintaining part of my privilege, but also for diluting their cause by mixing it up with the causes of all the other disadvantaged groups. So I feel stuck keeping my mouth shut and allowing people to believe I'm just another heterosexual cisgendered man, lest I have not only many real hetero cis men attacking me for being a freak, but also some feminists, gays, and transwomen all attacking me for somehow hurting their causes by my existence.</p>
					<hr />
					<p>I have been describing my sexual orientation along with my gender identity thus far not because I conflate the two, but because I want to make an analogy between them, which leads into the actual topic of this essay. That analogy is this: I see myself compared to a trans person as a pansexual is to a gay person.</p>
					<p>So far so good, perhaps, but the problem is here: in the concepts in which I think of myself, I am "a man, who is comfortable as a man, and would be comfortable as a woman; who sometimes likes being a man, and would like sometimes to be a woman". In those terms, someone otherwise just like me who, unlike me, was not comfortable with the idea of being female, who would normally be described as a cisman, would be "a man, who is comfortable as a man, but would not be comfortable as a woman; who likes being a man, and would not like to be a woman". And &ndash; here is the hot-button issue &ndash; someone otherwise just like me who, unlike me, was not comfortable with being male, who would normally be describes as a transwoman, would be "a man, who is not comfortable as a man, but would be comfortable as a woman; who dislikes being a man, and would like to be a woman instead". You see the problem.</p>
					<p>In short, in describing myself in the terms in which I think of myself, and comparing myself to cis and trans people on a spectrum of gender identities, I run afoul of the received terminology used within the trans community, which tends to get me automatically pigeonholed as an insensitive bigot and shuts off any opportunity to discuss gender issues with the people I would hope would be the most understanding, with whom I want to sympathize and share. The purpose of this essay, after establishing all the above, is to defend the conceptual framework and associated terminology with which I think of myself, arguing not only that it is the more linguistically accurate and philosophically rigorous terminology to use, but also that even if it is not some people's preferred terminology for themselves, it should not be offensive that I use it, any more than I should be offended at the use of the received terminology; and that the imposition of the received framework and terminology on me is itself as offensive as what it is claimed I am doing.</p>
					<hr />
					<p>The point of contention is effectively that of what the proper referents of the terms "man" and "woman" are.</p>
					<p>The root of my objection to the received terminology has nothing to do with gender identity issues, but rather is a much wider-reaching ontological point, which I will state here but not argue for per se in this essay: indicative terms derive their meaning from the observable features they describe, and consequently, if a term "X" means only "those who are called X" or "those who call themselves X", then the meaning of "X" swirls away to nothing in a circular reference. In other words, socially constructed properties are not real properties; someone being called or calling themselves something does not make them that, and if it could, it would make that apellation completely meaningless.</p>
					<p>I acknowledge that there are real facts about the kinds of categories society <em>tries</em> to put people into, and those are important to recognize for practical purposes; but social belief in said categories does not make them actually exist. Whatever categories there are for people to fit into, their lines are drawn by the kinds of objective features people really have, to which we can assign meaningful names; but a name which means only "is called [that name]" means nothing. It may be practically important to be wary of who gets called "foo" by whom, but if you asked what it meant to be <i>foo</i> and I replied "it is to call yourself 'foo'", would you feel at all enlightened on the subject?</p>
					<p>The concept of gender used today was initially coined in a socially constructive way like this, and the terms "man" and "woman" reassigned in that framework from naming anatomical categories to naming socially constructed categories. While the initial purpose behind this was noble &ndash; to make conceptual room for non-binary sexes, by abstracting the binary categorization away from sex itself &ndash; I think it was a philosophically flawed move, and that that purpose would have been better served by leaving "man" and "woman" as anatomical categories, and admitting that those categories are either not mutually exhaustive or not mutually exclusive; that someone could be neither man nor women, or both man and woman, depending on how we wanted to refine those concepts.</p>
					<p>The usual objection here from defenders of the received framework is that gender identity is not a socially constructed property at all, but rather an objective biological fact of brain anatomy. I want to acknowledge here that I am well aware of the brain anatomy differences statistically common between cis and trans populations and I don't contest those facts. However, I do contest the claim that the proper referent of "man" is "person with male-typical brain anatomy" and likewise that that of "woman" is "person with female-typical brain anatomy".</p>
					<p>The first reason I do so is epistemological: in the vast majority of cases, we do not ever learn anything about a person's brain anatomy, and in the minority of cases we do, it's not until after they are dead and we can examine their brains safely. The second reason however is more compassionate: in some of the minority of cases where we do learn about someone's brain anatomy, it may not exhibit the anomalous differences. Between these two factors, if we meant to indicate brain anatomy by the terms "man" and "woman", we would have to say we had no idea whether most people were men or women, only found out about a few of them after they died, and occasionally found out that some of <em>them</em> were completely wrong about what sex they thought they were! And if we developed the technology to scan such brain anatomy while people were alive, we would sometimes be faced with the uncomfortable prospect of telling someone that they aren't really the sex they and everyone else thought they were.</p>
					<p>That raises complicating issues about how to categorize people with anomalous genetic or hormonal conditions as well, who have nevertheless lived their entire lives apparently unambiguously one binary sex or the other. By the same argument defenders of the received framework make about brain sex, one could argue that genetic sex is the proper referent of the terms "man" and "woman", and that a person with unambiguously female anatomy her entire life, who identifies as and is accepted as a woman, discovered to have XY chromosomes and androgen insensitivity syndrome, should be told that she is "really" a man. Note well that I am <em>not</em> making that argument, but rather pointing out the absurdity of it, and by comparison the absurdity of identifying sex with brain anatomy.</p>
					<p>I contend that the obvious, common understanding of "man" and "woman" as referring primarily to genitalia (and secondarily to other sexually dimorphic external anatomy such as fat and hair distribution) remains the linguistically correct understanding &ndash; the one the general speech community will understand and intend, and the one that tracks with historical usage &ndash; and that the terms were only recently transferred from those referents by way of the philosophically bankrupt concept of a socially-constructed property of "gender" distinct from "sex".</p>
					<p>I fully acknowledge, mind you, that even primary and secondary sexual characteristics do not fall neatly into the binary categories of "man" and "woman", and that it is an injustice for doctors or parents to choose the category into which someone should be forced when there is any question about it. My contention is that these two terms refer strictly to the cases where there is not any question, when primary and secondary sexual characteristics align neatly into the two widely-recognized categories. I support an expansion of the language to coin terms to acknowledge and refer to people who do not fit neatly into one of those two categories, which eliminates the need to abstract socially-constructed "gender" away from physical sex.</p>
					<hr />
					<p>The model of sex and sexuality I propose is one based on a multidimensional spectrum of external, anatomic sex; not genetics or other internal features that can only be discovered by advanced medical testing, but the ordinary features that any untrained person can see when looking at a person's body.</p>
					<figure>
						<picture>
							<source srcset="reconstructinggender.svg">
							<source srcset="reconstructinggender.png">
							<img src="reconstructinggender.jpg" alt="Two-dimensional spectrum of sexes" />
						</picture>
					</figure>
					<p>For a start, we can imagine a two-dimensional spectrum, with one axis indicating conformity to typical male anatomy, and another indicating conformity to typical female anatomy; the majority of unambiguous males and females would be found clustered near two opposite corners, and people with ambiguous or mixed sexual anatomy due either to birth conditions or later modifications would be found scattered around other parts of the spectrum. This spectrum is merely a first pass at modeling a diverse and non-binary assortment of anatomic sexes; I am open to suggested modifications.</p>
					<p>Whatever our spectrum of non-binary, inclusive, but external, anatomic sex, any person could identify three points on this spectrum: their location on it at birth (their natal or birth sex), the location on it they would prefer to occupy (their intended or target sex, or their "bearing", the meaning of the root "-phor" in "dysphoria" or "euphoria", and a navigational analogy alongside "orientation"), and their present location along the vector between them (their somatic or body sex). Those with coincident natal and intended sex would be those who are typically called "cisgendered"; I would instead have them called "cisphoric", "bearing to the same side" as they were born. Those with natal and intended sexes on "opposite" sides of the spectrum would be those who are typically called "transgendered"; I would have them instead called "transphoric", "bearing to the opposite side" as they were born; and in that case, the location of the second point (somatic sex) corresponds to various stages of transition.</p>
					<p>Other gender identities not neatly categorized as trans or cis can also be thus modelled, but to label them we will need terms which do not assume binary sexes. If we use the usual prefixes "andro-" and "gyno-" to refer to the binary sexes, "neutro-" to refer to the lack of distinctive features of either sex, and "ambi-" to refer to a combination of the distinctive features of both sexes, we can then use terms such as "androsomatic" to mean "male-bodied", "ambinatal" to mean "intersex-born", and "gynophoric" to mean "female-bearing", in the sense of "headed toward, or intending to be, female", what would typically be called a "female gender identity".</p>
					<p>If we expand the model further, allowing vector maps instead of merely single points to describe intended sex, we can introduce the prefixes "bi-", "pan-", and "a-" to refer to having an intended sex (i.e. a bearing) split between the binary genders, spread across the entire spectrum, or absent from the entire spectrum, respectively; someone who would want sometimes to be either or both sexes, someone who wants sometimes to be any and all sexes, and someone who doesn't particularly want to be any one sex or another. If we allow the earlier prefixes to precede these, we even can allow for convenient labeling of uneven distribution of preference, e.g. a gynobiphoric person would be someone with some interest in being male and some interest in being female, who would pick female if they had to choose.</p>
					<p>Lastly, "trans-" and "cis-" prefixes can remain to indicate relations between one value and another that cross the binary divide, e.g. a transphoric person wants to be a sex other than they are or were born as, a transsomatic person has a different sex than they were born as or want, and a transnatal person was born as a different sex than they are or want to be (thus all corresponding to the existing sense of "transgendered").</p>
					<p>(This model can also be easily expanded to cover sexual orientation as well, by combining all the preceding prefixes with the suffix "-philic", e.g. an ambipanphilic person would be attracted somewhat to all sexes but with a preference for people mixing male and female characteristics. "Hetero-" and "homo-" prefixes can similarly be retained to indicate orientations that cross the binary divide, e.g. a heterophilic person is attracted to people of a different sex than they are, and a homophilic person is attracted to people of the same sex as they are).</p>
					<p>My argument about the use of the terms "man" and "woman" can then be described in this model as an argument than "man" means "androsomatic", not "androphoric"; and likewise "woman" means "gynosomatic", not "gynophoric". In more familiar terms, a man is merely someone who is male-bodied, and a woman is merely someone who is female-bodied. And to argue this is not to argue that anyone should stick with the body they have or that there is anything wrong with doing otherwise, it's merely to argue that the words properly refer to whatever body you have at the moment; that it is more than fine for a man to become a woman or vice versa, but until they have done so, they are still whatever they were before.</p>
					<hr />
					<p>Words by themselves are mere envelopes which transport meaning from one mind to another, and it is the meaning they carry which is the proper object of offense, not the words themselves. We must first understand what someone is saying, not just what we hear them say, before knowing if they have said anything offensive. Any other standard of offense would justify anyone taking free offense at anything anyone ever said based solely on the interpretation of the listener, completely beyond the speaker's control; or equivalently, leave people open to blame and condemnation merely for being misunderstood. Hate and discrimination may "break our bones", as it were, but words <em>qua</em> words can never hurt anybody.</p>
					<p>To call a male-bodied person who intends to have a female body "a man who wants to be a woman", rather than "a woman with a man's body", is not necessarily to dismiss anything about that person's experiences or their rights to be or become anyone they choose to, any more than saying that although I am male-bodied I am "not a man" because I am not cisgendered is necessarily offensive to me in any way. If someone meant to impugn me by that comment, I would be offended, and rightly so; if they were suggesting that my comfort and interest in being other than male-bodied was a flaw, that someone of my sex should not have such feelings, was perverted or deviant, and somehow a defective member of my sex because of it (and thus "not a man" in that sense), I would be very offended, with justification. Likewise, if someone were to say of (in my above terminology) a gynophoric andronatal person that they were "just a man who wants to be a woman" with intent to imply the same sort of things &ndash; that that is some kind of character flaw, a mere perversion or deviance &ndash; and in doing so dismissing the substantial rights and significant experiences of that person, then that would very much be something to take righteous offense to.</p>
					<p>But if merely using my terminology and its implicit framework to discuss issues of gender identity were to be grounds for offense, then the use of the received terminology and framework should be grounds for me to take offense as well. After all, if what I'd call a "gynophoric" (or in more familiar terms, "transgendered") male (i.e. a transwoman) can be offended at not being classified as a woman even though they call themselves one, then shouldn't I, who call myself a "ambipanphoric" (or in more familiar terms, "pangendered") man, be offended at not being classified as a man? But if we do that, we will never be able to speak to each other civilly unless one side is forced to abandon the conceptual framework they find most legitimate. And that, I believe, is a greater offense still: to force someone to think in your terms. To argue for one's terms is surely fine &ndash; I'm doing it here, and I welcome counterargument &ndash; but to declare a priori that you get to define the terms of the discussion and that others are, as I have frequently seen declared, simply <em>not allowed</em> to say certain things, is a great intellectual offense.</p>
					<p>Much better, I think, to accept that people think in different terms than ourselves, let them speak in their language, learn to understand what they mean, and translate as necessary into our own frameworks as we listen; and depending on our audiences, translate our thoughts into their framework if they don't speak our language. E.g. I know what someone means when they say "transwoman", even though I wouldn't have coined that term to mean what they mean; and I'll use it in contexts where that's the easiest way to be understood, without explaining the framework in which I'm natively thinking. And just as I don't find it offensive to use the terminology of a framework I don't agree with which would label me something other than I label myself, I contend that there are no grounds for anyone to be rightfully offended when I use the terminology of my framework, just because they disagree with that framework and label themselves something other than it would.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
