<section>

	<h2>Hard Work Doesn't Pay</h2>

	<p class="description">An analogy between business and romance, 2014.</p>

	<p>Imagine a young woman fresh from college, just beginning her career. She is a dedicated hard worker in everything that she does, for money or otherwise. Even if she's doing something for reasons other than money, if she's going to do something at all, she cares about doing it right, just for the sake of it being right.</p>
	<p>But she would also like money for its own sake. Thankfully, society tells her, people who work hard and care about getting things done right are exactly the kind of people who also make good money, because those are the kind of people who can make good money for the employers who in turn are in a position to provide the hard workers with money, in a mutually beneficial relationship. So she dives headlong into her career thinking that her natural positive qualities will take her far.</p>
	<p>After years of this, however, she repeatedly sees new people hired from outside her place of work into openings above her, instead of dedicated employees like her being promoted. And the few internal employees who <em>do</em> get promoted are the weasels who kiss upper management's asses and schmooze.</p>
	<p>Meanwhile the management (like society in general) continues to tell her "just keep being yourself, keep working hard for its own sake, and eventually you'll get promoted... by someone, somewhere, I'm sure, but there's no room for promotions here right now. Now excuse me, I need to go hire one of my golf buddies for a newly-created high-paying busywork position."</p>
	<p>Eventually, she gets sick of this, and starts complaining about the injustice of the business world, and that the whole "hard work pays off" spiel is a total lie. She vocally complains that bosses hire unqualified shits for cushy positions just because they sweet talked them at some expensive party somewhere, and meanwhile shit on and take advantage of the people who would really shine if they were just given a chance.</p>
	<p>In response to this complaint, pro-business advocacy groups everywhere start shouting at her angrily that nobody <em>owes</em> her a job <em>at all</em>, employment is <em>voluntary</em> and anything else would be <em>slavery</em> of the business-owners, and she should be happy with <em>any</em> employment she gets, even if it's just an unpaid internship. And if the only reason she works so damn hard is to get paid well, they say, then she's <em>not</em> really the kind of dedicated hard-worker who likes to do things right for the sake of them being done right that she claims to be in the first place.</p>

	<hr />

	<p>This story is an analogy for a pattern I observe between other people in another aspect of life: romance. The analogy is this: the hard worker is analogous to the nice guy, a person with good qualities honestly expressed for their own sake; the money is analogous to sex, something else that is desirable for its own sake, for both parties in question; the businesses are analogous to women, a possible source of the desirable thing for the person with the good qualities (who, in turn, see the other party as a source of that themselves); the message society tells about hard workers going far and fast in business is analogous to the message society tells about nice guys going far and fast in romance; the "weasels" getting promoted over the hard workers are analogous to "jerks" being preferred over the nice guys; and the pro-business groups calling complaints about that business phenomenon tantamount to a desire to enslave are analogous to radical feminists calling complaints about that romantic phenomenon tantamount to a desire to rape.</p>
	<p>I want to be very clear that I am not portraying "niceness for sex" as a business transaction identical to "work for money", but rather making an analogy between a career relationship between an employee and employer, and a romantic relationship between a man and a woman. And that this analogy is limited only to when the power relationship favors the latter party in each pair; and that that is not always the case. Some employers have trouble finding good employees, and some employees have no trouble finding good employers; likewise some women have trouble finding good men, and some men have no trouble finding good women. But the "nice guys" being demonized by some feminists are guys who <em>do</em> have trouble finding any women, and so are in an analogous position to many employees who have trouble finding any employers; and from there the situation is analogous.</p>
	<p>The "nice guys" are saying "I'm nice for the sake of being nice. I also want to get sex. I don't think anyone <em>owes</em> me sex for any reason, and I don't want or intend to rape anyone, far from it. But I'm told, and it sounds reasonable, that guys who are nice for the sake of being nice are the kind of guys that girls want to have sex with. Yet that apparently isn't true in my experience, and that is very frustrating and seems unfair." But instead, they are being portrayed as "You think anyone <em>owes you</em> sex? You're no better than a rapist! And if you're only being nice to get sex, then you're hardly 'nice' at all!" Which is just as ludicrous a response as portraying complaints about underpayment in business as calls for enslavement of employers.</p>
	<p>Of course nobody is entitled to either money or sex, and if they were that would be tantamount to slavery and rape respectively. But for someone to complain that they aren't getting one or the other is not the same as claiming to be entitled to it. It's just a complaint, the venting of bad feelings about a frustrating situation, compounded by the collapse of a socially built-up expectation that that situation defies. And until they go so far as to act as though they are entitled, and try to take what they are not in fact entitled to, then such frustrated people deserve our sympathy, not demonization. Sympathy doesn't mean giving them what they're longing for. It just means understanding that, yeah, it sucks not to have that, that life is not as sweet as it is said to be, and good people can get shat upon by bad or simply callous people, and that sucks and it'd be nice if they didn't do that. And that though they may need to learn how better to overcome the challenges posed by life being the way it is like that, if they want to succeed in their endeavors despite that, that the good qualities they're told it's desirable to have <em>are</em> in fact still desirable, even if they're not sufficient; and that they shouldn't throw those qualities away to become the "jerk" or "weasel" merely scamming their way to what they want, even if those people are more successful in their respective endeavors. It may be tricky to pull off, but nice guys don't have to finish last; and sometimes, hard work does pay.</p>

</section>