<section>

	<h2>A Survey of Anthropological Dichotomies</h2>

	<p class="description">A paper for a class on Cultural Anthropology, 2006.</p>

	<p>In this essay I intend to survey and outline in an organized fashion a number of different aspects of anthropological theory and ethnographic writing. Within each section I will lay out the opposing approaches toward that aspect of anthropology, presenting for each a summarized argument of one anthropologist, arguing for the inclusive consideration of one side of that particular dichotomy (whereas the opposing side was taken for granted by his predecessors). </p>
	<p>Four aspects will be covered, each segueing into the next, oscillating between the respective sides of the overarching dichotomy common to them all. As these arguments swing back and forth across the chasm which separates the opposing sides, I feel that a “spiral-shaped”, dialectic progress is made in our understanding of what constitutes well-done ethnographic writing and accurate anthropological theory, converging toward a balanced synthesis which acknowledges the cogent points of both sides of the argument. </p>
	<p>On the topic of social structure, I will examine the question of whether base or superstructure is the central feature of society; in other words, whether a society’s basic economic functions, or rather it’s ideology, is the proper focus of a theory of social structure, and likewise which derives from the other. Next, on the topic of ethnographic style, I will discuss the question of whether ethnographers ought to take a purely materialist, third-person, etic approach, or a more interpretivist, emic, 1st-person approach to the peoples they are writing about. After that, on the topic of scope, I will examine the question of whether it is appropriate to consider societies by themselves, in isolation, or whether it is necessary to consider them in their global context. Finally, I will look at whether such a global context is fixed, one-dimensional and unidirectional, true of the society in question in all way and at all times, or whether contextual position in global, historical society is a complex, multidimensional and multidirectional network of different relations which change dynamically over time. </p>
	<p>In covering all these broad topics, I do not claim to be presenting any particularly new or novel ideas, or even to giving a particularly thorough investigation of the arguments presented herein; this is only a broad survey of concepts. Even the ecumenical focus on balance and synthesis is not novel , as previous anthropologists have likewise advocated embracing both sides of these dichotomies to get a more complete picture. All I hope to accomplish is to present these concepts in a well-organized fashion, to make the dichotomies and their relationships clear, and thus make understanding of the need for balance more apparent to the reader. </p>
	<p>The first authors under examination are Karl Marx and Friedrich Engles. In academia during their time, social structures were seen largely in terms of ideologies, with various social institutions and processes coming into play on the basis of various (e.g. religious, philosophical, etc.) established beliefs in the society. Likewise, the evolution and change of social structures was seen solely in terms of the dialectic processes which influenced the evolution of those ideologies. </p>
	<p>To those with such a view, a society was feudal or capitalist, monarchial or democratic, or so forth, simply because the prevailing ideology of the people said that society should be structured that way. Thus those who held power did so, according to such a view, because the society believed that they rightly held that power. Such ideological effects then had assorted material effects on the well-being of the people, but these material considerations were not considered to be the cause of the social structure in the first place. </p>
	<p>In contrast, Marx and Engles wrote in The Communist Manifesto that the history of social evolution is that of economic class warfare, with material concerns being the primary motivating force for the establishment or change of social structures. They called these materialist concerns and the structures directly concerning them the “base”. The assorted religious, philosophical, and ideologically inspired institutions less directly connected to material concerns were defined as the “superstructure”. In contrast to the prevailing view at their time, this superstructure of belief systems and their associated institutions was not the impetus of social structure at all, but rather a mere effect of the structures that really mattered, the mode of production, and the ways of reinforcing and legitimating such modes of production. They saw historical societies evolving not through ideological stages like polytheism to monotheism, or monarchy to democracy, but rather in terms of the function of it’s economic relations: from primitive communism, to a system of slave labor, to the feudal system, to capitalism, and eventually back to an advanced form of communism. As such, in their view the material needs and means of meeting those needs overwhelmingly dominated any ideological concerns in the structuring of society. </p>
	<p>But while they may be right, that the ideological structure of a society is secondary to its material, functional structure, to focus solely on this aspect of society is to ignore the complex layers of meaning and ideology which build up around it. Materialist approaches take a scientific, purportedly objective approach to studying societies. That is to stay, the ethnographers who utilize such approaches study societies as external objects, from the third person perspective, in what is called an “etic” style, and their ethnographies are likewise written from this external perspective. But in the past few decades there has been a turn in ethnographic styles of writing to further incorporate more meaning-oriented, first-person approaches as well, to record the “what it’s like”, the subjective experience from within the society in question. Such interpretivist notions are discussed in James Clifford’s essay Introduction: Partial Truths. According to Clifford, ethnographies since the 1960s differ from earlier studies in that they do not purport to be objective, but instead admit to the subjective experiences of the ethnographer and the people being studied. New ethnographies speak in the first person and tell a story about the particular experiences of the ethnographers during their studies, rather than trying to portray cultures as they “really” are, as though from the viewpoint of some omniscient, objective, invisible observer. </p>
	<p>They thus record not only what the ethnographer’s take on that society is, as an outsider, but also include many of the direct impressions of that society from the very people under study.</p>
	<p>Clifford’s two examples, of James R. Walker’s ethnographies of the Lakota people, and Godfrey Lienhardt’s ethnographies of the Dinka people, illustrate the difference between new and old styles. Lienhardt showed the Dinka as some ahistorical ‘other’ society, where individuals he spoke to were merely ‘informants’ and their culture was shown to us only via his representation of those he spoke to, while ostensibly claiming to show their complete culture in an accurate and objective manner. Walker, on the other hand, collaborated with the Lakota to publish a collection of their own interpretations of their culture, himself serving more as editor and commentator of this compilation. This way more honestly shows the Lakota from the inside, and acknowledges the ethnographers’ opinions as just that – opinions. </p>
	<p>Hand in hand with recording the experiences of the local peoples must come reflexivity. </p>
	<p>According to the interpretivist view of authors such as Clifford, ethnographers must own up to their own biases in order to be more academically honest, separating their outside take on the society in question from the locals’ interpretations of their own culture. Ethnographers are not in some privileged position of objectivity from which to correctly describe the rest of the world. </p>
	<p>They cannot accurately represent a culture in it’s entirety while treating them as some alien and inferior “others”. To do so puts epistemological distance between us and them, and until we can accept their view of themselves on the same level ground as our view of them, to compare and contrast side by side, we cannot hope to truly understand them. Though an external, etic perspective is informative in the analysis of many aspects of a society, ethnographies also need an internal, or emic, component in order to be complete. </p>
	<p>Yet while this emic, interpretivist approach captures an element that is sorely lacking from Marxist, materialist, functional approaches, it runs the risk of narrowing the scope of investigation to an isolated “snapshot” of a culture as it exists then and there at the time of the research, ignoring the relationship that that culture has both to history and to other cultures around the world. In The Rise and Future Demise of the World Capitalist System: Concepts for Comparative Analysis, Immanuel Wallerstein critiques social sciences which focus solely on isolated societies, particularly nation-states; the kind of analyses which take each civilization or society as an isolated unit devoid of any outside interaction. At least two important things are left out of such analyses. One is the historical influence that cultures have had on one another, how each society inherits some aspects of it’s culture from earlier societies in the world, similar to how individuals inherit much of their character traits from the greater societies in which they live. Neither individuals nor societies develop in isolation. Another important factor which more isolated analyses overlook is the influence of contemporary societies on each other, and the interactions between them in a single world system. We can no more look at the social and economic activities of a society apart from the world system in which it functions than we can examine the socioeconomic activities of individuals apart from the societies which envelop them. </p>
	<p>In Wallerstein’s view of world political economy, there are three relational or structural positions which a society can occupy: “core”, “semi-periphery” and “periphery”. The cores are those with the most efficient economic systems and greatest access to natural resources, and thus the greatest economic power. They spread their dominance and influence through military might at first, seeking out new sources of cheap capital and labor from the societies which form the periphery. They then, to use Marxist terms, spread an ideology of capitalist potential which creates a socioeconomic dependency between the periphery and core, as the periphery supports the very system which keeps them marginalized and exploited, in the hope that they might someday become core societies. Thus as labor and resources flow from periphery to core, so too the core’s culture flows, along with their salable finished goods, to the periphery. Finally the third position, the “semi-periphery”, is a sort of world-system equivalent of the middle class, which acts as a periphery to the core, but a core to the periphery. Thus the semi-periphery serves to keep the hope of ascending the world-system’s social ladder alive in the peripheral cultures, and so perpetuates the core’s capitalist ideology and the core-periphery relationship.</p>
	<p>But is the world system really such a harsh, dominant and hegemonic process of the economically powerful trotting over the weak, who haplessly support the system of their own oppression in the hope of one day becoming the oppressor? Or is it in truth more a more diverse and multilateral, multidimensional network of relationships, where – while domination may be a factor in places – the system also presents true opportunities for what Wallerstein would consider peripheral societies to benefit? In Notes On The Global Ecumene, Ulf Hannerz presents a conception of the world-system (or the “global ecumene” as he calls it) which differs from Wallerstein’s view in several ways. For one, Wallerstein focuses almost completely on one type of relationship between societies, a materialist economic relationship, thinking in Marxist terms of the periphery as akin to the proletariat, and the core as akin to the bourgeoisie. Hannerz on the other hand focuses on a more diverse set of cultural relationships – political, economic, artistic, academic, ideological, etc. – with multiple cores possible in each type of relationship. </p>
	<p>The other major difference between Wallerstein and Hannerz is that Wallerstein sees the flow of power and benefit as unidirectional, with the core acquiring raw capital and labor from the periphery and giving nothing back to the periphery but the ideology and cultural standards which perpetuate that relationship. Hannerz, meanwhile, sees the flow as omnidirectional, by virtue of the diverse set of different relationships between societies. The cores not only forcibly export their culture and ideology, but at the same time they absorb new and interesting pieces of culture from the periphery – art and music styles, for example – and integrate them, being reshaped by them, and dispersing them across the global ecumene. Academic discourse may likewise transcend political and economic power relations, and new ideas can spread out from societies which are socioeconomically peripheral. For this reason Hannerz thinks we should not be alarmist about the homogenization of culture, for even while this global ecumene moves toward an international world culture, it also preserves unique local cultures as subcultural trends within itself, amplifying them and spreading them throughout the rest of the world.</p>
	<p><strong>Bibliography: </strong></p>
	<ul>
		<li>Clifford, James (1986) “Introduction: Partial Truths” in Writing Culture: The Poetics and Politics of Ethnography, Clifford, James and George E. Marcus eds. Berkeley: University of California Press. Pp. 1-26. </li>
		<li>Hannerz, Ulf (2002) [1989] “Notes on the Global Ecumene” in The Anthropology of Globalization: A Reader, India, Jonathan Xavier and Renato Rosaldo, eds. Malder, MA:  Blackwell Publishers. Pp. 37-45. </li>
		<li>Lemert, Charles ed (1999) “Class Struggle – Karl Marx and Friedrich Engels (1948)” [excerpt from The Communist Manifesto] in Social Theory: The Multicultural and Classic Readings. Boulder: Westview Press. Pp. 37-41. </li>
		<li>Wallerstein, Immanuel (1979) “The Rise and Future Demise of the World Capitalist System: Concepts for Comparative Analysis” in The Capitalist World Economy. Cambridge: Cambridge University Press. Pp. 1-35.</li>
	</ul>

</section>