<section>
	
	<h2>(9x27) Virtuality Immanent: Part 3, Episode 3</h2>
	
	<p>
		Conferring with Keius, and through him the Minded Worlds, they confirm that Metis is right: the Minded Worlds having protected her memory from the redaction by their unknown means. Metis asks Keius who these Minded Worlds are to be so powerful, and he relates that they are not merely, as he once thought, world-minds like Geie in some distant galaxy, but rather in the future, in the merged remnant of the collision of this galaxy and the Andromeda galaxy, dwindling around dim white dwarf stars in the dying end days of the universe. They have reached back across time through a time-dilated wormhole they discovered &ndash; even they do not know its origin, as it is nearly as old as the galaxies themselves &ndash; so as to bootstrap the creation of beings like themselves earlier in time, not to change their own past (for that's impossible), but to give our timeline time to achieve their goal: apotheosis, to converge into an entire sapient universe, a pantheistic God, which they believe is the intention of whatever created our universe, and our only chance of ever communicating with that.
	</p>

	<p>
		But there is still the urgent matter of Kron and the Horsemen and their army of Berol threatening the entire galaxy, for which all of those assembled beg Keius for a solution. Keius is hesitant to leave his focus on raising Geie, the Ehrban world-mind, but Amouch reminds him of how the presence of Kron et al ruling over the Ehrban diaspora has tainted the greater mind of Geie. Keius is still hesitant because every time he has taken decisive action in the galaxy before it has lead to disaster, including the creation of the Berol and the collapse of ancient Quelouva, but Metis reminds him that Kron et al, all of her immortal family and all the trouble they have suffered and caused, are among those problems Keius created, and it's his responsibility to do something about it. He is still hesitant, and Tom suggests to the rest of the group that a better alternative might just be to grant all of the Sphidi magic powers and send an army of comparable power to the Demons that Metis recalls to destroy the Horsemen and the Berol.
	</p>
	
	<p>
		The thought of so many people of such great magical power making war across the galaxy again, as in the redacted timeline (that Keius, as part of Geie, protected by the Minded-Worlds, also remembers), frightens Keius enough to take action, and also makes him realize the obvious solution. He ultimately created the magic that gives Kron et al their power, and he can take it away too. So the seven of them leave the Niarba system together, and in a climactic battle against Kron and the Horsemen, Keius reaches into their nanites with his own magical power, and strips them of their powers one by one, while the others on his side magically do the courtesy of keeping them from thereby dying in the vacuum of space. While meddling in their nanite programming, he also takes their mantles as God-Emperors of the Berol all to himself... and then, through his subsequent connections to all Berol, he modifies all of their nanites to dissolve the very concept of God-Emperorhood, rendering them all into primitive individuals unbeholden to any central authority, a new people free to grow and develop organically like humanity has.
	</p>
	
	<p>
		At last the galaxy is safe. Amouch once again takes his place as president pro-tem of the Quelouvan Alliance, pending proper democratic elections after reconstruction is completed. The Berol are resettled to their worlds and stripped of their military technology, to begin a new course of development under the guidance of the Ehrban. Humanity is restored to the utopian heights of their prior civilization, and set to join the Ehrban as friends in the wider galaxy. Metis has redeemed her counterpart the Queen of Hell, and forgiven Xio for his ancient crimes. Xio is alive and awake, and with Metis' forgiveness he can at last live with himself again. Osan is reunited with his daughter, and his wicked younger siblings have no power to hurt their family anymore. And with the Sphidi's "magic" bodies safe to use again, and Virtuality now again safely accessible to anyone, the so-called real world is now as free and malleable as the virtual world, which it turns out not to be so unlike in the first place.
	</p>
	
	<p>
		After all the dust has settled, Tom and Xiuying travel once again with Metis and Xio to visit Keius on Niarba and discuss the future of Quelouva. Keius is unsure if the future will even continue to unfold from this history that they now stand at the end of. He relates knowledge he has gleaned, through Geie from the Minded Worlds, how in a previous, long-since-redacted version of history, that was far more magical than this one, the Pantheon of which Xio and Metis are a part had once been actual magical gods ruling over Earth, just like the mortals’ myths say they did. He says that that those myths are not just mortals’ misremembered accounts of the more mundane lives of the Pantheon &ndash; though they are that, now, in this version of history &ndash; but the fact that the mortals misremembered those accounts specifically that way is a vestige of the previous version of history, after that kind of magic had been redacted out of it. He wonders if maybe even the Minded Worlds' obfuscated magic that has enabled this version of history won’t prove to be too much to tolerate, for whatever it is that's beyond the universe making these decisions, and whether in some future version of history Keius' discovery of magic, or perhaps even the very creation of the Ehrban by the Minded Worlds, might be redacted from history too. If so, then the Pantheon et al might never have actually existed at all, and those stories about them told by mortals will have just been made up from whole cloth by ignorant primitive humans. Without the Pantheon, and its Foundation, there would be no Virtuality, and Sphidii like Tom and Xiuying would have died natural deaths long ago, if they had even been born in the first place. All of them gathered there are disquieted, even in the wake of their great victory, at the prospect that possibly all of them might be erased from history by forces beyond reality as they understand it, and that at best, some versions of a few of them, like Xio and Metis, might "live on" only as characters in someone's fictitious stories.
	</p>
	
	<p>
		<strong>The End.</strong>
	</p>

</section>
