<section>

	<h2>Teachings of Jesus</h2>

	<p class="description">A paper for a class on Early Christian History, 2006.</p>

	<p>In his book “Living Buddha, Living Christ”, the Buddhist monk Thich Nhat Hahn presents an image of Christianity and of Jesus far different from that understood by mainstream Christians across America. He approaches both Jesus and Christianity from a distinctly Buddhist point of view, and paints a favorable picture of both Jesus the man and his living teachings with an uncommon emphasis on the aspects which the Christian faith shares with Thich’s own Buddhist tradition. The resulting image is one which seems, to me at least, far more approachable to a person who is not already wrapped up in the details of the Christian faith or other similar theistic traditions. As Buddhism does not hold central to its beliefs and practices the notion of an entity like God, but adhering to its tenets does not prohibit belief in such a being, Thich’s approach presents an image of God and of the tenets of the Christian tradition that I feel any open-minded and spiritually inclined person, even one strictly averse to any appeal to the supernatural (such as myself), could willingly accept and easily understand. </p>
	<p>Thich interprets the historical figure of Jesus as a special and unique individual, as do mainstream Christians around the world; but Thich means this only in the sense that we are all special and unique. No person is entirely like any other person, and so no person on Earth is, was, or ever will be like Jesus. Along with this understanding of uniqueness, however, comes the obvious truth that while no two individuals are exactly alike, people can still be said to be similar to one another, and in this sense Thich holds that while Jesus was indeed a rare and special sort of person, he is not entirely unique in all of the respects which make him such a special individual. </p>
	<p>As the Son of God, which mainstream Christians often emphasize as the central unique aspect of Jesus, Thich holds that we are all the children of God, and thus while Jesus is indeed the Son of God, he is not alone in that position. (Thich p.xxiii, quoting Thomas 3). But Thich believes that Jesus a more special and rare individual in that he was a great spiritual teacher, one of the greatest who has ever lived; but not the only great teacher of spiritual truths. Like Jesus, other people have lived exemplary lives and taught people the way to the Kingdom of God, or to enlightenment — in particular, Siddhartha Gautama, the Buddha, whose teachings founded Thich’s own tradition, but also other religious and philosophical teachers. (Thich p.xxi). </p>
	<p>Thus Thich sees Christ as a religious figure in the same way that Buddhists of his kind see the Buddha. He sees Christ as a figure who taught through his practice, by the example of his very life, and as such, as long as people continue to practice and live according to the way of the Christ, so Jesus continues to live on in our hearts. In this sense Jesus is identified not with some metaphysical entity continuing to exist somewhere out there, but rather as the manifestation of the divine law which he taught by example of his life. Thus so long as adherence to that law lives within us, so does Jesus himself. (Thich p.70). (To me, this seems remarkably similar to the identification of Jesus with the Word of God, or logos, in John 1:1). </p>
	<p>Thich’s understanding of Jesus, wherein the teachings are embodied in the life, is a distinctively Third Quest approach, and goes perhaps even further than the Third Quest into an entirely new way of looking at Jesus. In the Old Quest, to understand Jesus scholars sought to understand the historical life of Jesus, establishing an accurate chronology of events and as detailed a biography as possible given our limited sources. The subsequent New Quest sought rather to understand Jesus in terms of the so-called “Christ of Faith”, the teachings or doctrine that Jesus handed down to his disciples, who in turn passed it down through the church and recorded it in the Gospels. The present Third Quest approaches the questions of Jesus’ life and his teachings as one, emphasizing that the teachings of Jesus come from the context of his life. </p>
	<p>The Third Quest approach understands that to to better understand Jesus’ teachings — which, as with the New Quest, is the goal of the Third Quest — we must understand as well as possible the context in which they were taught; that is to say, we must understand Jesus’ life. </p>
	<p>Thich’s approach goes beyond even this inasmuch as, as I have already stated, he sees the primary teaching of Jesus as Jesus’ very life itself, and not in the written gospels and other doctrine built up by the church since its inception. Thus, to truly understand the teachings of Jesus, we must understand the life and actions of Jesus in their context. By thoroughly understanding the reasons for the choices Jesus made and the actions he undertook in the situations with which he was faced, we can come to understand the true nature of his impeccable character. In so understanding Jesus’ character, so too can we strive to emulate him in the practice of our own lives, and in doing so, we will have truly learned the lessons that Jesus has given us. </p>
	<p>As to the actual teachings of Jesus, Thich again sees many similarities to Buddhism. </p>
	<p>Thich emphasizes that the Kingdom of Heaven is immanent, present here and now and just waiting to be discovered, and not something far out in space or in the distant future. This is something of particular importance in Thich’s type of Buddhist practice. Much emphasis is placed on being aware and in the present moment, not regretting the past or anticipating the future. Instead, the practitioner is urged to, as author Baba Ram Dass once popularized in the title of his book, “Be Here Now”. If we can successfully do this, and absolve ourselves of all desires, regrets, and expectations, then we will have already attained heaven on Earth. Thich himself urges us to “be in the present moment, to be aware that we are here and now, that the only moment to be alive is the present moment.” (Thich p.17). </p>
	<p>Also of particular note is Jesus’ emphasis on compassion. In Buddhist teachings, there is much emphasis placed on ‘inter being’, or ‘non-being’ — the notion that the individual is not some distinct thing separate from other individuals and from the universe, but that all are one, and there is no “self” other than an assemblage of many different non-self parts. From this are drawn conclusions remarkably similar to the compassionate teachings of Christ. Instead of fighting against others who might be called our enemies, Buddhism encourages us to see that their anger or violence toward us is a product of their own suffering, and so by being compassionate toward them, and easing the suffering which causes those reactions in them, so too we help ourselves (at the very least, by relieving ourselves of their violence against us). So too Jesus said to love your enemies (Matthew 5:44), and Thich takes this to mean that if you love those whom you might otherwise call your enemies, and show them compassion instead of anger, you will make them no longer your enemies at all. (Thich pp.78-86). </p>
	<p>The similarities between Thich’s approach to Jesus and the Buddhist approach to Buddha, and both the importance of compassion and the emphasis of the immanence of heaven in both religions, are but a few aspects of Thich’s emphasis on the common ground which makes possible inter-religious dialogue. Thich believes that dialogue is a key component of compassion, in that genuine dialogue fosters understanding of the person whom one is engaging — or perhaps it would be better said, that one cannot genuinely enter a dialogue with a person without the intent to better understand them. In this way, communication becomes less rhetorical and antagonistic, less focused on proving one’s self right and one’s “opponent” wrong, and rather focuses on a dialectical and compassionate goal of mutual understanding, wherein the other person is not an opponent at all, but an equal from whom one might learn something, as well as one who might learn from us. Thus dialogue ceases to be a zero-sum game where one person must lose for the other to “win” (while on the whole, no progress is made), and instead becomes a venue for mutual growth, whereby all participants benefit. </p>
	<p>Taken beyond the small and interpersonal scale, such dialogue between cultures, nations and religions is what Thich sees as the key to ending warfare and bringing peace to the world. As Thich says, “Even if we transport all the bombs to the moon, the roots of war and the roots of the bombs are still here, in our hearts and minds, and sooner or later we will make new bombs” (Thich pp.76-77). The roots of war are in our hearts and minds, as we see one another as enemies rather than as friends, and think that we can do good for ourselves by harming others. But if we engage in this dialectical and compassionate dialogue which Thich advocates, we will no longer be able to see our “enemies” as less than ourselves and deserving of violence, but will instead be unable to do anything but love them, and show them our compassion. Thus such dialogue between peoples of different cultures and in particular different religions will heal the world of its divided antagonism, and bring understanding and peace at long last. (Thich p.136). </p>
	<p>Thich is not alone in his compassionate and inter-religious view of the world. Another great eastern thinker, the famous Mahatma Ghandi, has also written on both the topics of compassionate response to those who would fashion themselves your enemies, and of inter- religious common ground and the possibility of collaboration. In A Letter To A Hindu, Ghandi wrote that “Love is the only way to rescue humanity from all ills ... Love, and forcible resistance to evil-doers, involve such a mutual contradiction as to destroy utterly the whole sense and meaning of the conception of love”. (Ghandi/Tolstoy p.54). This mirrors precisely Thich’s emphasis on love and compassion, as reflected in his citation of the Gospel of Matthew. This very selection from the Bible is also referenced by Ghandi, who in the Talk on Board “S.S. </p>
	<p>Pilsna” cites the Sermon on the Mount in Matthew 5-7 as containing the core tenants of the Christian tradition, and being the part of the Bible which revealed to Ghandi that Christians were not merely those with “a brandy bottle in one hand and beef in the other” (Ghandi p.438), but rather that many are compassionate people with many things in common with his own people. </p>
	<p>Beyond these ethical similarities between Buddhism, Hinduism and Christianity, Thich believes the key for non-Christians to approach Christianity is through the notion of the Holy Spirit. As I have already said, Thich places much emphasis on the immanence of the Kingdom of Heaven, as this immanence is of key importance in Buddhist traditions; and as the Holy Spirit is the immanent aspect of God, it only makes sense that a Buddhist would find that the most approachable aspect of the Christian religion. (Thich 13-14). It seems to me that this is also the aspect which non-religious people such as myself would find the best approach to Christianity. </p>
	<p>Many non-religious philosophical traditions — or at least, philosophies with no direct ties to a particular religion — have conceptions of a divine order or principle. In Greek it is called the logos, in Chinese it is called the tao, and in Sanskrit it is called the dharma. Though the latter two are often thought of as inseparable from the religions that emphasize them (Taoism and Hinduism, respectively), I do not see them as any more inseparable than the concept logos is from Christianity. Though they do not often give it a name, modern scientists even acknowledge that there are universal natural laws and principles, and indeed that is what the entire process of science seeks to discover. All of these notions of a divine or universal or natural order to reality echo hauntingly similar to the notion of the Holy Spirit, that aspect of God which is embodied in everything throughout the universe — as Thich quotes an unnamed Catholic priest as describing it, the “energy sent by God” (Thich 13). When described in this way, I find it hard to imagine that anyone would not agree that there is some overarching principle of order to the universe, and in this sense, I must agree with Thich that the Holy Spirit is the best way of approaching God. </p>
	<p>This emphasis on the immanence of God closely mirrors Thich’s emphasis on the very life of Jesus being his real teachings, and between these two concepts Thich emphasizes Jesus in a very different way than mainstream Christianity does. Mainstream Christians focus on the written word of the Bible and what specific laws must be followed, what doctrine must be believed, and so forth, focusing on metaphysical notions of God-the-Trinity and such. Thich instead emphasizes that the nature and law of God is present and visible all around us, in every part of the universe, immanent as the Holy Spirit. Likewise, the teachings of Jesus are present in his very life, his actions and his choices; not so much in the literal words which the disciples of his disciples claim the he spoke. In this sense, Thich urges us all to find God and Christ, not outside of ourselves in a book or in the words of some authoritative religious figure, but rather inside ourselves, in our communities, and in the world that surrounds us at every moment.</p>
	<p><strong>Bibliography: </strong></p>
	<ul>
		<li>Ghandi, Mahatma, Collected Works. New Delhi, India: the Publications Division of the Ministry of Information and Broadcasting of the Government of India, 1958-1994. </li>
		<li>Ghandi, Mahatma and Tolstoy, Leo, Letters. Long Beach, CA: Long Beach Publications, 1987</li>
		<li>John 1:1, <a href="http://www.biblegateway.com/passage/?search=John%201:1&amp;version=31">http://www.biblegateway.com/passage/?search=John%201:1&amp;version=31</a>  Retrieved March 19, 2006</li>
		<li>Matthew 5:44, <a href="http://www.biblegateway.com/passage/?search=Matthew%205:44&amp;version=31">http://www.biblegateway.com/passage/?search=Matthew%205:44&amp;version=31</a>  Retrieved March 19, 2006</li>
		<li>Thich Nhat Hanh, Living Buddha, Living Christ. New York, NY: Riverhead Books, 1995</li>
	</ul>

</section>