<section>
	
	<h2>How <i>Stargate Universe</i> Should Have Gone</h2>

	<p class="description">Spinning events from the end of canon <i>SGU</i> season 2 into a cosmic plot arc connecting with the foundations of the <i>Stargate</i> mythos.</p>

	<p>(This story presumes the events of <a href="stargate-atlantis"><i>How Stargate Atlantis Should Have Gone</i></a>).</p>

	<section>
		<h3>Season 1</h3>
		<p>The nine-chevron address concept is first stumbled upon by the SGC when making contact with the people of the Orilla galaxy, trying to forge a new peace after the end of the Ori war. The people of one world, claiming to be the oldest settlement in Orilla, request as an offering of peace and goodwill the return of a sacred artifact taken from their galaxy by the Alterans when their schism with the Ori began. When the SGC asks what this artifact is and how they may find it, the people of this world tell them that it is a ship, which belonged to the Ori before they were gods, with which they spread throughout the galaxy and seeded it with Stargates, and which the Alterans took with them when they fled from the Ori. They do not know where to find it now, but it was once accessible by a special nine-chevron Stargate address, before it left the Orilla galaxy; they ask that the SGC try dialing it from the Milky Way, to see if they can find the ship, and return it to its rightful home.</p>
		<p>The Asgard confirm that there was such a ship known in their time before their departure from Orilla; the Nox in turn confirm that it was the ship in which the Alteran expedition fled to the Milky Way, which seeded Stargates in this galaxy, but that it has not been seen since soon thereafter; the Furlings add that they encountered the ship and its crew briefly near the start of the plague, before they fled for Pegasus, but they have no idea what became of it after that. Either way, all three races remember it with similarly mythic levels of awe, and aid and encourage the project to locate it; but the nine-chevron address given by the Orillans fails to connect just the same from any of the four galaxies. However, it is noted that the failure to connect is similar to attempting to dial an intergalactic address with insufficient power. Even dialing from a City Ship with three ZPMs gives the same insufficient power error. Thus the plan is concocted to use an Icarus-type planet to power the connection to wherever the ship has gotten to. Unlike in canon SGU, there is no Lucian Alliance attack that foils the attempt; there is simply a catastrophic overload due to an unknown technical problem, which forces the motley crew of the Icarus base to gate into the ship prematurely.</p>
		<p>Upon arrival, they find the ship in horrible disrepair, as in canon; but unlike canon it appears to have (or have had) technology from the pinnacle of Alteran civilization, despite the ship's much older age. They also find the ship in much more dire circumstances than in canon: rather than floating in empty space, it is caught in the accretion disc of a black hole, hovering barely above the event horizon! Rush suspects that this is the reason they were getting insufficient power problems: just as dialing <em>from</em> near a black hole can power a stargate almost indefinitely due to time dilation, dialing <em>to</em> a location very near a black hole requires inordinate amounts of power due to space dilation. Here in the accretion disc of this black hole they are being bombarded with dangerous levels of radiation and need to leave immediately. Fortunately for them, the ship's gate almost immediately begins dialing again, where in canon the ship would have jumped to FTL. It seems that their gate-in interrupted a dialing process already in progress. They clear a space for the kawhoosh, but instead of opening a wormhole in the gate, an event horizon forms outside the ship, as it engages its wormhole drive...</p>
		<p>...and arrives at an unknown location. The ship's controls, as in canon, are able to show nearby Stargates; but none are visible. Astronavigational scans show unfamiliar star configurations, no known constellations. They have no idea where they are, but they suspect that dialing the wormhole drive from so close to a black hole could have catapulted them unimaginably far across the universe. Their most pressing concern however is life support, as in canon. Like canon the ship's autopilot takes them to a series of planets where they can find things they need; unlike canon, there are no stargates already on these worlds, so they use the ship's ring transporters to ring down to the planets; the timer is the countdown until the scheduled ring-up and the ship's departure. The rest of the first season proceeds similarly to canon SGU S1, including the encounters with various alien species (who have not, by necessity, been following the ship, but are instead merely very interested in it). Notable differences include no communication-stones contact with Earth, and the aforementioned use of ring transporters in place of stargates. Of significant similarity, the mysteriously perfect, Earth-like planet that appears out of nowhere mid-jump is still found and settled by a portion of the crew, especially those with a particularly religious bend.</p>
		<p>At the end of the first season, rather than an invasion by the Lucian Alliance, the action involves the unlocking of Destiny's bridge, and a subsequent attempt to use a wormhole drive jump next to another black hole in order to propel them back to the Milky Way, or somewhere nearer to it at least. The attempt is cancelled at the last minute when Eli calculates that with their current trajectory the wormhole will be bent through the black hole, and nobody is sure what would happen if you tried to gate through a black hole. Instead they continue through normal space dangerously close to the event horizon, slingshotting back around the black hole, and emerge back into safety... only to find that the positions of the stars have all shifted significantly. They passed so close to the black hole that their time was notably dilated, and they are now at least several centuries in the future.</p>
	</section>
	
	<section>
		<h3>Season 2</h3>
		<p>Here in the future, they find a civilization similar to that encountered near the end of canon SGU S2, descended from the colony left behind on the mysterious planet that shouldn't have been there. Their colony has become a tiny fledgeling interstellar empire. The crew of Destiny have mixed reactions to this discovery; on the one hand it is awesome to find an entire civilization of their descendants, who remember them as mythic figures from the ancient past; on the other hand, they are saddened to be, apparently, several thousand years in their future, with no hope of ever returning to the Earth that they knew, even if they could find it in space again. Meanwhile, this new human civilization out here in the middle of nowhere is struggling against some of the alien races in this galaxy first encountered in season 1, including the tall blue aliens (their most personal enemies), the short grey aliens (unhelpful allies in their own dire straights), and the automated drones (everyone's greatest foe). Over the course of season 2, the crew of Destiny attempt to help their descendants in their battles against these enemies, and in exchange they receive much help in resupplying and repairing Destiny itself.</p>
		<p>The second season ends when Eli discovers on Destiny an Ancient time drive. He wants to activate it and try to use it to travel back in time to before they attempted the jump near the black hole, to at least get them back to their own time, so they can continue trying to get back to Earth, and maybe spare this galaxy's civilization the thousands of years of isolated struggle it's been through. Many people are very hesitant about any use of time travel, but after much debate the pros outweigh the cons, and it is brought online. However, when it is activated something malfunctions; they do successfully jump through time, but it is discovered that the drive has suffered much damage from the ship's long time in the first black hole's accretion disc, and they did not jump to the time frame that they wanted; instead of traveling back in time, they have instead travelled even further forward in time! Use of the time drive is thereafter disallowed; they keep getting further and further from their own place and time.</p>
	</section>
	
	<section>
		<h3>Season 3</h3>
		<p>There is now a reasonably advanced interstellar human civilization spanning this galaxy; the allied grey aliens and the enemy blue aliens have both been destroyed by the drones, but the human civilization has absorbed their technology from their ruins and, combining it with their own advanced knowledge, have been slowly driving the drones back.</p>
		<p>The origins of human life in this galaxy have, over the many millennia, become shrouded in myth. One faction believes, accurately though without many precise details, that their people came to this galaxy from somewhere else far away, although even that is laden with religious overtones, the mysterious lost homeworld being portrayed as some kind of heaven. They have been searching the skies for the location of their lost homeworld. Another faction, the more dominant one, believes that their original homeworld was created by an act of divine providence, itself a claim of possible veracity, but they believe human life was created with it. They point to a pattern in the cosmic microwave background, discovered in the others' sky-scans while searching for the Milky Way, as evidence of this cosmic intelligence (ala canon SGU S2).</p>
		<p>The crew of Destiny try to set the record straight for everyone, while being at the same time intrigued by the CMB data, but run into dangerously hostile backlash from some more rabid members of the local-origin faction, so they shut up about it and just do what they can to help and to get along in this new civilization. They submit the Destiny's stargate to study, which allows the creation of new stargates, which they then help seed throughout the galaxy (having by far the fastest drive around); this greatly aids in their battle against the drones, allowing much faster movement of troops and resources across the galaxy.</p>
		<p>They also work with the distant-origin faction, who are mounting an expedition to try to revisit the Milky Way, which they believe they may have located. They plan to join this expedition and hopefully, finally, return home, albeit many thousands of years later. Without Destiny's wormhole drive, the expedition was planning to be a very long, multi-generational journey, using advanced cloning and memory-transfer techniques to preserve the original crew along the way. And near the end of the season, the crew of Destiny learn that this expedition is to be named the "Asgard Expedition", after a mythical name for heaven, which the more religious amongst them believe this lost home to be. The crew of Destiny begin to get very suspicious upon learning this.</p>
	</section>
	
	<section>
		<h3>Season 4</h3>
		<p>Their suspicions are confirmed when the time drive, in its damaged state, unintentionally activates again, bringing them further into the future, where they are confronted by a battleship -- more advanced than those they have been seeing in this galaxy so far, but still much less advanced than Destiny -- commanded by someone identifying himself as a Prior, and demanding that they affirm their allegiance to Origen or they will be fired upon. The crew of Destiny have thus far believed themselves to be in the future, somewhere unfathomably far away; but now they begin to realize that they may in fact somehow be merely in the Orilla galaxy, but unfathomably far in the past. They leave the outmatched Ori ship rather than engage it, and try to sort matters out; meanwhile the time drive is intentionally damaged to disable it and prevent any further unintentional jumps.</p>
		<p>They encounter the fledgling Alterans, those who the Ori call the Others, the descendants of the distant-origin faction of the previous timeframe's civilization; while the Ori are the descendants of the local-origin faction (from which they derive their name). The war has become one of religion versus science, with the Ori desperate to somehow attain unity with the divine cosmic intelligence which they believe created them; and the Alterans, while not denying the awe-inspiring data in the CMB, believing that science is the true path to enlightenment, and that people cannot be forcibly enlightened but must walk the path voluntarily.</p>
		<p>Since Destiny was last around, The Alterans have discerned that the Asgard Expedition was misaimed, and will not arrive in the Milky Way but in another galaxy entirely. They believe they have located the true Milky Way however, and ask Destiny's help in rounding up their supporters and bringing them home at last, far more quickly than they could make it on their own. The crew of Destiny are happy to help; they round up the Alteran supporters from around the galaxy, doing battle with the Ori meanwhile, who are able to dial straight into Destiny via the nine-chevron address. Then after a climactic battle at the place that would be called Ortis Malum, on the planet that would be called Celestis, where the Ori would celebrate their "victory" over the Alterans, the fully-loaded Destiny at last departs for the Milky Way.</p>
	</section>
	
	<section>
		<h3>Season 5</h3>
		<p>Arriving successfully in the Milky Way, where the Ori can no longer reach them by stargate and cannot follow by ship, they find a pre-existing Unas-Goa'uld spacefaring civilization, bearing little resemblance to the Earth-derived Goa'uld culture of later aeons. Being far more technologically advanced, they easily fend off the initial Goa'uld attacks, but being horribly outnumbered they soon realize a more permanent measure is required if the Alterans are to settle this galaxy. A planet which would come to be called Dakara is selected as the site of a superweapon which can create or destroy select forms of life instantaneously, and stargates are deployed to key Goa'uld worlds, through which the weapon would be fired, annihilating the parasites and leaving the empire headless, but the Unas hosts alive, though without much hope of a continuing civilization.</p>
		<p>Afterwards, Destiny seeks out Earth, finding it, as they expected, in a prehistoric state, and settle the Alterans there. They seed further stargates on Earth and a few other important worlds; then bid the Alterans farewell. The Ancient time drive is repaired as best as possible, and they attempt to return to their own time, in a series of shorter jumps.</p>
	</section>
	
	<section>
		<h3>Season 6</h3>
		<p>After their first jump, they arrive at the height of Ancient civilization in the Milky Way. To their dismay, they find the Alterans have been hunting the Unas to extinction, slowly unmaking their empire even though the Goa'uld which built it are thought to be extinct, and their Unas hosts are innocent of their crimes. Upon reflection though, it is obvious that this should have been expected from history as they knew it. The Alterans of this time are finally advanced enough to fix or replace Destiny's more advanced systems, including the wormhole drive and the time drive, restoring the ship to brand new condition.</p>
		<p>Then the stargate on Destiny unexpectedly activates, and through it come soldiers of the Ori army. They have been trying to dial the nine-chevron address regularly ever since Destiny left Orilla, and now have power sources capable of intergalactic dialing. They capture Destiny, and bring back data on the Ancient civilization to Orilla. Destiny is eventually reclaimed by its crew with the help of the Alterans, but now the Ori have many addresses in the Milky Way, and begin gating in troops to many Alteran worlds. The Alterans, however, are more advanced, and manage to fight them off. They plan to send their newest City Ship, Taonas, to the Orilla galaxy to stop these attacks. But Destiny remembers their history, warns the people of Taonas to flee the galaxy instead, that a plague is coming, and promises to take the fight to the Ori in Destiny itself.</p>
		<p>But on its way to recharge in a star before jumping to Orilla, an Ori force still in the Milky Way deploys a weapon which collapses the star the ship is charging in into a black hole. As the star collapses, they begin to engage the wormhole drive to Orilla to escape, but Eli warns them again that dialing this close to a black hole would send their wormhole through the black hole which is like dialing through a star but a million times worse, even if they survived at all they might end up back in time all over again! It dawns on them all, at that comment, that that is precisely what happened the first time, and that this is the black hole where the ship was found to begin with. They lock the computer to abort the wormhole drive dialing sequence; they manage to get the ship settled into a stable orbit around the black hole, and then try to figure out a way off the ship themselves. The original crew -- they realize now, they <em>are</em> the original crew -- somehow managed to escape before they first arrived on the ship, so there's got to be some way.</p>
		<p>Eli eventually devises an escape plan. They can't gate out for the same reason they can't dial the wormhole drive: the ship's sublight drives aren't powerful enough to escape the black hole and neither are any of the shuttles. But a matter stream like the ship's ring transporter should be able to do it, and ring transporters seek their own targets, so all they need to do is channel enough power into the ring transporter to be sure to reach a ring platform somewhere in this neighborhood of the galaxy, and they will automatically ring to the nearest one. They can use energy from the black hole to super-boost the rings just like a stargate connection. The one confounding factor is time dilation; the matter stream will be time-dilated on its way out, they are being time-dilated right now just being this close to the black hole, so they will end up an unknown length of time in the future.</p>
		<p>They do it, and ring out off the ship, abandoning it where they found it. They arrive on an apparently uninhabited world on a ring platform near a stargate, and attempt to dial Earth. Not knowing what time period they're in, they radio through first; the SGC responds! They have arrived nearly seven years after their departure; they were presumed dead in the explosion of Icarus, and attempts to dial the nine-chevron address were abandoned. Nevertheless they have made good progress on building relations with the Orilla galaxy, and things are going well all around.</p>
		<p>During debriefing, they ponder on the ontological paradox of the ship's cyclical existence in time; and the mysterious planet they found when first arriving in the past Orilla; and the even more mysterious pattern in the cosmic microwave background, and the claims that it represents some kind of primordial, universal intelligence. The team at the SGC report that they've actually found data on this "God pattern" in Atlantis' databanks, that the aim of the ascended Ancients, what set them on that path in the first place, and why they focus more on their own internal spiritual matters than matters of the material realm, is the hope of attaining some kind of unity with this cosmic intelligence. They believed that it was itself composed of a union of ascended beings, that it transcended space and time, and had subtly shaped history since the Big Bang, perhaps even causing it in some way. The Ancients knew, from their interactions with Destiny's crew, that their own origins were cyclical, and suspected that cosmic intelligence of having something to do with it; of creating the planet they first settled in Orilla, of putting Destiny in place to begin with, as a part of ensuring its own creation.</p>
	</section>

</section>