<?php $title = "The Chronicles of Quelouva (9x25): Virtuality Immanent: Part 3, Episode 1 &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>

				<section>
					
					<h2>(9x25) Virtuality Immanent: Part 3, Episode 1</h2>
					
					<p>
						On Niarba, Keius confesses to Metis that he did not invent magic, he merely discovered it. But with his help his people have learned to commune with those who did invent it, the Minded Worlds, and he can try to guide the mind of Geie, the world-mind of Niarba, to ask the Minded Worlds for help. Though the details are difficult to comprehend, as Keius is like a mere a neuron trying to convey the results of an entire organism's conversation with many other organisms, what he relates is astounding.
					</p>

					<p>
						The technology he has so long insisted is not actually magic, <em>is</em> actually magic, because this world itself is in some sense virtual. Not that there is a "real galaxy" out there, but there is something poorly understood outside of what we think of as the universe, and the nanotechnology from the Minded Worlds exploits that to do things that should be physically impossible within the rules that normally govern our universe. Such "magic" masquerades as technology because whatever it is that is outside the universe does not want "magic" to exist, does not want the rules of its construct violated, and has gone so far as to actually rewrite the previous course of history so as to erase magic from existence before. The Minded Worlds have developed some kind of resistance to this cosmic retconning, and so are able to remember it having happened.
					</p>
					
					<p>
						So as to end the current crisis quickly before this rampant abuse of magic brings another cosmic retcon down upon the universe, they offer to grant Metis alone a special degree of magic beyond even that of the nanotechnology: the ability to defy the second law of thermodynamics and so to overpower the Demons, able to take the waste heat being rapidly generated by the consumption of matter to fuel the titanic war of magic tearing apart the galaxy and use that as a power source to counteract that magic. But with that power she must dive straight to the source of the Demons, to destroy Xio and with him Virtuality, to end the Demons immediately. Metis is urged to depart quickly, to go reluctantly kill her lost love Xio to save the galaxy and perhaps history, making a beeline punching through vast swathes of Demons throughout the galaxy straight to Earth.
					</p>
					
					<p>
						Meanwhile, in the virtual world, Tom and Xiuying, in their continuing but futile battle against the Queen of Hell, have adopted a suicidal plan to save the galaxy themselves. Knowing that it will kill Xio's avatar and awaken him from Virtuality, in doing so ending the virtual world and themselves with it, but also the Queen and all the Demons, they crash the Sword of Darklight at top speed into the virtual moon, destroying both in the collision. Xio awakens on the real Earth... but only moments before Metis smashes into his location like she has a death wish herself.
					</p>
					
					<p>
						<strong>Next:</strong>
						<a href="../2">
							Virtuality Immanent: Part 3, Episode 2
						</a>
					</p>

				</section>

<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
