<section>

	<h2>Army of Angels</h2>

	<p class="description">A paper for a class on Philosophy of Religion, 2007.</p>

	<p>In his essay “Primary Philosophy”, Michael Scriven gives an argument intended to prove the nonexistence of God by way of his incompatibility with the existence of evil. His argument is: (1) There are incidents of true evil in the world. (2) Such incidents would be prevented if anyone moderately powerful, understanding the situation, and caring to prevent evil was around to prevent it. (3) As God must be all powerful, all knowing, and all good, if God existed there would be a being powerful enough to prevent the evil, who understood that it needed to be prevented, and who cared to prevent it. (4) But such evil is not prevented. (5) Thus a sufficiently powerful, understanding and caring being must not exist. (6) Thus God must not exist. If we let “P” stand for “evil things occur”, let “Q” stand for “a sufficiently powerful, understanding and caring being exists”, and let “R” stand for “God exists”, then the argument is formally: </p>
	<p>(1) P. </p>
	<p>(2) If Q then not P. </p>
	<p>(3) If R then Q. </p>
	<p>Therefore (4) Not not P (from 1 via double negation). </p>
	<p>Therefore (5) Not Q (from 1&amp;4 via modus tollens). </p>
	<p>Therefore (6) Not R (from 3&amp;5 via modus tollens). </p>
	<p>However, Scriven then seems to tacitly acknowledge that premise 2 is not entirely correct, as he then proceeds to collectively address a body of theist responses to arguments such as his, all of which seem to assume a modified version of premise 2. The modified premise which such counter-arguments assume is, roughly, “If a sufficiently powerful, understanding and caring being exists, and there is no morally sufficient reason to allow evil to occur, then evil will be prevented.” If we let “S” stand for “there is a morally sufficient reason to allow evil to occur”, our modified premise becomes: (2) If Q and not S, then not P. Counter-arguments to arguments such as Scriven’s then seek to show that we cannot be sure that “not S” is the case (i.e. that there is no morally sufficient reason to allow evil to occur), and thus that we cannot soundly conclude “not R” (i.e. that God does not exist). As Scriven’s response to such counter-arguments is to argue that it appears that no such morally sufficient reason exists, it seems that Scriven tacitly accepts the modification to the form of his argument, but denies that “S” is the case, i.e. that there is a morally sufficient reason for an all-powerful, all-knowing, all-good being to allow evil to occur (or at least, that the reason in question is in fact morally sufficient). </p>
	<p>Typically, morally sufficient reasons for humans to allow evil to occur are along the lines of either “I didn’t know the evil was occurring; if I had known I would have done something about it”, or “I couldn’t do anything to stop the evil; if I could have I would have.” But as God is by hypothesis all-knowing and all-powerful, such excuses do not work for him; so his reason must be either that he shouldn’t stop it, as there is some good, moral reason to allow the evil to occur (i.e. the evil in fact serves some greater good); or at least, that he doesn’t have to stop it, as he is not morally deficient in permitting it (i.e. he’s doing nothing wrong by allowing it). </p>
	<p>The particular response which Scriven addresses is of the latter sort. He presents, on behalf of unnamed theists, a supposedly possible morally sufficient reason for allowing evil to occur, namely that God gave mankind free will, which was good of him to do, and that all the evil which occurs is a result of us poorly exercising that free will, not of any wrongdoing on God’s part. But Scriven responds to this by stating that we do not usually consider it morally right for a bystander who could prevent evil to stand idly by and allow it to occur. Thus, as God would be “present” at the scene of every crime (inasmuch as he would know it was occurring and be able to do something about it), it would be immoral of him to stand idly by and allow it to occur. But as God cannot be immoral by his very nature, nor can he help being thus present, if God existed he would necessarily prevent all evil from occurring. The only reason Scriven seems to permit for someone to stand by and and allow someone to suffer evil is when it serves as punishment; however, he claims, as seems right to me, that there are incidents where people suffer evil far disproportionate to any punishment they could possibly deserve, and thus it seems that there are at least some instances of evil which God has no good reason to allow. </p>
	<p>But theist counter-arguments of that sort are weak, and there are stronger counter- arguments of the other sort I listed; that is, reasons along the lines that permitting evil to occur is necessary for a greater overall good, and that had God acted to prevent all such evil, the overall good of the world would be diminished. Such an argument as this, also regarding free will, has been made by Alvin Plantinga. His possible morally sufficient reason is thus: The existence of free agents is so good that any world with free agents is better than a world without it. This does not mean that God cannot ever interfere with free will, but rather that he must sometimes allow it. Thus, given that God must make the best world he can, and that such a world must contain free agents, God does not have the ability to directly eliminate all evil from the world, for the existence of free agents creates the possibility for evil to enter the world. God only has choices as to what package of direct actions to take in the creation of the world, initial conditions and miraculous interventions and so forth; and given those packets of direct actions, God must have chosen the best of them (being all good), and this world would then be the result of that package plus the actions of the free agents in the world. Thus, some evil is permitted to exist because it must be in order to allow us our freedom; but God has done much, as much as could possibly be done, to eliminate evil from the world without eliminating free will as well. </p>
	<p>But Scriven’s final argument counters this nicely, arguing that it certainly appears that there is more that God could have done without removing our free will. He makes the analogy of God to a parent or mentor, and of mankind to children; and by that analogy it seems that there is obviously much more that God could have done, even given a world otherwise just like it is now (free agents and all), to make the world safer, promote justice, and even make people morally better. In other words, it seems that God could have easily done a better job of parenting the human race, raising us to be good people, and protecting us from each other and the world, without removing our free will. The first thought which comes to my mind is that he could have created an army of wise and powerful angels (themselves without freedom to do evil, being merely agents of God’s actions) to guide and protect mankind until such time as we are capable of caring for ourselves; just as mentors and parents raise children to be responsible adults. No one claims that such actions by human mentors deprive children of free will. Parents and mentors merely guide children to be better people and protect them from each other and from the world. </p>
	<p>It is often claimed that God in fact does all these things already. Various holy texts are supposedly the word of God to mankind, meant to educate and guide us. Further, said texts claim that God often intervenes in the world to protect the innocent and punish the wicked. But even accepting such holy texts as the inspirational word of God, and their accounts of God’s interventions as true, when I look around the world today, it seems obvious that God could do so much more, without any apparent negative consequences. I cannot imagine how a world in which there existed an army of angels, who left us alone to mind our own business except to come to the aid of those who needed it and to teach those who do wrong the error of their ways, could be in any way worse than the world as it is today. It would be just as though the world today were filled with more saints and heroes than it is, which would be undeniable better; everything else could stay the same and still the world would have improved by leaps and bounds. Granted, I can imagine a world that was still better than that: a world in which such an army of angels was not needed, and in which humans freely chose to fulfill the role of those angels themselves, looking out for each other and keeping each other in check. Unfortunately if we are to accept that God must allow free will, he cannot directly bring about such a world. Though we might say that God could have created each of us with kinder and nobler dispositions, such that we were all saints and heroes from birth, one might argue that to do so would be to meddle in our ability to exercise our free will. While I do not accept that rebuttal myself, I am willing to grant it for the sake of argument, for it seems that God could still have brought about such a world without directly meddling with our innate dispositions, by providing such angelic role models as I have described, to raise us into well-behaved people, and then surrender the world to us as we matured. One may suggest that God did do this in ancient times. Holy texts are full of tales of divine intervention. </p>
	<p>But why so little of that now? Did God give up on us after too many centuries of our failure to learn our lessons, or decide that we ought to be able to care for ourselves by now, even though we clearly are not? That would be like abandoning a room full of immature children to themselves, with no safeguards but a warning to behave themselves, which we ordinarily would say would be irresponsible of their caretaker; and irresponsibility is not characteristic of an all-good God. </p>
	<p>This seems to be a possible rebuttal to nearly any supposed morally sufficient reason; we pretty much always consider it a good thing when people fight against injustice or come to the aid of their fellow human beings, and so if that is our standard of morality for ourselves, why should we hold God to any less of a standard? I will readily admit that there are many reasons why a God might allow evil into the world, if we are to allow him some different sense of goodness than we normally ascribe to human beings. A great struggle between good and evil may make the history of the world more beautiful, for example; but we would not excuse a person for allowing a crime which he could have prevented, on the ground that he found the struggle of good against evil to be beautiful to watch. So why should we allow God that excuse? In short, it seems to me that any excuse one could give to permit evil to exist — to build virtue in people, to lead history to some predestined conclusion, to make people appreciate the good things in life, etc. — begins to slip away from our normal concept of morality, whereby evil is to be prevented whenever possible, and no such excuses are acceptable. Thus it seems that likewise, no such excuses would be morally sufficient for an all-good being such as God; and therefore it seems that such a benevolent God cannot exist together in a world with evil, such as our own.</p>

</section>