<?php $title = "The First Waterbender &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2>The First Waterbender</h2>
				
					<p class="description">A prequel to <i>Avatar: The Last Airbender</i> outlining the first complete cycle of the Avatar.</p>

					<section>
						<h2>Fire</h2>
						<p>Ten thousand years before the era of the Avatar, the physical world was inhabited by all manner of intelligent animals, from the mighty Lion-Turtles, Dragons, Sky Bison, and Badger-Moles, on down to primitive man. These creatures bent not only the elements, but also the energies within themselves and each other. Their world was shaped by not only their deeds, but by the subtle guiding actions of guardians from the spirit world, who in turn were conjured into being and shaped by the processes of the physical world.</p>
						<p>Then, everything changed when the great spirit of darkness and chaos, Vaatu, opened the spirit portals and allowed bodily passage between the spirit world and the physical world, disrupting the natural relation between physical and spiritual beings. Though Vaatu was defeated at that Harmonic Convergence by the great spirit of light and peace, Raava, the spirit portals remained open, and many lesser spirits began to settle in the physical world. Though the great animals, learned and powerful in the bending arts, stood well against the invasive spirits, young mankind was threatened by the newcomers, and retreated to the protection of the mighty Lion-Turtles.</p>
						<p>Ten thousand years later, as the next Harmonic Convergence approached, a young man named Wan left the shelter of his home and learned to live in the wilds with the spirits. There, he met the great spirits Raava and Vaatu, and mistakenly freed Vaatu from Raava's grasp. Setting out to right his mistake, Wan became the first human to learn all four bending arts, with the support of Raava, and in a climactic battle against Vaatu at the Harmonic Convergence, their spirits were permanently joined, Wan becoming the first Avatar of Raava. Together they were able to imprison Vaatu, return the lesser spirits to the spirit world, and seal the portals between the worlds, restoring balance between them.</p>
						<p>But in the physical world, mankind began to spread again beyond the shelter of the Lion-Turtles. Having learned the bending arts from their protectors, these early human civilizations made war on each other in a race to claim the lands now free from occupying spirits. But the spirit world remained intertwined with the physical world in its natural way, and this war between the human nations ravaged not only the physical world but the spirits intertwined with it. So Wan set out to bring peace to the burgeoning world of mankind. But his efforts, though well-fought, were ultimately in vain, and those first civilizations of men were utterly destroyed in war, their masters of the bending arts killed in battle, including ultimately Wan himself.</p>
					</section>
					<section>
						<h2>Air</h2>
						<p>Yet bound up with the spirit of Raava, the Avatar was now immortal, and after Wan's death was reborn, into the the one civilization which had not ruined itself in war. A race of nomads with strong spiritual practices had secluded themselves away from the warring world to the best of their abilities, though the wars still had not let them be in peace, and their own benders were killed in defense of their people. But as the next Avatar grew up among these nomads, she watched the Sky Bison who still lived among them in their mountaintop home to the south, and subconscious memories of her previous life as Wan came to her. Mimicking the Sky Bison, she became the first new airbender, and incorporated that art into the breath-centric spiritual practices of her peoples, teaching them to control the breath of life, and by extension any air.</p>
						<p>As she grew, memories of her past life returned to the Avatar like dreams, and eventually she left her air-nomads to find what had become of the tribe from which Wan had arisen. Upon finding them, she discovered that they worshipped fire, and the sun as the source of all fire, but had lost the art of bending it as she remembered them doing in her dreams. Harkening back to their past greatness, the Avatar took an expedition to study the Dragons that lived in the volcanic archipelago to the west, and petition them to teach these people the art of firebending. Recognizing Raava in the spirit of the Avatar, the wise dragons agreed to teach her alone to focus her breath-energy and project it in the form of fire. But that was enough, and the second Avatar spent much of the remainder of her life rekindling the art of firebending amidst the sun-warriors of the western archipelago.</p>
						<p>In her old age the Avatar set forth in search of other great animals to teach her the other bending arts. She sought most of all a Lion-Turtle like had taught her past life as Wan, but they had become rare, secluded and hidden in the years since the wars of man began. The best she eventually found were Badger-Moles, who agreed to teach her earthbending. Upon mastering that art, she set forth to find worthy pupils to bring to the Badger-Moles to learn as she had, but by that time the Avatar was very very old, and on her journey passed away into the mountains, never again to be seen.</p>
					</section>
					<section>
						<h2>Water</h2>
						<p>But the Avatar was again reborn, this time into the fishermen of the north. Again he grew and memories of his past life began to come to him as dreams. Living on the water, the idea of waterbending appealed to him most, but living far from any great animals that might teach him its ways, he grew to adulthood without ever realizing his potential. Until one night, while fishing at high tide under a full moon, he realized the interplay of the ocean and moon, how the later would push and pull the waters of the former, and learned directly from them how to bend water likewise, becoming the first new waterbender. He began to teach his people what he had learned, and with this new talent his tribe became prosperous.</p>
						<p>But unlike his predecessors, this Avatar had no great desire to travel the world and learn or teach the other bending arts. He sought always the easy way in life, flowing down the path of least resistance, and with waterbending he and his people had settled into an easy life on the northern sea. It was not until a great Lion-Turtle came to him one day, and bending his energy, reminded him of the oath he had swore, as Wan, to bring balance to the world. The Lion-Turtle warned him of how, even devoid of bending arts, the wars continued to rage between petty tribes and kingdoms on the mainland, and that it was his duty as the Avatar to fulfill his oath and bring peace to those people.</p>
						<p>The first Avatar was then sent on a mission by the Lion-Turtle to visit each nation, to find the other benders therein, to live with them, learn their element and their way of life, rally them together, and unite their respective nations. The Avatar didn't want this responsibility; he just wanted to stay at home and relax in peace and prosperity with his people, and he didn't understand why others were so bent on their power trips anyway. But the Lion-Turtle pleaded with him that the world needed him, that he alone could heal mankind and restore balance to the world, and so the Avatar was persuaded to give it a try.</p>
						<p>The Avatar first visited the main continent to the south of his native waters, what would eventually become the Earth Kingdom, where he found many warring villages. He tried, with little success, to build peace between them and with the spirits intertwined with their land, to teach them to relax and not be so uptight about all the things they were warring over. He eventually met Oma and Shu, lovers from two warring tribes on opposite sides of a mountain, and the first earthbenders, who had learned their art from the very same Badger-Moles that had taught the second Avatar beneath said mountain. The Avatar befriended them, showed them that he too had a bending skill, and learned earthbending from them. In doing so he also learned their way of steadfast resilience in the face of opposition, and the stillness and patience to wait for opportunities, which was a change from his people's relaxed ways of flowing around obstacles and finding alternatives instead of pressing difficult issues. This helped convince him that despite the apparent futility of it thus far, he needed to remain steadfast and press on in his mission as the Avatar. But his training was interrupted when when Shu was killed in the battle between his and Oma's tribes. Oma nearly destroyed them both in retaliation, but the Avatar talked her down, reminding her of her own philosophy: be still, be strong, remain dedicated to your cause, and see opportunities whether others would not. Instead of destroying the two villages, she and the Avatar took advantage of the tragedy of Shu's death. They used their earthbending to build the city of Omashu on top of their mountain, dedicated in Shu's memory; and after this breathtaking feat of power, Oma declared the war between their villages over, inviting the peoples of both to live together in peace in this grand new city.</p>
						<p>Thereafter Oma travelled the lands with the Avatar, building peace amongst the warring tribes and mediating between men and spirits as they went. But they soon realized the great threat posed by the expanding empire of Ba Sing Se, whose strategy consisted of strongly defending their own borders while closely watching the play of their neighbors' wars, and then just as each war ended, conquering both victors and victims in their weakened state, thus expanding their empire. Even with earthbending and waterbending, the Avatar concluded that they stood little chance of stopping that behemoth. Though Oma would stay and fight, and positioned Omashu as the strongest enemy of Ba Sing Se, the Avatar insisted that they must find another way. So they travelled across the sea to the volcanic archipelago where the Fire Nation would some day be born, seeking the power of fire to use in their intended war against Ba Sing Se. There they met the Sun Warrior Tribe, who had continued to learn firebending from the Dragons since the previous Avatar left them. After initial hostilities, they were forced to prove themselves to the Sun Warriors through a series of difficult trials. The Avatar wished merely to pass them by and find someone else who would teach him firebending, but Oma insisted that there may be no one else; that the Avatar had to remember what she had taught him about steadfastness, and withstand their trials. They eventually proved their worth, won the Sun Warriors' aid against Ba Sing Se, and the Avatar was taught firebending. It proved a most difficult subject for him, very much unlike waterbending, even more so than earthbending; he was forced to put a kind of brute force and passion into his training, not merely standing strong but taking the initiative and forcing his way through, finding a strength, energy, and vitality he did not previously know he had. But when he eventually mastered firebending, the Avatar became a great warrior, forceful and unflinching, and dove headlong into his plan to defeat the empire of Ba Sing Se.</p>
						<p>But first, as Oma reminded him, he had to complete his training by learning airbending. Together with Oma and his firebending teacher from the Sun Warriors, he sought out the mysterious nomads seen riding Sky Bison, figuring that they of all people would be the ones to learn airbending. But the nomads, being nomadic and traveling by air, were very difficult to find. Eventually they tracked a Sky Bison across the south seas to what would become the Southern Air Temple, where they learned to their surprise that all the nomads had learned airbending as part of their breath-centric spiritual practice. But the nomads were extremely hesitant to teach the Avatar airbending, knowing he intended to use it to defeat Ba Sing Se in war; for they believed in peace above all, never condoning the use of force, but instead seeking personal freedom via complete detachment from all things. The Avatar asked to at least be allowed to study their spiritual ways, if not airbending, as they reminded him much of his own people's relaxed attitude, and he feared that he may have lost something of himself in his training in earth and fire. After some time studying with the nomads, he realized that simply defeating Ba Sing Se in war would not accomplish his goal of bringing harmony to the world and healing mankind. Instead, he decided on a different battle strategy, one only feigning force, without the intention to use it except as a very last resort. Even then, the airbending masters were hesitant, but after much meditation on the matter, they were persuaded, and the Avatar was taught airbending. His training consisted of learning to let go of the great burden of his mission and actually enjoy life; he was, in a way, forced to take a vacation, which he found very difficult with the fate of the world weighing on his shoulders. Eventually he realized that he was not responsible for the world, that even if he failed it would be no worse off than if he had never existed. Learning to let go brought him the freedom required to master airbending, and at last his training was complete. But still, he had to come down again and complete the task before him.</p>
						<p>Now fully realized in his power, the Avatar and crew traveled with his reluctant airbending teacher on a Sky Bison, back to his home lands, to rally their forces to the continent. They then travelled back to the fire archipelago to rally their allies there as well. Then they travelled to Ba Sing Se, sailing easily over its supposedly impassible walls, and entered the halls of its king, the Avatar demonstrating his immense power during the battle to get inside, aided by Oma and the master Sun Warrior, while the Air Nomad monk whipped up a sandstorm around the city as a distraction. Once inside, the Avatar struck a deal with the king of Ba Sing Se. If the king continued his path of war and conquest, the armies of fire and water, which were even then massed against him, would storm his shores and unmake his empire; and with the airbenders' ability to fly right over their walls, and the Avatar's immense power, Ba Sing Se itself would be erased from the map. Or, preferably, the king could stay his hand, stop the war, and devolve partial sovereignty to those who had already been conquered, in which case Omashu, their greatest rival, would join as a free province of the kingdom, equal with all the others; Oma would teach earthbending to the army of Ba Sing Se, and with it the city would be made truly impenetrable; and on his next life, the Avatar would be reborn in Ba Sing Se, and he would build its domain into a true kingdom of the earth, unrivaled amongst the nations of the world.</p>
						<p>The king conceded, and the war was ended. Oma and the Avatar, having grown close through their adventures, eventually settled down together. At first they lived in Omashu, where Oma began the first school for earthbenders, and from which the treaty with Ba Sing Se was enforced, with the aid of visiting firebenders. But later, the Avatar and his wife created a colony of the Avatar's people in the southern waters near the Air Temple, where he continued his spiritual training until the end of his days. As he trained, he founded temples of the Air Nomads in the other three nations as well, for them to act as mediators and spiritual guides for the peoples of the world.</p>
					</section>
					<section>
						<h2>Earth and beyond</h2>
						<p>After the third Avatar's passing, his promise to the Earth King was fulfilled, and he was reborn as an earthbender in Ba Sing Se. There, he strengthened the ties between the Earth Kingdom's constituents, built Ba Sing Se into the greatest city the world had ever known, and from that seat of power at last united the four nations of mankind into a harmony that would last for generations. His promise to Raava had been fulfilled, and the first cycle of the Avatar was complete.</p>
						<p>Over subsequent lives he would continue his mission of peace. Restraining the nascent Fire Nation, the united colonies of the Sun Warriors across the western archipelago, from their earliest bid for power against the Earth Kingdom. Devolving spiritual authority from the Air Temples to local peoples, creating Temples of Fire, Water, and Earth as well. Uniting the northern and southern Water Tribes into a single kingdom despite the world of distance that lay between them. And completing the unification of the mainland into the great Earth Kingdom.</p>
						<p>And thus over the next Avatar cycle were settled the four nations of the world: the four temples of the Air Nomads, the northern and southern Water Tribes, the Fire Nation, and the Earth Kingdom. Each alive with its own spiritual practice, each master of its own bending art, and each proud to be united with each other under the Avatar.</p>
					</section>
				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
