<? $title = "A Buffyverse Spin-Off &ndash; by Forrest Cameranesi" ?>
<? require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-stories.php" ?>
				
				<section>
	
					<h2>A Buffyverse Spin-Off</h2>
				
					<p class="description">An idea for a spin-off series set in the same fictional universe as <i>Buffy the Vampire Slayer</i> and <i>Angel</i>.</p>

					<p>It is well-established that the multiverse of <i>Buffy The Vampire Slayer</i> and <i>Angel</i> consists of many worlds or "dimensions", populated by many nonhuman races, all collectively called "demons". Most of these worlds are hellish, some are even called hell dimensions, but the beings which inhabit them run the gamut of morality. Some exceptionally powerful beings called gods often rule over these world, and are usually indifferent at best, outright evil at worst.</p>
					<p>At least one world, however, is a blissful heavenly dimension; and at least one group of beings, the Powers That Be, fight against the evil to bring goodness and light to the world. They were originally natives of our dimension who banished the demons from our world when human life evolved here.</p>
					<p>Let us allow that Heaven is controlled by the Powers That Be; that ever since banishing the demons from our world, they have guided human souls after death into other realms they control. The Powers however are very protective of their own Heaven and only permit the purest of souls into it; other souls are sent instead to purification, containment, or punishment facilities of varying severity in other worlds. Meanwhile, of course, the demons have been trying to reconquer our world as part of their larger war against the Powers across the multiverse. </p>
					<p>The main protagonist of this story is a businessman from present-day Earth, who is savvy of the supernatural element in our world, and tries to play off it to his own betterment without actually helping the forces of evil with their whole destroy-the-world bit (since he rather likes the world and isn't stupid about where his place would be under a demonic rule). However, he is far from a champion of justice either. He's ruthless, selfish, and otherwise without compassion for strangers, although he is charming, charismatic, loyal to his buddies, and will kiss anyone's ass to move up in the chain of power.</p>
					<p>He got eaten by vampires he was trying to double-cross in some underhanded dealings, and is now in a Powers-controlled purgatory full of high-handed sermons and gentle forced labor. This place has the aim of reforming wayward souls and transforming them into beings worthy of admittance into Heaven. Our protagonist is bored out of his goddamned mind and determined to get the hell out of there... or, preferably, find a more pleasant route out of there.</p>
					<p>While in purgatory, he meets a physicist from a future Earth who is likewise not happy with his situation. This guy suffers the additional indignity of not having actually died to get here. He was working on some sort of information-theoretic quantum trans-temporal trans-dimensional transportation technology, and accidentally ended up in the purgatory world in the what he considers the distant past (though not so distant from our perspective), rather than in Earth's past as he had intended. He's still there because he doesn't believe the Powers are anything other than interdimensional aliens, and he rather has a thing against interdimensional aliens, since they have apparently caused some havoc in his future; and so he will have nothing of their attempts at indoctrination and forced labor. The businessman takes keen interest in the possibility that this guy could bust them out, if he managed to bust in here to begin with; but the physicist shatters his hopes by pointing out that he got here with the help of a lot of fancy high-tech equipment like quantum supercomputers and vacuum energy extractors and artificial singularities, and without that he's little better than a walking physics textbook.</p>
					<p>Those hopes are rekindled later when the businessman meets another lost soul trapped in this purgatory: a witch from Earth's past, who has been in purgatory longer than anyone else he's met thus far because she refuses to bow down to anyone and opposes all authority. She believes in immanent magic permeating the universe and scoffs at witches and wizards who invoke and supplicate deities for their magic. In life, she was a druidic priestess who fought against the Christian church's incursion into her people's lands, and was burned at the stake for her troubles. She sees the Powers as connected to the Church, says she can feel the mystical connection between them, and so refuses to have anything to do with them. She was once a frequent troublemaker here but was sent for a stint in a more hell-like dimension as punishment, and so for the most part just tries to avoid everyone else as much as possible these days. She confides that she has been spending her time attempting to perfect portal magic to break out of here, but while she can harness great amounts of power now, the specifics of any particular portal incantation are too complex for her to master. So she is still stuck here, as she has been for hundreds of years; and so she holds little hope for ever figuring a way out.</p>
					<p>The witch and the physicist are connected with each other through the businessmen's mutual acquaintance, and between them all they realize that the physicist's calculations can be adapted into incantations for the witch to cast, allowing them to open portals to other dimensions at will. The three of them plot a scheme to break out of purgatory, and succeed, ending up in a wild, medieval demon dimension. There they meet a demon warrior who is being pursued by agents of the Powers, who have established a military base in his dimension and are one none too friendly terms with natives about it. The warrior, despite his grotesque appearance, is a very friendly, helpful fellow, who is just on the wrong side of the Powers for being a demon and a soldier in the army of the native people who resist the Powers' incursion into their world. They were happy when the Powers got rid of their evil gods, but they aren't too happy that the Powers want to be their new gods.</p>
					<p>The four of them evade the Powers' forces and hide out in the wilds of this world, while the physicist completes his next set of calculations and the witch connects with the magic of this new dimension. The businessman and the warrior converse meanwhile; the businessman explains that they plan on breaking into Heaven, and that while they have spiritual, intellectual, and leadership savvy between the three of them, they lack the muscle that will probably be necessary for this endeavor, and invite him to join them on that role. The warrior, being a demon, has no hope of ever getting in to Heaven otherwise, and his world is pretty shitty as-is, so he agrees to their plan.</p>
					<p>After the witch and physicists are done with their preparations, they open a new portal, and break into break into a world filled with light and warmth and beautiful clouds colored as though by sunset. They are immediately set upon by the black-armored demon guards they knew from purgatory, and though they put up a good fight, they are captured, and confronted by priests of the Powers.</p>
					<p>They are told that the punishment for battling against the forces of Heaven is eternal damnation, however, the Powers are impressed with their ability to get this far, and aside from this little rebellion they are not, on the whole, such bad people. So they are spared retaliation, and offered a job instead. They will be made mortal again, even as they transverse the immortal realms, and if they fight for the Powers against the forces of evil, across the many different worlds, they may earn entry into Heaven when they finally die again. Otherwise, if they die before completing their mission and proving themselves worthy, then for their attempt against Heaven, they will be sent to a death much worse than the purgatory from which they came.</p>
					<p>The witch rebels against the idea of working for the Powers, but the businessman argues they she was willing to compromise once to get back to purgatory from her stint in a minor hell, and this is little different, only with much higher stakes of reward and punishment. The physicist chimes in that he doesn't believe in any of this spiritual mumbo jumbo and would just as soon return to his own world and be done with all this, but he acknowledges that the Powers, even if they are just extradimensional aliens, do seem to hold power over the multiverse, so he is willing to give working for them a try since it looks like his only way out. The warrior doesn't have much different than this deal to look forward to in his own world, even if he could return there now, so he's willing to do whatever his new leader, the businessman, asks of him.</p>
					<p>So they accept, and are set loose on their first mission, capturing a nasty demonic beast serving to terrorize a demon dimension on behalf of the evil gods of that world, and bring it to be contained in a Powers-controlled hell dimension. Their missions like this continue for a while, fighting the forces of evil, but over time some of their missions become more morally ambiguous. The demons they are fighting sometimes seem to be innocent creatures merely opposed to occupation of their realm by the Powers. Eventually, at the witch's urging, they end up siding with an army of such native demons in revolt against the Powers occupying their realm; but that revolution is put down, and the natives beaten into submission. The protagonists are not punished per se, but they are warned that so far they are digging themselves in deeper and would be hell-bound should they die right now, so they had better shape up their act.</p>
					<p>Their next mission, coincidentally, is especially dangerous, and they barely pull through with their lives. Likewise, several immediately following that. At this point the physicist begins suggesting that they should just defect from the cause, run off to some obscure realm and hide out from the powers for the rest of their lives. The others are hesitant about that; after all, what happens when those lives are over, and then they're doomed to hell? But it's suggested that maybe they can find some way around that over time, but with the way the Powers are treating them now, they're more likely to die and go to hell sticking with the job than they are defecting. So they defect, and for some time are free, jumping from one obscure realm to another, evading the powers, and dealing with whatever problems come up along their way. However, after an encounter with a wild demon beast leaves the witch near death, during which time she finds herself temporarily in hell again, she pleads, upon returning to life, that she cannot bear the possibility of returning to hell again, and so dangerous or not, they have to continue their service to the Powers to save their souls.</p>
					<p>Over time, the nature of the multiverse begins to become more clear to them. Most everything is morally some shade of grey; the Powers, despite maintaining Heaven, do a lot of morally grey things on the outside to keep their paradise so perfect, and are thus far from perfect themselves. They are not beacons of pure light as they would like to portray themselves; and it doesn't seem like anyone else out there is either. However, even though there is no font of pure light in the 'verse, there is a being of pure darkness, the First Evil, and it has legions drawn into its servitude trying to snuff out whatever scarce light there may be anywhere. The Powers, for all their many flaws, are the greatest source of good out there, and the strongest opponents of evil there is to find. Our protagonists eventually grow comfortable in their service to the Powers, and learn how to fight the good fight and dodge the morally grey things they are sometimes asked to do without outright rebelling or defecting from their jobs.</p>
					<p>Eventually they come to realize that there is a great threat looming which their many smaller tasks are systematically designed to forestall. An alliance of evil demon gods from a variety of realms, the Old Ones who were banished from Earth millions of years ago, are rallying armies across the multiverse for a simultaneous assault on both Heaven and Earth, figuring the Powers will be unable to find off attacks on both fronts at once. As the deadline of the attack nears, our protagonists are informed that they have nearly earned their admittance into Heaven, and that one vital last mission will guarantee their place there. They are to sacrifice themselves in a special attack which somehow stop the evil forces' from being able to launch an attack on Heaven, saving the Powers and their blessed chosen few, while the Powers send other, more regular champions to defend Earth.</p>
					<p>However, the protagonists manage to twist their mission differently, calling on allies they have made across the worlds, the reputation they have made for themselves, and the tricks they they have learned, to instigate an uprising within the population of the enemy's worlds, who overthrow their gods and take control of their worlds for themselves. With this great turmoil suddenly thrown at their feet, the Old Ones are enraged, and refocus their forces from the attack on Earth and instead attack the Powers directly, which they are able to do because the protagonists did not complete their assigned suicide mission. In the chaos, our protagonists escape through a portal back to present-day Earth, intend both to slip away from the Powers' control and also to join the vanguard in the defense of Earth, which they care about protecting much more than they do about protecting the Powers. But because the Old Ones have turned their energy against the Powers directly, the attack on Earth never comes.</p>
					<p>When the dust settles, the Powers have defeated the Old Ones; but not evil itself, for against that we all must be eternally vigilant. The Powers' forces in the multiverse are weakened because of the hard fight, and they have ceded control of the Old Ones' realms to the native demon forces which rose up against their gods there, as those demon forces were instrumental in the defeat of the Old Ones, and the Powers don't really have the resources to argue otherwise at this point. The Powers have decided that our protagonists have fulfilled their debt sufficiently enough that they are no longer hell-bound, but that their little trick has burned up their credit toward heaven. Furthermore, they have proven themselves too much trouble to employ further, and so they are being released from their service. They may live out the remainder of their mortal lives here on Earth, and their souls will be treated after death according to their actions from this point forth. They have a clean slate.</p>
					<p>The protagonists discuss whether they should disband to the different times and places from which they have come. The businessman is home again, but they can send the warrior back to his home dimension if he wants, and then the physicist and the witch can travel to one's time and then send the other back to theirs. The warrior declines, as his tribe was destroyed before he joined this team, and they are his tribe now, so this is where he belongs. The witch declines, because her time was no great a time for a witch to live in; at least here she won't be burned at the stake for practicing her magic; and besides, she might unmake the others' existence and all that they have done if she went back to her time and made any kind of difference there. The physicist remarks that that's a funny thing, changing timelines, because the whole reason he was trying to come back in time in the first place was to bring warning to the forces of Earth about an invasion by evil interdimensional aliens which had occurred right around this time frame and seriously messed up the world in his timeline.</p>
					<p>So in the end they all stay on present-day Earth, alive, free from their service to the Powers That Be, and ever vigilant against the forces of evil.</p>

				</section>
	
<? require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
