<?php $title = "Harry Potter Foreknowledge &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2><i>Harry Potter</i> Foreknowledge</h2>
				
					<p class="description">How might the Harry Potter series have gone if the protagonists knew at the start all of the things they learned by the end?</p>

						<p>On his first day of his first year, after his first Defense Against the Dark Arts class, Harry approaches Professor Quirrel alone in the classroom and introduces himself with a handshake. Quirrel, unaware of the consequences, accepts Harry's handshake, and upon touching Harry dissolves into nothing, as in canon, to Harry's feigned shock. Harry uses this incident of the "unexplained and terrifying" death of Quirrel to get an audience with Professor Dumbledore, where he offers his explanation by way of the Penseive as he knows Dumbledore will never believe his words. He shows Dumbledore memories of his original timeline and the events which lead up to now, winning Dumbledore to his aid. They summon Snape and show him as well. Then, by Harry's plan, Dumbledore and Snape approach Cornelius Fudge in private and confront him with the incontrovertible proof by Penseive which even he would not deny. Under the pretense of being spurred on by Quirrel's death, the Ministry launches numerous "investigations" at Fudge's direction, arresting the Death Eaters on the loose (identified from Harry's memories) including Barty Crouch, Jr. (saving Mad Eye Moody from his future imprisonment), and freeing Sirius Black from Azkaban.</p>
						<p>Meanwhile, Harry leads Dumbledore into the Chamber of Secrets, opening it with his Parseltongue. While Harry remains safely concealed under his Cloak of Invisibility (at Dumbledore's insistence), Dumbledore uses Fawkes the Phoenix and the Sword of Griffindor, together with Harry's foreknowledge, to kill the Basilisk and imbue the Sword of Griffindor with the power to destroy Horcruxes.</p>
						<p>Soon thereafter Sirius Black returns from Azkaban and retakes possession of 12 Grimmauld Place. He is brought in on Harry's secret as well, and the plan to bring down Voldemort. With Black's help, a pretense is established that in clearing Black's name, Peter "Wormtail" Pettigrew has been implicated in his place, and the Ministry is now searching for a rat animagus. Under this presence, Snape confiscates Scabbers the rat from Ron Weasely, and in private forcibly returns him to human form. Snape tells him, as a fellow Death-Eater, that he has long known known what Wormtail's plans are, but with the action that the Ministry has taken spurred on by Quirrel's "unfortunate" death, plans must be accelerated. He tells Wormtail to travel to Albania where he will find Voldemort, and upon his return, Snape will bring Harry Potter to the grave of Tom Riddle, Sr., to offer his blood to resurrect the Dark Lord. Wormtail accepts the offer, and departs to Albania in search of Voldemort.</p>
						<p>While Wormtail searches for Voldemort, the Horcruxes are assembled and destroyed. Sirius orders Kreacher to turn over Slitherin's Locket, and then to Apparate to the locations Harry has provided and obtain the other Horcruxes: recovering Gaunt's Ring and Ravenclaw's Diadem from their hiding places, and stealing Riddle's Diary from Lucius Malfoy and Hufflepuff's Cup from Bellatrix Lestrange's vault using house-elf Apparation to bypass normal securities that would make those difficult to obtain. With the five Horcruxes now assembled, Dumbledore uses the Sword of Griffindor to destroy them. Harry keeps the Resurrection Stone from Gaunt's Ring as his reward for his efforts, so that he can visit his dead parents any time he likes; Dumbledore, recognizing Harry's worth, allows this.</p>
						<p>Before meeting Wormtail to complete the resurrection, precautions are set in place. Wards are set up around the graveyard to allow Apparation into it, but no Disapparation from it; and an innocuous Portkey is created, kept on Snape's person, to transport the holders to the safety of Hogwarts' Room of Requirement. Harry tells Dumbledore of his plan, and says he will need to borrow another's wand to complete them; and he is going to duel the most powerful dark wizard in the world, he will need the Elder Wand to succeed. Dumbledore accepts the need for this, and gives Harry the Elder Wand, making Harry, together with the Resurrection Stone and the Invisibility Cloak, the Master of Death.</p>
						<p>Wormtail returns, and Snape "abducts" Harry to complete the ritual required to resurrect Voldemort at Riddle's grave: a bone from Tom Riddle, Sr.; the blood of Harry Potter; and Wormtail's own hand. When Voldemort arises, and the remaining free Death Eaters Apparate, Snape makes a grand show of surrender Harry to Voldemort, including handing over Harry's wand, which Voldemort recognizes as his own wand's "twin". Voldemort laughs at Harry's defeat, plays up his own victory to the Death Eaters, and casts Avada Kadavera on Harry.</p>
						<p>Both wizards fall to the ground, as the Horcrux in Harry is destroyed. Voldemort stands again first, confused at what happened, and orders Snape to check that Potter is really dead. Snape checks, and falsely "confirms" that Potter is indeed dead. But as Voldemort and the Death Eaters cheer, Harry draws the Elder Wand from his robes and casts Fiendfyre at the snake Nagini, the final Horcrux. Voldemort and the Death Eaters attempt to Apparate away, but are unable. Snape puts the Portkey in his and Harry's hands and transports them to the safety of Hogwarts, as Voldemort and his few remaining Death Eaters are consumed by unstoppable fire over the grave of his Muggle father.</p>
						<p>The final report on the matter published by the Ministry is that Professor Quirrel was found to have been possessed by Lord Voldemort, and was unexpectedly destroyed by contact with Harry Potter due to the same deep magic which protected Potter as an infant; that spurred the Ministry's renewed investigations into the Dark Lord's affairs, which prompted Peter Pettigrew to redouble his efforts to resurrect the Dark Lord by way of Harry Potter; but thanks to Professor Snape's successful espionage of the Dark Lord's forces, and planning and intense training of Harry Potter by Professor Dumbledore, a trap was set which has defeated the Dark Lord and his followers once and for all. Dumbledore, Snape, and Potter are honored as heroes. The time travel is, of course, never revealed.</p>
						<p>In the aftermath, Dumbledore remains the renowned headmaster of Hogwarts. Snape is appointed to the post of Defense Against the Dark Arts teacher he has so long wanted. Harry lives with his godfather Sirius and never has to return to the Dursleys again; and with the Resurrection Stone he can at last visit with the parents he never knew. He goes on to befriend the Weasley family and Hermoine Granger, become a renowned Quiddich Seeker, and attends Hogwarts for seven long, uneventful years before eventually marrying his best friend's sister, Ginny Weasley, with whom he fathers his first son Albus Severus Potter.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
