<?php $title = "Smallville Foreknowledge &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				
				<section>

					<h2><i>Smallville</i> Foreknowledge</h2>
	
					<p class="description">How might the Smallville series have gone if the protagonists knew at the start all of the things they learned by the end?</p>

					<p>Through means unimportant to this story, Superman of the post-2011 era comes across a Kryptonian time crystal like that he used in early 2006, on the day of his father's death, and resolves to use it to travel back in time to set right the many wrongs that occurred in his youth due only to his own ignorance and error, things completely and easily avoidable with the benefit of hindsight and foreknowledge.</p>
					<p>Clark Kent arrives back in his bedroom at the Kent Farm, at the start of his freshman year of high school, the year that everything in his life began to change. He greets his parents, especially Jonathan, with warm hugs as he comes downstairs to the breakfast they've prepared, lingering especially long on his father. The superfluous affection prompts Jonathan to ask Clark what the occasion is, and he tells them that they had better sit down for it.</p>
					<p>Gathering his composure, Clark levitates slightly off the ground, demonstrating his mastery of his powers, and tells them that he has come back in time from over a decade in the future to set right what once went wrong, including saving Jonathan's from his death in a mere five years. He tells them his complete history that he has learned in the future: that he is from the planet Krypton, that his birth name is Kal-El and that his birth parents are Jor-El and Lara-El, that they sent him to Earth both to survive the destruction of their planet and also to be the savior of this one, a destiny he has fulfilled in the future from which he has returned, and which he intends to fulfill all the better this time around.</p>
					<p>He tells them that his only weaknesses lie in the meteor rocks, called Kryptonite, that fell to Earth with him, and the effects that each type of Kryptonite has on him. He asks for their help in building him a suit to protect him from that threat, as well as to disguise his identity, to keep both him and his loved ones safe in the adventures that are to come: a suit lined with thin sheets of lead inside, and both steel rings and kevlar outside to keep the Kryptonite from penetrating the lead; Clark's super-strength will be more than enough to bear the weight of it.</p>
					<p>He also tells them that he has a cousin who was sent to Earth to protect him, but that her ship was lost on arrival, though he knows where to find her; and that the mind of his birth father was also sent to guide him, but the key on which that mind was imprinted was lost in the field where his ship crashed. He tells them that he is going to go find his cousin, Kara, and that together they will find the key to his ship, and then both sides of his family can meet each other.</p>
					<p>That night, under cover of darkness, Clark travels to Reeve's Dam where he carefully unearths Kara's ship, and flies it to the Kent Farm where he hides it underground in the storm cellar, which he quickly digs out to a larger size to accommodate. Kara is awakened and emerges from the ship, and Clark brings her up to speed on the situation, introducing her to his Earth parents as well. He promises her that he will help to restore her father, and his own birth mother, from the crystal she brought with her, but that they first need to bring his own father's program online, and to that end he enlists her help in scanning Miller's Field with their x-ray vision for the Octagonal Key that activates his own ship.</p>
					<p>The key is found, and returned to the Kent Farm, where Clark, Kara, and the Kents gather around to see Jor-El reactivated. When the voice of Jor-El speaks, Clark explains himself yet again, and makes introductions all around. Jor-El is cautious and tries to dissuade "Kal-El" from his course of action, treating Clark still like a child in need of guidance, but Clark is forceful and insists that he has done this song and dance before and the conflict between them brought little but suffering to him and to the world, and that Jor-El would do best to cooperate, to offer insight and guidance to Clark in his plans, and desist with any patronizing tests and trials.</p>
					<p>To emphasize the point, Clark levitates again, as he insists that he has fully mastered his powers already in another life, and he knows very well what he is doing. He tells Jor-El -- without yet explaining to anyone else present, to whom it means little -- that he knows the location of the Orb, that Kara has a crystal serving a similar function for Lara and Zor-El, and that Dax-Ur is hiding here on Earth and Clark knows where to find him. He says that with Dax-Ur's help, the Orb, and Kara's crystal, Jor-El and Lara can live again in the flesh, the last survivors of Krypton can salvage what remains of their lost civilization, and that even his brother Zor-El and his best friend Zod can be returned and redeemed safely, if Jor-El will just cooperate. Hesitantly, Jor-El agrees not to impede Clark's plan, and to offer his guidance and wisdom to further his endeavors.</p>

					<hr />

					<p>But before any of those grand deeds can be done, Clark needs to ensure that he does not lose sight of his humanity. Many of his friendships, and his friends' very lives, were ruined by him trying to protect his secret, even as he did so out of their supposed best interest. So this time around, he's not going to make that mistake again. He continues going to school, where he befriends Chloe and Pete. This time around, knowing he is in full control of his powers, the Kents allow Clark to join the football team, where he also befriends Lana and Whitney. He volunteers to help Chloe as a reporter for the Torch, and when she reveals the Wall of Weird to him, he uses that as a springboard to begin creating his inner circle.</p>
					<p>He tells Chloe that he knows the origin of many of the cases on her Wall of Weird: mutations from the meteor rocks that fell in Smallville in 1989. Then he tells her how he knows this: that he himself was among the things that fell to Earth in 1989; that he is an alien, with superpowers himself, which he demonstrates by levitating before her. She is amazed, and asks if anybody else knows, and he says nobody besides his family, but that he also wants to share it with his closest friends; and he wanted her to know first.</p>
					<p>He asks her to gather Pete, Lana, and Whitney and bring them all to the Kent Farm that weekend. When they arrive, the Kents direct the kids down to the storm cellar where Clark is waiting for them, sitting on his space ship. When Lana enters, the ship neutralizes the Kryptonite in her necklace, providing an awe-inspiring introduction to the weirdness that Clark is about to explain to them all. He tells them not only his Kryptonian origins, but also about his time travel, and that he has come to save the world in general, but also to save them, his friends, especially.</p>
					<p>In particular, he warns Whitney of his own impending death in the Marines, which he would join after his father's death in the near future. He tells Whitney that when his father's health reaches a critical point, that he can bring him here to the Kent Farm, where Clark's birth father's technology will heal him. Whitney thanks him, and a bit overwhelmed, asks to step outside for a bit. Lana excuses herself to go with him.</p>
					<p>When they are gone, Clark tells Chloe and Pete that he was never that close to Whitney in his original timeline, that in fact they were erstwhile enemies and competitors for Lana, and that he brought Whitney into the circle more for Lana's sake than anything, because he wants Lana to live a happy and fulfilling life. Chloe asks Clark, somewhat wistfully, if he loves Lana, and Clark admits that he did, in another life, but that things didn't work out; and that though he could have used his foreknowledge to engineer this timeline in a way where he and Lana may have lived happily ever after, that would have required leaving Whitney in the dark to die a preventable death, and that Clark would never do something like that just to win a romantic conquest.</p>
					<p>Besides which, he says, he has always regretted never seeing what was right before him the whole time, at least before it was too late to matter; the only person who stuck with him through all his ordeals, the whole way, never wavering in her devotion to him: Chloe. She is moved to tears, and opening his arms to invite her into them, he says that he would like not to repeat that mistake this time around. They embrace, and Pete feels like an awkward third wheel and excuses himself to go check on Whitney and Lana. Clark asks him to bring them back in again whenever they are ready, because he has more to tell them all.</p>
					<p>Clark and Chloe share a minute alone, where he tells her that he almost feels like he's cheating at love, knowing how Chloe feels without her having to say it; but she's actually grateful not to have to say it, and just to have Clark even notice her. She asks him who he ended up with in his original timeline, if it didn't work out with Lana and he missed the boat on her. Awkwardly, he admits that it was her cousin, Lois. Chloe asks him why he would turn to her now instead of seeking to rekindle things with Lois; did he secretly lust after her the whole time he was with Lois in the future or something? Clark says that it was nothing like that, that he still remembers the person Lois became (or will become?) with love, but that it's different now that he's come back to the past. He hasn't even met Lois yet in this time, and what is he supposed to do, have Chloe invite her to visit Smallville, tell her that he's a super powered alien who's her husband in an alternate future that he's come back in time to change? How well, he asks, would Lois take that? He also says that time travel always has a price -- that the last time he used it, it cost him his father's life -- and that losing his future with Lois may be the price he has to pay to save everyone else. And besides all that, he tells her, they, Clark and Chloe, deserve the chance together they never got before.</p>
					<p>Pete, Lana, and Whitney return to the cellar, Pete cautiously leading with a "knock knock" in case any "funny business" is going on. Seeing that the coast is clear, he bids Lana and Whitney down after him. Lana is the first to speak, asking Clark why he brought them here and told them his secret. He tells them all that the reason is two-fold: one, he needs an advisory council, a circle of friends to keep him grounded in his humanity, to make sure that he never lets his power go to his head; and two, that he will need help in finding the people of Smallville, most of them teenagers just like them, who have been infected by the meteor rocks, who may pose a danger to themselves and to others, and whom he intends to save, or to save the world from, as the need may be. But, Clark explains, in order to do so, they are going to need the help of more powerful people; not powerful in the way that Clark himself is, but powerful in the world of human affairs; people like Lex Luthor.</p>

					<hr />

					<p>In the days leading up to Clark's fateful meeting with Lex Luthor on the Loeb Bridge, Clark contacts Professor Swan preemptively, who is surprised to learn that the Traveller, Kal-El, already knows about him. Clark tells the Professor that he knows all about Veritas, and that while the other surviving members of it, the Teagues and especially Lionel Luthor, cannot be trusted, he knows their children are all good people and would like them to form a new Veritas together with the Professor himself, to help him save the world. He asks Swan to summon both Oliver Queen and Jason Teague to a meeting at his office on October 16th, 2001, but under no circumstances is he to contact the Luthors about it; Clark will be bringing Lex Luthor himself.</p>
					<p>On the afternoon of the 16th, Lex swerves off the Loeb Bridge as in Clark's original timeline, but unlike the original timeline Clark Kent is not standing on the bridge to be hit; instead, a masked and armored Superman catches Lex's car out of the air, and returns it safely to the side of the road intact and unharmed. Lex is amazed, and steps out of the car to thank the man who has just saved his life. Clark shakes his hand when it's offered, and then, with some hesitation, takes off the mask and introduces himself. Lex asks why he even wears the mask if he's just going to show his face to everyone he meets, and Clark tells him that it's not everyone he meets: Lex is a special exception.</p>
					<p>Lex asks why him, and how did Clark know to be here to save him now? Clark explains that he is from the future, and that in that future, Lex was once his best friend, but later became his greatest enemy, in large part because Clark wasn't honest with Lex; so this time around, Clark intends not to make that mistake. Lex is suspicious, and asks why he should trust anything Clark says if they were once enemies. Clark says that in that timeline, he saved Lex's life here before, just by chance; and that this time around, Clark could have just left Lex to die, if he thought of him as an enemy. Clark says again that he has come back in time to save the world in general, but also his friends especially, and that he counts Lex among those friends. Clark says that there are other friends already gathered and waiting for Clark's arrival, some of whom Lex already knows, and that he would love to take Lex to see them and explain further. Clark offers Lex an arm, gesturing toward the sky with the other, and hesitantly, Lex allows Clark to fly him to Metropolis to meet with Professor Swan and the rest of "Veritas Jr".</p>
					<p>Landing on the balcony of Professor Swan's office, Clark and Lex enter the meeting already taking place between Swan, Oliver, and Jason. Lex and Oliver recognize each other from school, and are initially hostile, but Clark puts a stop to it and cues Professor Swan to begin the presentation. Swan tells them all about Veritas, about their parents' involvement in it, and about their search for Clark, Kal-El, or as they knew him, The Traveller, and the wealth of otherworldly knowledge he would be able to provide. Clark promises that that wealth of knowledge will be made available to the Veritas families, and that with it they will both grow their own riches as well as usher in a new golden age for mankind, but that before that work can begin, the children of the Veritas families here must come into their own, as their parents cannot be trusted. Clark cues Professor Swan to explain, and Swan tells stories of the backstabbing and duplicitousness of his erstwhile friends in Veritas, culminating in Lionel Luthor's murder of the Queens.</p>
					<p>At that, both Lex and Oliver are outraged, Oliver at Lex as a proxy of Lionel, and Lex at Oliver for the accusation against his family. But Clark intervenes, and says to Oliver that Lex is not to blame for the sins of his father; and asks Lex if it really seems beyond what his father is capable of? He tells Lex that the other thing that drove Lex to villainy in his original timeline was his dysfunctional relationship with his father, and that Lionel is the greatest threat to their plans. But that in that timeline, Clark saw even Lionel redeemed, just not soon enough to save Lex, and that Clark would see Lex's relationship with his father mended eventually. He mentions that Lionel believes Lex killed his brother Julian and hates him for that, and that though Lex can't remember it yet, the proof that he did not kill Julian is locked in his mind, and Kryptonian technology can help to recover it and mend his relationship with his father.</p>
					<p>But first, Lionel has to pay for his crimes, and be prevented from standing in the way of the great things they're all going to do together, and though there is no evidence available that can prove Lionel's murder of the Queens, there is evidence available that can prove an even greater crime that will put Lionel away for good: the murder of his own parents, together with Morgan Edge. Lex is aghast that his father is responsible for the death of the grandparents he never knew, and demands proof of this. Clark suggests that Oliver take point on that, as Clark knows that Oliver has "methods" that could "persuade" Edge to confess on tape, and that doing this for Lex could help mend their relationship, as well as punishing Lionel for the murder of Oliver's own parents.</p>
					<p>Oliver agrees, and the group disbands for the evening. Clark and Lex both stay with Professor Swan for the night, bonding further, and Lex has his car towed from Smallville to Metropolis to avoid raising suspicion back home. The next night the group convenes again, but Jason brings his parents with him this time. Clark is very upset about that, but Jason says he had to ask his parents about the truth of Veritas after hearing all this, to verify whether Lionel was really such a monster; and that they came out in overwhelming support of taking down Lionel, if it means working with the Traveller.</p>
					<p>Clark is unsure whether Jason's parents are completely untrustworthy or not, from his mixed experiences with them in the original timeline, but he is happy to have them helping press the case against Lionel. Oliver presents Edge's taped confession for the assembled group, and Lex resignedly accepts the truth about his father. Lex himself takes the evidence to the Metropolis police the next morning, knowing full well exactly who there cannot be trusted to act on it, and Lionel is arrested pending trial. Swan and the Teague parents give their testimony as to Lionel's character to the prosecuting attorney, who takes it from there, freeing Clark and Veritas to move on to grander things unimpeded by Lionel's scheming interference.</p>

					<hr />

					<p>Clark lays out a tripartite plan to save the world, through three organizations. The first, the Isis Foundation, is to be lead by Clark's parents, who Clark trusts to treat powered people with the appropriate balance of care and caution. It will be staffed by volunteers consisting primarily of his friends from Smallville. Its purpose will be to find people with unusual powers, whether caused by Kryptonite or otherwise, and help them to understand and control their powers; and if they should like, to remove them. Isis will also be the main source of referral to the other two parts of the plan.</p>
					<p>The second one, Black Creek, will be a containment facility, to be headed by Lex, who Clark knows is concerned with the protection of the world from extra-normal threats. Lex's operation will be supervised by Swan and Jason as a safety check. Its purpose will be to contain superpowered people who are a threat to themselves or others and will not work peacefully with the Isis Foundation to resolve their issues or cure themselves. It is to offer its containment services to a preexisting secret government organization called Checkmate, and through that relationship gradually infiltrate Checkmate and take control of it. This is necessary because Checkmate indiscriminately seeks to control all powered people without distinguishing between heroes and villains, and in doing so unwisely polarizes the world into a war of ordinary humans vs superhumans, a war that the ordinary humans cannot win, and shouldn't have to fight in the first place, when some of the super-powered people could be protecting humanity from the others who would hurt them.</p>
					<p>To that end, the final organization will be the Justice League, a society of superheroes, to be headed by Oliver, who Clark knows is already moonlighting as a superhero, the Green Arrow. To keep such a super-powerful group in check, it is also to be overseen by both Jason and Swan. Its purpose will be to use extra-normal abilities to protect the world both from other people with super powers, and from itself, and so serve as a kind of support group or advisory council to help super-powered individuals keep themselves and each other in check. Clark tells them that such an organization already existed once, the Justice Society of America, before it was forced to disband to hide from Checkmate, and that Oliver should seek out its members to join the new organization, assuring them that Checkmate is being handled and will soon be dissolved or merged into an organization that will cooperate with heroes such as themselves in protecting humanity together, rather than needlessly oppose them.</p>
					<p>Clark says that all three of these organizations should be jointly funded by the four Veritas families, the Swans, Teagues, Queens, and Luthors, through an independent foundation managed by someone with loyalties to both Queen and Luthor: Oliver's lost lover and Lex's estranged half-sister, Tess Mercer. She will also be instrumental to both Black Creek and the Justice League, as she is herself an inactive Checkmate agent and will be invaluable infiltrating them; and in Clark's original timeline she served valiantly as the central intelligence coordinator, or Watchtower, of the Justice League, a role that she can serve in this timeline as well. The funding foundation that Tess is to run will also be the route by which Kryptonian knowledge is meted out to the Veritas families for development into new technology for sale, as well as to the three organizations to help research, develop, cure, and contain super powers.</p>

					<hr />

					<p>But to get at that wealth of Kryptonian knowledge, Clark will need first to reunite the Stones of Power into the Crystal of Knowledge, and then, to resurrect what remains of his people in order to understand and explain the knowledge contained therein. Clark knows that Swan has one of the Stones already, and encourages a trip to Smallville, where caves sacred to the native Kawatche tribe hold the key to reuniting the Stones. The group travels there, and at Clark's direction, Swan fixes the first Stone into place within the caves, as unlocked by Clark's octagonal key. Clark says that he knows the location of the other two stones, and that he will take Lex, Jason's father Edward, and his friends Chloe and Pete, on a mission to retrieve one of them from Egypt; while Clark's Kryptonian cousin Kara, who arrives at the caves on cue, will take Oliver, Jason's mother Genevieve, and Clark's friends Lana and Whitney to retrieve the final stone from China.</p>
					<p>Clark's expedition to Egypt goes easily and uneventfully, successfully recovering the Stone of Fire, and Clark solidifies both his friendship with Lex and his relationship with Chloe. But as Clark expected, tensions arise when Genevieve and Lana are on the same trip together, as Lana is taken over by the spirit of her witch ancestor Isobel, who Genevieve's ancestor the Duchess Gertrude had burned at the stake, and Isobel attempts to murder Genevieve in revenge. But Kara and Oliver, acting on advance intel from Clark, are able to use the recovered Stone of Air to drive the spirit of Isobel from Lana and save Genevieve.</p>
					<p>Both parties reunite at the Kawatche Caves, and place their respective Stones into the altar there. The entire group are then transported to the arctic, Clark bearing the reformed Crystal of Knowledge, which he throws into the distant snow; and they witness the birth of the Fortress of Solitude, which will be the home base for the resurrected Kryptonians, and the font of knowledge that will save the world and usher in a new golden age for mankind. Inside the Fortress, they speak to Jor-El, who praises Clark for his masterful accomplishments thus far, thanks everyone else for their support of his son, and then transports the group back to the Kawatche Caves.</p>
					<p>The Teagues are upset that that was all, as they expected to be given the knowledge of the cosmos, and Clark explains that the voice they were just speaking to was not his actual father, but was an AI created in the image of his father, who can barely be reasoned with and would certainly never hand out Kryptons's greatest secrets to mere humans. But, he adds, his real birth parents would be more reasonable, and they can be resurrected, with the aid of another Kryptonian artifact that Veritas have long had in their possession (which, Clark informs them, is not, as they have heard, capable of controlling him, but in fact it has only the ability to depower him, and even that is easily reversed), plus another that Kara brought with her, and the aid of a Kryptonian in hiding on Earth, named Dax-Ur.</p>
					<p>Kara and Oliver are sent to accompany Edward to St. Christopher's Cathedral in Montreal, where Edward had been hiding as a monk for years until Jason reached out to him just recently, and where the Key to the Orb was hidden long ago. Meanwhile, Clark takes Lex and Genevieve to the Luthor Mansion where Clark locates and Genevieve recovers the Orb itself, as Clark is still haunted by memories of the last time Lex held it and doesn't want to take any chances this time. The Orb and its Key are delivered separately to Professor Swan, who reunites them and delivers them to Clark at the Kawatche Caves, where he takes it alone to the Fortress of Solitude.</p>
					<p>Meanwhile, Kara steals the Shield of Dax-Ur from the Smallville Time Capsule and, using it to locate the scientist, implores him to visit the Fortress of Solitude to use the Orb and her own crystal to restore her father, Clark's family, and the last remnants of Krypton. She assures him, on Clark's word, that the Orb has neutralized the powers of all those stored within it, which assuages many of Dax-Ur's concerns about unleashing an army of super-powered Kryptonians on Earth. He agrees, and travels with Kara to the Fortress, where he speaks with Clark and the voice of Jor-El, and begins his work to resurrect the Kandorians within the Orb, reunite Jor-El's mind in the Fortress with his younger self inside the Orb, to restore Lara and Zor-El from Kara's crystal but stripped of their powers like the Kandorians, and to plan for the containment of dangerous Kryptonians like Zor-El and Major Zod.</p>

					<hr />

					<p>Over the next four years, everything continues according to plan. Clark and friends work together to find the meteor infected around Smallville and usher them into the Isis Foundation, where the Kents and the team of scientists under their command help them learn about and control their powers.</p>
					<p>Those who are too dangerous are sent to Lex to be contained until they can be depowered, and over the years Black Creek successfully infiltrates Checkmate until Tess is their new White Queen. Those who show great promise, meanwhile, are introduce to Oliver and inducted into the Justice League, which gradually incorporates the members of the old Justice Society as well, all under watchful guidance of Tess as Watchtower.</p>
					<p>Tess and Jason, each having their fingers in all three super-pies and so working with each other all the time, gradually develop feelings for each other and get together. Lex and Oliver remain playboys for many years, but eventually find stable relationships of their own. Lex recovers his memories of Julian's death, and that begins the process of his reconciliation with his father, still in prison. Oliver can never forgive Lionel for murdering his parents, but takes a kind of satisfaction in knowing that he's helped turn Lionel's own son from his dark path and made him a person worth considering a friend.</p>
					<p>Dax-Ur successfully restores the Kryptonians, and Clark and Kara finally have both of their families, the Kents in Smallville and the House of El in the Fortress of Solitude. The Kryptonians, lead by the same House of El of course, slowly and cautiously feed advanced knowledge to the human scientists who work for the three organizations and the four Veritas families.</p>
					<p>Zor-El and Major Zod are imprisoned and gradually reformed within the Kryptonian settlement in the arctic. Because the Book of Rao was never used to send them to another world, Darksied is never able to enter the world through the rift that it would have created.</p>
					<p>One of the first cases for the Isis Foundation is Davis Bloome, a.k.a. Doomsday, the two of whom are split from each other with Black Kryptonite and sent their separate ways: Doomsday is imprisoned deep beneath the Earth by the Black Creek team, and Davis is welcomed into the Justice League as their in-house medic, as well as being introduced to his unknown Kryptonian parents, Zod and Faora. Davis and Faora gradually become close family to each other, and together they are instrumental in rehabilitating Major Zod.</p>
					<p>Clark and Chloe remain together throughout high school. Things get awkward when Chloe's cousin Lois moves to Smallville in their senior year, as Clark experiences some wistful longing discomfort in her presence, but he remains faithful to Chloe. There is further awkwardness when the couple both intern at the Daily Planet over their winter break, where they meet Jimmy Olsen, who has the hots for Chloe but puts the breaks on it out of respect for Clark, who informs Chloe that she ended up marrying Jimmy in his original timeline, though it ended in Jimmy's death. Awkward. Later that year, Clark and Chloe narrowly beat out Lana and Whitney in the competition for Prom King and Queen.</p>
					<p>At their high school graduation commencement in 2005, a second meteor shower reaches Earth on schedule, but with the power of the Fortress and all the knowledge of Krypton it is easily prevented, and with it the arrival of the Black Ship carrying Braniac and the Disciples of Zod, thus preventing the release of General Zod from the Phantom Zone, the imprisonment of Clark there, and the escape of all the Zoners and Phantoms with him, including Bizarro.</p>
					<p>After graduation, Clark, Chloe, and Lois all begin work at the Planet, where Jimmy puts the moves on Chloe's hot cousin, whom both Clark and Chloe encourage to reciprocate, for the irony if nothing else. Those two are eventually brought into Clark's inner circle as well, the four of them forming the core intel and promo team of the Justice League, being on the pulse of Metropolis and the public voice of it, working together at the Planet.</p>
					<p>Pete and Kara gradually develop a relationship with each other, and end up working together at Black Creek containing the most dangerous of prisoners with Kara's super-strength and Pete's moral support. And Lana and Whitney remain the happy small-town couple in Smallville, continuing their volunteer work with the Isis Foundation and slowly working toward taking it over for the Kents, as Jonathan begins his bid for State Senator.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
