<?php $title = "How Star Trek Enterprise Should Have Gone &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2>How <i>Star Trek Enterprise</i> Should Have Gone</h2>
				
					<p class="description">Remixing the best elements of the series into a stronger finish with connections to the classic shows.</p>

					<p>In this reimagining of <i>Star Trek Enterprise</i>, the Temporal Cold War is a war between the 27th-century Federation and the Mirror Universe Dominion of the same time frame. The struggle is primarily to determine the course of 22nd-century history: whether the Humans unite the Vulcans, Andorians and Tellarites together against the Romulans and form the Federation (as in the Primary Universe), or whether they conquer them and form the Empire (as in the Mirror Universe). The war is "cold" because the 27th-century Primary Federation can more easily detect large changes to the timeline and respond before those changes propagate to their own timeframe, so the Mirror Dominion make only small changes to the timeline in hopes that they may pass undetected and slowly unmake the Primary Federation.</p>
					
					<section>
						<h2>Season 1</h2>
						<p>Season 1 begins as canonically with an incident with the Klingons. However, diverging from canon, most of Season 1 focuses around stabilizing relations with them, with the Klingon encounters from later canon seasons moved into this season. The Augments plot arc and its aftermath amidst the Klingons takes place in this season as well. Mysterious shapeshifters taking orders from the future play a role as in canon, but rather than genetically-modified Suliban, they are Changelings from the future Mirror Universe Dominion. By the end of the season the Temporal Cold War is revealed, and Archer learns from Daniels that the Changelings are the leaders of their enemy, hiding amongst the various races of this timeframe in order to disrupt history. However, Daniels' agency in the future has agents hiding in the past as well, not only amongst humanity but amongst many other races, including the Klingons, with whom humanity is at peace in his future. One of these future Klingon temporal agents is instrumental in stabilizing relations between Humans and Klingons back to their historical status quo: Klingons threatening war upon any further interaction with humanity, and Humans therefore carefully avoiding Klingons at all cost.</p>
					</section>
					<section>
						<h2>Season 2</h2>
						<p>Failing to stir up that trouble successfully, the Changelings instead attempt to sew discord between the founding races of the Federation, beginning with the Vulcans and Andorians, in Season 2. This process has been ongoing for some centuries, and it is revealed by Daniels that the origins of the mutual distrust between Vulcans and Andorians was Changeling-enacted duplicity on both sides. Enterprise becomes involved in mediating these long-running disputes as in canon, resulting in the earliest truces between the founding races. The Mirror Dominion thus becomes indirectly responsible for the formation of the very Federation whose formation they are trying to prevent. By the end of this season an Andorian liaison has joined the crew of Enterprise as a technical advisor, and begun making advancements to their technology, bringing it closer to canon Original Series levels, such as primitive energy shields, which would prove invaluable in later seasons.</p>
					</section>
					<section>
						<h2>Season 3</h2>
						<p>After a sudden unexpected attack on Earth (as in the canon Xindi attack), Season 3 has the Enterprise travel through the "Delphic Expanse" in search of the origins of the attack, and presumably the Changelings, which lie toward the Gamma Quadrant. They follow the trail as far as Bajor and the trail goes cold. It is implied to viewers, but not to the Enterprise crew, that the Changelings are travelling back in time and across universes via their version of the Bajoran wormhole, with the help of the Mirror Universe equivalent of the Prophets, which the Primary Universe Bajorans know as Pah Wraiths. Travelling beyond Bajor blindly, they enter Cardassian space. In lieu of the canon Xindi are a loose economic alliance of Cardassians (in lieu of Reptillians), and neighboring species: the Breen (in lieu of Insectiods), Ferengi (in lieu of the Primates), and the Bajorans. Lead by the Cardassian civilian government, the Detapa Council, following the depletion of Cardassia's natural resources and downfall of the Hebitian culture, the Cardassians have traded their superior technology and cultural relics for raw resources, and trade resources between the four other worlds to their economic advantage. But this otherwise peaceful Cardassian alliance inexplicably harasses Enterprise while its crew explore their space; and when it is eventually learned that the attack on Earth was a secret Obsidian Order operation, Enterprise almost begins a war with the Cardassians.</p>
						<p>But while in Cardassian space, Enterprise has discovered the network of Spheres, which as in canon are creating the Expanse and transforming it; but unlike canon, their purpose appears to be to create a vast morphogenic field, and transform all matter in the every-growing Expanse into fluidic Changeling matter. The Obsidian Order have been informed by their future Mirror Universe counterparts that this series of events, which will destroy Cardassia, is the fault of "Terrans", and they have been instructed to build a weapon to destroy Earth and prevent this catastrophe. But one Cardassian commander, implied to be another member of Daniels' future agency, covertly aids the Enterprise in destroying the Sphere network, thereby convincing the Detapa Council and Central Command that Humans are not a threat. The Obsidian Order launches its weapon anyway, but with the aid of the the Bajorans and Ferengi, it is destroyed before reaching Earth. However, the loose Cardassian alliance is shattered in the political turmoil surrounding humanity's intervention, the Detapa Council is almost completely disempowered, and though the Obsidian Order is thereafter barred from possession of directly offensive military technology, it is implied that Cardassian Central Command will go on to attempt to subjugate its neighbors and become the Cardassian Union known from later centuries.</p>
					</section>
					<section>
						<h2>Season 4</h2>
						<p>In Season 4, Enterprise returns to find that the delicate relations between Vulcans and Andorians have been destabilized by apparently unprovoked attacks from both sides, each claiming to be retaliation for similarly unprovoked attacks. The Tellarites are further involved, with similar mutual claims of unprovoked attack between them and both the Vulcans and the Andorians. As in canon, this is discovered to be due to Romulan duplicity, and the four races of Humans, Vulcans, Andorians, and Tellarites set aside their differences to deal with this mutual threat. Unlike canon, there are further complications in settling that the Romulans are at fault, as apparent collaborators of each race are discovered working with the Romulans against their respective former enemies. These collaborators turn out to be Changeling infiltrators, but with no proof to show, nobody is willing to accept that explanation, and the collaborators have to be excused as fringe elements within each race's government, and not representative of their people as a whole, by plain old-fashioned diplomacy.</p>
					
						<p>In the end, the four founding races still unite into a proto-Federation alliance against the Romulan Star Empire. But on the eve of the Romulan War, the Changeling infiltrators try to broker a fake peace between the proto-Federation and the Romulan Empire, with the aim of the Romulans betraying the proto-Federation, thus preventing their future existence. After much difficult deliberation, the four founding races tentatively agree to peace talks; but the Enterprise, acting on faith of Daniels' temporal intelligence, makes a difficult decision to betray that false peace, initiating the Romulan War and securing that history as recorded happens. In the aftermath, it is discovered that the humans orchestrating the peace with the Romulans were themselves actually agents of the future Dominion; but they are not Changelings, they are actual Humans, who are proud, leading members of the Dominion in the Mirror future.</p>
					</section>
					<section>
						<h2>Season 5</h2>
						<p>Season 5 begins when Daniels unexpectedly loses contact with his agency due to a temporal incursion some time between the 22nd century and his time. His last information indicates that multiple temporal incursions are occurring at key junctures across history, and all field agents are being ordered to highest alert. When Daniels loses contact with his agency, he examines the quickly-changing timelines, and is forced to act quickly and remove Enterprise from its timeline before its very existence is unmade. They instead travel over 200 years into the past, to the event which lead to the unmaking of history as they knew it: Mirror Universe interference in our World Wars, leading to a Nazi invasion of the United States (as in canon "Storm Front"). Though with Enterprise's help the Mirror Universe insurgents are stopped, the damage to the timeline is already done; and there is evidence that other temporal incursions earlier in history have already been successful, leaving the world in a state subtly but substantially different from our Earth of the time. Following episodes showcase the evolution of the subsequent timeline into the Mirror Universe itself (as in canon "In A Mirror, Darkly"). With power only for one more temporal jump without aid from his (now-nonexistent) future agency, Daniels takes Enterprise back to the earliest of the temporal incursions in hopes of unmaking all the rest. </p>
					
						<p>Travelling nearly two thousand years further into the past, they find Mirror Universe insurgents masquerading as gods of the Roman Empire with their "magical" technology, spurring them on to greater conquest than in our history. (It is insinuated, in a nod to canon TOS "Who Mourns for Adonais?", that the actual Greco-Roman gods did once exist, and were extraterrestrial in origin, but have since moved on and abandoned Earth). Daniel's timeline-examination technology shows that this incursion, together with other temporal incursions over the next two millenia, ensures a continuous reign of power from the Roman Empire through the Holy Roman Empire to the Third Reich, leading to the eventual conquest by Nazi Germany of the United States and from there, all of Earth, leading to the Terran Empire of the Mirror Universe. By stopping the temporal insurgents in this time frame, they are able to branch a timeline in which the Federation as it was comes to be again, and Daniels' temporal agency is able to return Enterprise to its own time. Daniels assures the crew that his agency will take appropriate actions against the other temporal incursions at other times. When Archer asks how the Mirror Universe still exists if they just unmade their history, Daniels explains that time travel isn't quite that simple.</p>
					</section>
					<section>
						<h2>Season 6</h2>
						<p>In Season 6, as the Romulan War begins, the Enterprise crew investigate human agents of the future Dominion which have infiltrated Starfleet itself, who aim to pervert it into becoming the Terran Empire of their own universe by spreading xenophobia. They sew the seeds of Section 31 in the early Federation, which unbeknownst to them becomes, centuries later, the first part of the Federation to use time travel technology to protect their own timeline, and the seeds of Daniels' temporal intelligence agency which is fighting the future Dominion's agents. Thus, the human infiltrators cannot be stopped entirely, for to prevent Section 31's existence would unmake the Primary Federation's side of the Temporal Cold War. Section 31's attempt to turn Starfleet dark is prevented, but they are left as a hidden, festering seed inside the blossoming Federation.</p>
					
						<p>During season 6, Imperial agents cornered by Archer reveal to him why they are doing what they are doing, why humans would act seemingly counter to what Archer perceives as all our collective interests. The Imperial agents reveal the history of the Temporal Cold War from their perspective:</p>
						<ul>
							<li>
								During the 23rd century, the first incursion of the Primary Universe into the Mirror Universe occurred, when the senior staff of the NCC-1701 <i>Enterprise</i> were accidentally transported onto said ship's Mirror equivalent. The aftermath of this incursion lead to major peaceful reformation in the Terran Empire under new Emperor Spock.
								This left the Empire militarily weakened, leading to defeat by an alliance of some of their Alpha and Beta quadrant enemies, including the Klingons, Cardassians, and Romulans. The Alliance became the dominant power of the Alpha and Beta quadrants, took the Empire's slaves as their own, and dominated the Terrans.
							</li>
							<li>
								During the 25th century, the second incursion from the Primary Universe occurred, when the crew of <i>Deep Space Nine</i> accidentally transported to its Mirror equivalent. This lead to a Terran Resistance under Mirror Benjamin Sisko, which sought to take down the Alliance and free the subjugated Terrans.
								That Resistance in turn contacted the Dominion of the Gamma quadrant, who then conquered the Alliance, placing Terrans back in power as the Dominion's regents.
							</li>
							<li>
								"Now", in the 27th century Mirror Universe, the Dominion, spanning the near Gamma, Alpha, and near Beta quadrants, is facing an implacable, overpowering enemy from the Delta Quadrant called the Borg, who they are losing the war against due to a resistance movement amongst the subjugated non-Terran races of the Alpha and Beta quadrants (such as Klingons, Cardassians, and Romulans), who somehow would prefer Borg rule. The Mirror Dominion thus initiated the Temporal Cold War in an attempt to smooth over the history of the Empire/Alliance/Dominion by preventing the formation of the Primary Federation and thus preventing its disruptive incursions into their own timeline, allowing the Terran Dominion to continue unabated and keep the rebellious traitors in the Alpha Quadrant from sabotaging the war against the Borg.
							</li>
						</ul>
					</section>
					<section>
						<h2>Season 7</h2>
						<p>During Season 7, at the height of the Romulan War, Archer begins to feel morally ambiguous about everything, given what he has learned from the Mirror Universe's human agents, and about how Daniels' agency descends from Section 31; he feels like he's being forced to choose between two evils. To soothe him, Daniels tells Archer his side of future history:</p>
					
						<ul>
							<li>
								Although throughout the 23rd century the Federation did have its own conflicts against the Romulans, Klingons, and Cardassians, by the 24th century, while the Mirror Universe's Terran Empire was being conquered by the many enemies it had made, the Primary Universe's Federation began signing treaties with them instead, building lasting alliances which Archer has witnessed with their agents amongst the Klingons and Cardassians. So the Primary Universe history is better even just for Humans, despite the Empire's xenophobic Human-supremacism.
							</li>
							<li>
								In the 25th century, while the Terran Resistance was siding with the tyrannical Dominion in order to reconquer the Alpha and Beta Quadrants from the Alliance, the Federation and its allies (those former enemies including the Klingons, Cardassians, and Romulans) rallied together to ward off the Dominion's invasion, and instigated major reforms within the Dominion, leading to a union between them and the Federation Alliance by the 26th century. So the Primary Universe's history is also better for everyone else.
							</li>
							<li>
								"Now", in Daniels' own 27th century, his Federation (now spanning the Alpha and near Beta and Gamma quadrants) is fighting a war against the Borg as well; but because of the strength of their mutual peace and spirit of cooperation, the Primary Universe Federation is winning the war against its Borg, unlike the Mirror Universe. So going down the Mirror Universe path would be bad for everyone all around.
							</li>
						</ul>
					
						<p>Archer's concerns are assuaged and they continue pressing the war against the Romulans, Temporal Cold War issues seemingly set aside now. The Enterprise leads an alliance of the Earth Starfleet, the Vulcans, the Andorians, and the Tellarites, in a final push against the Romulans. But in the climactic final battle, the temporal war unexpectedly becomes "hot" when the Primary Borg of the 27th century learn of the Primary Federation's efforts in the Temporal Cold War, and make their own, more blunt temporal incursions in a similar attempt to prevent their defeat in the Primary Universe. The Primary Borg's temporal incursions prove too great to counter; the fledgeling Federation and Romulans both are assimilated by the future Borg. Thanks only to Daniels' last-minute intervention, the Enterprise escapes the destruction by fleeing through time to the 27th century, only to discover the timeline has been altered, the Federation hasn't existed since the Borg invasion of the Romulan War, and the entire galaxy is now dominated by the Borg. Daniels brings the Enterprise back to the 22nd century again, in the aftermath of the devastating battle with the Borg, to try to find some way of stopping them and fixing their future.</p>
					
						<p>But meanwhile, in the Mirror Universe, the Mirror Borg have defeated the Mirror Dominion in their own 27th century, only to find their victory suddenly undone after the Primary Federation's incursions into the Mirror Universe are undone by its nonexistence. Thus discovering the Temporal Cold War, the Mirror Borg travel back in time to defeat their counterparts in the 22nd century, where they encounter the Enterprise at the scene of the last battle. Initially terrified of a second wave of Borg, the Enterprise crew quickly learn that the mirror Borg more closely resemble the Primary Universe's Federation than anything else: valuing diversity and harmony and seeking to assimilate the best of all cultures, species, and technologies together in the mutual pursuit of perfection. Enterprise guides the Mirror Borg to locate the Primary Borg and defeat them before they can cause any further damage.</p>

						<p>Following so closely on the tail of the Romulan War, the fireworks and debris of the battle between the Borg is lost in space and unrecorded by history. The devastating annihilation of both Federation and Romulan fleets prompts the establishment of the Neutral Zone and the end of the Romulan War, as recorded by history. However, the Enterprise is recorded by history to have been destroyed in that battle, so their absence from further history is required; to fix this problem, Daniels brings them back to the 27th century, where they are able to witness the distant fruits of their labor, as the future Federation celebrates victory over both their Borg and the Mirror Dominion. In the aftermath of all this, the Primary Federation and Mirror Borg become allies across the universes.</p>
					</section>

					<p>Following this series, the classic Star Trek series' may be reimagined for temporal and thematic consistency. These modifications can be interpreted as changes to history due to the temporal meddling described above, or as a simple reimagining from whole cloth.</p>
					<ul>
						<li>
							<strong>Star Trek Alpha</strong> recaps the events of <i>The Original Series</i>, <i>The Animated Series</i>, and the <i>Original Series</i> movies, in the 23nd century.
						</li>
						<li>
							<strong>Star Trek Beta</strong> recaps the events of <i>The Next Generation</i> and the <i>Next Generation</i> movies, in the 24th century.
						</li>
						<li>
							<strong>Star Trek Gamma</strong> recaps the events of <i>Deep Space Nine</i>, but recast in the 25th century. The gradual formation of an alliance organization between the Federation, Klingons, Cardassians, and Romulans mirrors the foundation of the Federation itself, and the Dominion War solidifies it just as the Romulan War solidified the foundation of the Federation.
						</li>
						<li>
							<strong>Star Trek Delta</strong> recaps the events of <i>Voyager</i>, but recast in the 26th century, and <a href="startrek-voyager">with other changes</a>.
						</li>
					</ul>

					<!--Random note: The precursor aliens that seeded all humanoid life, the Bajoran Wormhole Aliens, the gods of the various humanoid species (e.g. Apollo, etc), "God" (who needs a starship) in the center of the galaxy, and the Q, are all the same race, in different stages of their development. Integrate this into the plots of Beta and Delta, somehow work it in with the rest of the story? -->
					
				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
