<?php $title = "How Star Trek Voyager Should Have Gone &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2>How <i>Star Trek Voyager</i> Should Have Gone</h2>
				
					<p class="description">Bridging the early Ocampa plot better with the later Borg plot, and tying the whole thing closer together with Deep Space Nine's Gamma Quadrant.</p>
					
					<p>
						Rather than being unexpectedly picked up by the Caretaker Array and dragged across the galaxy, the Voyager crew find their way into the Delta Quadrant thanks to a Maquis team, lead by B'Elanna Torres, attempting to surreptitiously access the Borg transwarp network, to gain a strategic advantage in their conflict with the Federation. As Voyager pursues the Maquis ship, B'Elanna successfully engages her transwarp drive, opening a conduit into which Voyager follows the Maquis, through a maze of twisting passages, avoiding traveling down those in which sensors show Borg craft, ending up dumping them out in a remote region of the Delta Quadrant: the Ocampa system.
					</p>
					<p>
						 Their traversal of the transwarp conduit alerts the Borg, who send a single Sphere to follow them there, threatening a battle that Voyager and the Maquis together could not hope to win. It is B'Elanna who makes the decision that strands everyone in the Delta Quadrant, by using her fledging transwarp technology to destroy that transwarp conduit and  the Maquis ship with it, cutting off the Borg's route of attack, but leaving the Maquis at the mercy of Voyager for their survival, and all of them stranded in the Delta Quadrant with no means of return. Realizing how hopelessly far from any known help they are, Janeway initiates contact with the Ocampa on the planet where they happen to find themselves.
					</p>
					<p>
						The Ocampa appear to be technologically primitive and so of little help to the stranded Voyager's crew and prisoners. But as they prepare to leave and begin the long trek home alone, they are approached by some of the Ocampa, who are very concerned about Voyager's appearance through a Borg transwarp conduit, and want to know what they are doing in this part of the galaxy and what their affiliation is to the Borg. Surprised to learn that these primitives know about things like transwarp and galactic political factions, and making clear that they are enemies of the Borg who found their way here by accident, the crew of Voyager are informed that the Ocampa were once a telepathically advanced species who travelled the stars and ruled over and provided for the other species in this region of space without the use of technology, turning every inhabited world in their domain into a garden paradise with their mental powers, incidentally inhibiting the development of technological civilizations along the way by making it simply redundant with what they provided.
					</p>
					<p>
						They were eventually targeted by the expanding Borg, long ago, and in defense put forth the illusion of destroying themselves rather than be assimilated, abandoning space and retreating underground on their homeworld, leaving a region of space of no interest to the Borg, because its inhabitants were so primitive. That is why they are so concerned to see a ship, after all these ages, emerge from the transwarp conduit that the Borg have ignored since those ancient times. After assessing Voyager's crew and their story, the Ocampa assign Kes to accompany them on their travels back home, for several reasons. Firstly, she is to look out for the interests of the Ocampa and others in this region of space, by advising the crew of Voyager on local affairs and guiding them out of screwing anything up. Secondly, she is to serve as ambassador between the Ocampa and the Federation, with whom the Ocampa wish to eventually establish diplomatic relations. 
					</p>
					<p>
						So Voyager sets off for home, and for several years ventures through a vast primitive region of the Delta Quadrant, encountering peoples and problems very closely mirroring those of the first few seasons of the canonical show, with some slight differences. As in canon, Voyager is, though stranded and outnumbered by the various locals, far ahead of the locals technologically. Furthermore, having an Ocampa on board now helps Voyager to eventually establish relations between and amongst the Kazon and other local races in that part of the Delta Quadrant, who remember the Ocampa as near-mythical figures from a bygone golden age.
					</p>
					<p>
						But as season 3 unfolds, Voyager finds itself making its way to the edges of the vast primitive region formerly occupied by the ancient Ocampa civilization, into regions now patrolled or even controlled by the Borg. As Borg threats increase, Voyager is forced to skirt the edges of Borg space as best as possible, through what they dub (as in canon) a "northwest passage" of minimal Borg activity, until they discover the reason why Borg are so scarce in that region: an enemy capable of fighting the Borg toe-to-toe, whom the Borg dub Species 8472. And at the start of season 4, as in canon, the Voyager crew find themselves forced into an uneasy alliance with the Borg against the even more threatening enemy, who they aid with the use of 29th-century technology adapted from the Doctor's mobile emitter to enable Borg nanoprobes to effectively attack their common enemy. After that alliance falls apart, as in canon, they end up taking Seven of Nine aboard as a new crew member; although, unlike in canon, Kes does not leave the crew at this point but rather, after making a life-threatening exertion of psychic power to extract Voyager from the conflict into a more distant region of space, she continues on with Voyager for the remainder of their journey.
					</p>
					<p>
						Also unlike in canon, the race that the Borg call Species 8472 are not from some kind of other dimension, though the Borg still describe them as being from "fluidic space". Little do the Voyager crew know, however, that the apparently normal, peaceful region of space into which Kes has flung them <em>is</em> the region that the Borg called "fluidic space", and despite all appearances, it is inhabited entirely by those the Borg call Species 8472, though the inhabitants of that region look nothing like the warriors fighting the Borg back on the periphery of the "northwest passage". This is because, as Voyager eventually discovers on a planet that they visit late in season 4 (after the season generally goes according to canon), this region of space is inhabited entirely by Changelings, who compose not only the inhabitants of the planets but the very material of the planets themselves, whole diverse worlds living out the lives of different races of "solids" for the sake of the experience, "reincarnating" as different parts of different worlds to experience different "lifetimes" as different kinds of beings.
					</p>
					<p>
						The "8472" that were fighting the Borg were merely a specialized combat form of the shape-shifting Changelings designed to meet the Borg threat, and it is that shape-shifting nature that made them impossible to assimilate, until Voyager's 29th-century technology adaptations to Borg technology overcame that. Since fleeing the battle between the Borg and "8472" at the start of the season, the "8472" have been trying to track down Voyager deep in the heart of their "fluidic space", the peaceful inhabitants thereof acting out their lives as "solids", never breaking character, assuming Voyager to be others like them doing the same, until the warriors show up in pursuit. Janeway must carefully negotiate with their pursuers to prove that they are not a threat to them generally, and are certainly not general allies of the Borg, pointing to the various good deeds that they have done throughout the region over the course of the previous year, not even knowing they were dealing with the "8472", as evidence of their peaceful intentions.
					</p>
					<p>
						Even once no longer directly under attack by the "8472", the Voyager crew are generally very uncomfortable about the fact that every person and even every rock on every planet in all of the space they have to travel through are all made of Changelings, especially when they learn how this part of space got this way. This region of space was long ago settled by a diaspora of Changelings, who would travel as individuals through space under their own power (as seen in Deep Space Nine), find new worlds, take the form of the natives, live amongst them, learn their ways, and learn everything there is to know about them, by being them. Some of them would breed with the locals, and their children, though born in the form of their solid parents, would have the latent ability to shape-shift, and so that ability would spread through the populations of these worlds. And these Changelings are not so unlike the Borg themselves in a way: as hinted at in Deep Space Nine where the Founders are able to turn Odo into a solid and then turn him back into a Changeling again, Changelings are able to convert ordinary solid matter into Changeling matter, and vice versa. In time these Changeling children, born of solids, would breed new Changelings by converting the other animals, plants, and the very rocks of the world themselves into living Changeling matter, in a way "assimilating" entire planets on a molecular level. Some of the Voyager crew are worried that they're going to be turned into Changelings, despite the Changelings' assurances that there are no such intentions. However, one minor member of the Voyager crew turns out to have actually been replaced with a Changeling after his death in the initial conflict with the Borg and "8472" a year earlier, a Changeling who has assimilated all the memories and personality of that dead crew member and, in character, feels all the things that person really would have felt. The Changelings see this as a gift, a way of giving immortality to someone who would otherwise have died, though they admit that it was also useful in the way of espionage. The rest of the Voyager crew, on the other hand, are simply creeped the fuck out that they've had a shapeshifter-zombie crewmate for the past year, and dump him off on the nearest Changeling planet and leave as quickly as possible.
					</p>
					<p>
						That uncomfortable realization leads Voyager to spending most of the next year trying to avoid "fluidic space", skirting the boundary between it and Borg space. Early on in that time period, the events of the canonical season 5 episode "Drone", occur, wherein a transporter accident merges some of Seven of Nine's nanoprobes with 29th century technology from the Doctor's mobile emitter, resulting in an advanced cybernetic entity who dubbed itself "One". This One exhibited Changeling-like abilities via the combination of nanoassembly and holographic replication, its organic body being symbiotic with its advanced technology on a cellular level, able to repair and adapt itself at will. "Raised" on a Federation ship with Federation values, and possessing 29th Century Federation technology, it attempted to combat the Borg when Voyager encountered them, but upon realizing that it could not do so alone, appeared to commit suicide while destroying a Borg fleet in a massive spatiotemporal disruption.
					</p>
					<p>
						Near the end of that year of dodging between Borg space and Fluidic Space, Voyager eventually find their way into Hirogen space near the edge of the galactic core. Through the Hirogen communications relays they establish brief contact with the Alpha Quadrant for the first time since they were stranded. In their short communication with Starfleet Headquarters, they inform them of the Changelings they have encountered, and are surprised to learn that the Dominion, with whom the Federation was on the brink of war when Voyager was lost, are lead by Changelings, with whom a truce has just been made after a tumultuous war. After learning this, and being chased from the communications relay by the hostile Hirogen, Voyager ventures back into Fluidic Space to attempt to negotiate safe passage through it with those that they hope are now peaceful allies of the Federation, at least so far as the Gamma Quadrant wormhole which will then cut their return journey home much, much shorter. The Changelings of Fluidic Space, unfortunately, know nothing of the Founders of the Dominion, but they are curious to learn more about them, believing them to be descendants of an ancient Changeling diaspora from a time when the solids of this region of space, where Changelings originated, feared and persecuted them, driving many of them far away in those dark days before, after much conflict, the peace of Fluidic Space was finally established as a safe place for Changelings. These Changelings offer Voyager safe passage through their space, if some of them can join Voyager on the journey deeper into the Gamma Quadrant to meet these "Founders" of the Dominion, their long-lost kin.
					</p>
					<p>
						During their passage through Fluidic Space, the Voyager crew learn much of what life is like for the Changelings there, and find much of it unsettling. On worlds where the conversion from solid matter to Changeling matter is still in progress, the Changeling children of solid parents often experiment with their ability to turn any rock or tree they touch into another Changeling of their own design and programming, going around "making friends" out of everything. The adult Changelings then have to link with those poorly-designed friends and teach them to be responsible parts of the world, to keep carrying out the role they originally had for the sake of the solids who still depend on them, at least until it's their turn to be something else in another life later. Someone still needs to be the ground that everyone else walks upon, not just figuratively but literally. But the Voyager crew find it very uncomfortable to think that they are walking upon sentient beings whose entire lives, their jobs in a manner of speaking, are to <em>be the ground</em>; not to mention all the other normally-inanimate objects on each world.
					</p>
					<p>
						They also learn more of the history of the Changelings, and their relationship with the Borg. It turns out that Changelings could not be assimilated by unmodified Borg technology because they effectively are a much more advanced version of Borg technology themselves, Changeling matter being essentially a fluid matrix of self-replicating and self-modifying nanotechnology capable of "assimilating" any matter on the atomic level. Their origin myth is that in the distant future, the Borg attempted to assimilate a race far more advanced than themselves, and in the process created a singular being far more advanced than the rest of the Borg, but free of their collective and aligned with the values of their more advanced nemesis. This being alone, who the myths call "The One", was unable to defeat the Borg and save his people of that time, and so he travelled back in time to build a force powerful enough to eventually defeat them, improving upon himself and his offspring until the first Changelings were born. Upon revelation of the Changelings' origins, the crew of Voyager realize that their One, the accidental merger of Borg nanoprobes and 29th century Federation technology, is most likely the same as the Changelings' "The One", and that they personally witnessed the proximate origins of the Changelings. This elevates Voyager to near-mythical status themselves among the Changelings of Fluidic Space, and The Doctor and Seven of Nine in particular are revered as something like a holy mother and father figure.
					</p>
					<p>
						As the final season begins, Voyager leads an expedition of Changelings across the unexplored middle of the Gamma quadrant toward Dominion space, there to reunite the Founders with their long-lost ancestors. They travel through a region where anti-Changeling sentiment among solids is still high, and have to try to peacefully negotiate the conflicts that arise there. Their eventual arrival in Dominion space is at first seen as hostile, but when the Changelings reveal themselves to the Dominion forces, they are then escorted to meet with the Founders themselves. Voyager's arrival at the Founders' homeworld strengthens Dominion-Federation relations by greatly pleasing the Founders, reconnecting them with their history and revealing that history to be tied to the Federation itself via the One and related time travel, and in the end Voyager is escorted through Dominion space to the wormhole and back home to the Alpha Quadrant at last.
					</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
