<?php $title = "The Superjesus Trilogy &ndash; by Forrest Cameranesi" ?>includes/header-dynamic.php
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2>The Superjesus Trilogy</h2>
				
					<p class="description">A very bizarre comedy mashup of Superman, Jesus, and Santa Claus mythos, together with some other Christmas themes.</p>


					<section>
						<h3>The Adventures of Superjesus</h3>
						<p>In the beginning, the alien god Jor-Elohim sent his only son from planet Heavon to save him from its destruction due to a terrorist attack detonating the Heavonite that permeated the planet's core. Baby Kal-Elohim ends up on a version of Earth where Rome is a global empire with 20th-century technology. He is found by Mary and Joseph, a young couple in Roman-occupied Judea, who raise him as their own child, and name him Jesus. They soon discover that their little baby Jesus is no ordinary child; he is possessed of great strength and power unlike any mortal man. When he is old enough, his parents show him his space-pod, and tell him the story of the night it fell from the sky like a shooting star, leading wise men, drummers, and other visitors to the Motel VI parking lot where they were staying that night. Jesus runs off into the desert in shock at this news; but once there, a crystal he brought from his space-pod, tossed into the dunes, builds an enormous sandcastle, wherein he communicates with the disembodied mind of his true father from Heavon, and accepts his destiny as savior of this world.</p>
						<p>By the time he grows up, Jesus now lives his daily life as a mild-mannered carpenter; but that bearded visage is really only his secret identity, as unbeknownst to most, behind the beard he is The Christ, a superhero who flies around in blue-and-red spandex with a flaming heart on his chest, fighting crime, healing the sick, and saving the souls of the wicked. But his antics slowly begin to make him enemies of the Roman empire, and of the Judean state which is subservient to it. One day he is unwittingly betrayed to them by his best friend Judas, who does not know Jesus is the Christ. On intel from Judas, The Christ is captured by the Judeans by use of shards of green Heavonite which rained down when he first arrived from Heavon. Thus subdued, he is nailed to a cross and left for dead. But several days later, his devoted fans find his tomb and remove the Heavonite from it; The Christ immediately returns to life and resumes his crime-fighting ways. News of his resurrection spreads quickly and he becomes even more renowned.</p>
						<p>This defiance of their punishment puts The Christ even further at odds with Rome. Jesus decides that he has to take the system down if he is to continue his mission of kicking ass and saving souls. As his conflict with Rome escalates, his secret identity is discovered and revealed to the public by Rome, and Jesus is forced into hiding even from his own people, who fear he will bring the wrath of Rome down upon them. But finally, Rome is toppled in a climactic showdown with Roman emperor Juliex Luthor, who is defeated when Judas, who has since moved up to working for Luthor, double-crosses his employer at the last moment. With his dying breath, Luthor utters his last words: "Et tu, Judas?" Thus falls Luthor. The Roman Empire falls with him, its territories are liberated, and Jesus is hailed as the savior of mankind.</p>
					</section>

					<section>
						<h3>Superjesus II: How the Grinch Killed Santa Christ</h3>
						<p>Decades later, Jesus is an international superstar, practically worshipped as the "Santa Christ", who not only fights crime, but also, every year on his birthday, December 25th, personally delivers presents to all the good little boys and girls of the world. He manages this in a single night by flying backward around the world really really fast, thus stopping time, allowing him to make all his deliveries, after which he flies forward around the world really really fast to resume time. His costume by this point has evolved to feature more bling, befitting his stardom; gold trim and backing surrounds his flaming heart emblem, his cape is now red velvet lined with white fur, as are his boots, and he wears gold-rimmed heart-shaped rockstar sunglasses. Between saving the day and announcing the winner of this year's Best Picture award (Andreas Llwyd Weber's critically acclaimed documentary <i>Jesus Christ, Superstar</i>), he likes photo ops, talk shows, and long walks on the beach with his sexy lady fans.</p>
						<p>But The Christ's day in the limelight comes crashing down when a enemy unlike any other rises against him. An ancient creature from the depths of Heavon, preserved from some earlier age, it too crashed to Earth long ago along with baby Kal-Elohim. Not knowing who or what it was, it has tried to blend in with human culture ever since; but failing miserably due to its hideous, green, alien appearance, it has been perpetually on The Christ's naughty list, and never gets anything but coal for Christmas. Now, fed up with its constant neglect, this monster known only as the Grinch is coming for Jesus.</p>
						<p>It begins one Christmas season by ravaging malls and holding hostage the fake Santa Christs who entertain children there. This catches the attention of the real Jesus, who comes demanding the release of the hostages. The Grinch instead kills them to provoke Jesus into combat. Jesus wades in overconfidently, but is then surprised when the Grinch deflects his blows and tosses Jesus on his ass. Jesus gets back up and re-enters the fight, more seriously this time, but is still quite well matched against the Grinch. The battle explodes violently, destroying the mall as civilians flee with their children, and spreading further still as the two throw each other about the city in their combat. Jesus manages to hold his ground for a while, but he finds that he is weakening, and the Grinch is growing stronger; for the Grinch, he realizes, has Heavonite in his body chemistry, and with it is sapping The Christ's strength. Fearing for mankind more than himself, Jesus takes the Grinch and, with his last ounce of strength, flies him high into space, hurling him into the void never to disturb Earth again. Jesus dies in the effort, and falls to Earth, burning like a meteror as he descends. His body is never found, and the world mourns for the death of The Christ. But some hold out hope, building snowy memorial statues of The Christ every year on Christmas, and singing their solemn prophecies that "he'll be back again some day".</p>
					</section>

					<section>
						<h3>Superjesus III: The Revenge of Zombie Jesus</h3>
						<p>Many centuries later, the crime-fighting, peace-keeping role of Jesus has been subsumed by a number of surrogates. The first of them was an ordinary man, Jesus' apostle Peter, who honed himself to extraordinary ability through rigorous training, crazy prepared planning, and unbelievably expensive secret technology, and came to be known as the Pseudochrist. Upon his death the mantle of Pseudochrist was passed down from generation to generation, eventually spawning an entire legion of Pseudochrists known as the Christ Corps or <i>Corpus Christi</i>, headquartered in Texas. Over the years, the Corpus Christi have created other Jesuses to help them. The first was a robot built to take down enemies no ordinary man could defeat: Robochrist. The first Robochrist served as a prototype for an entire legion of Robochrists which aided the Pseudochrists in their battles against evil. Another, more recent and more singular creation, was a clone of Jesus himself, recovered from DNA samples on his burial shroud, a sacred article since his resurrection: Thomochrist, who came to be the natural leader of the Corpus Christi. Most recently, a mysterious alien energy being has come to Earth from space specifically to honor the memory of The Christ, and now this Xenochrist fights together with the Corpus Christi, nearly outshining even Thomochrist in power.</p>
						<p>But a dark cult secretly worships only the original Jesus, viewing those who have assumed his mantle as heretical blasphemers, and they have fought darkly and secretly against the imposters ever since. Especially after the arrival of Xenochrist, they have been working on a dark, secret ritual to resurrect the original Jesus, needing only his body to complete the rites. The body of Jesus is finally found, surprisingly well-preserved, deep in the depths of the sea. There they build a dark, secret temple, enact the dark, secret rites, and chanting "Ph'nglui mglw'nafh Yshua Sh'm'yim wgah'nagl fhtagn", raise Zombie Jesus from the dead. Zombie Jesus proceeds to shamble the Earth, eating the brains of everyone on his naughty list, who in turn become zombies and shamble the Earth eating the brains of anyone they likewise deem naughty. Zombie Jesus himself is quickly opposed by the forces of the Corpus Christi. As the zombie apocalypse spreads, bringing eternal unlife to all mankind as promised in the dark, secret texts, the dark, secret cultists unveil themselves to the world and try to grab the power they have long since sought; but they are run down by the zombie horde, undone by their own creation.</p>
						<p>Zombie Jesus meanwhile burns through all who oppose him with his powerful hellfire-ray vision. The Pseudochrists and Robochrists, and eventually even the otherwise invulnerable Thomochrist, are destroyed in the cataclysmic battle. Finally, Xenochrist calls out Zombie Jesus, claiming to be "the naughtiest one of all", revealing himself to be the Grinch, whose heart grew three sizes after the absorption of The Christ's energy in their last battle. With his Heavonian power which he has since learned to control, he is able to battle Zombie Jesus successfully, but the two are evenly matched; Zombie Jesus, being dead already, cannot be killed. In the end, Xenochrist realizes how to win the battle: he imparts all the energy of The Christ back into Zombie Jesus, vanishing himself in a wisp of green light as the transfer completes, and returning Zombie Jesus to life, conscious and good again. Realizing what has become of the world, he calls on his super healing powers to return all the zombies to life again, ending the apocalypse. As the scattered survivors crawl out of the rubble, Jesus surveys what has become of the world, and together they set out to rebuild.</p>
					</section>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
