<?php $title = "Surfing the Cosmic Cataclysm &ndash; by Forrest Cameranesi" ?>
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-dynamic.php" ?>
				
				<section>
	
					<h2>Surfing the Cosmic Cataclysm</h2>
				
					<p class="description">A story about the unending end of the universe.</p>

					<p>An alien race from another galaxy arrives on a giant planet-ship in our solar system and makes first contact. They are lithe humanoids with a light, angelic or elfin air, and are vaguely remniscient of the stereotypical "greys". After hurried pleasantries they announce the reason for their visit: they have discovered that the vacuum is collapsing to a lower quantum state, an event which will inevitably destroy the entire universe in an expanding wave of destruction travelling at the speed of light, such that nobody will ever even see it coming, as they will cease to exist as soon as news of it reaches them. Except... these aliens possess warp technology, so they can outrun it. Their civilization now travels the stars ahead of the wave of destruction, initially stopping just to gather fuel and other supplies but as their technology has progressed over time they have begun to harvest all the matter they encounter and build a vast fleet of worlds propelled at warp speed away from their doom. The universe is infinite and, on a large scale, uniformly dense, so they can carry this out indefinitely, and plan to live like this forever. Every now and then they come across another alien race of course, and present them with a dilemma: either trust us and let us take over your planet and all your resources to turn it into a huge warp-capabable starship (we'll bring your sun along too), or stay here and be destroyed before you know it once this light-speed collapse of the universe reaches you. They give us one year to choose.</p>
					<p>Over the ensuing year typical alien first contact activities occur, there are shady back-room meetings between human governments and the aliens, and the people in general come to mistrust them as more and more power is seized in the name of alien cooperation. Eventually mass political unrest unseats the collaborating governments, and at the end of the year, Earth decides... no, we really don't trust these aliens. It is then that we learn that the dilemma was a false one, they're not letting any of the precious universe disappear never to be seen again: we're coming with them whether we like it or not. So they "conquer" us and begin converting Earth into a starship. As that progress happens, and resistance forces on Earth struggle futilely to fight them off, some of the protagonists uncover evidence, via the aliens' own technology, that they are telling the truth, right as the wave is about to reach Earth. But the aliens succeed despite our best efforts, and Earth is saved to join their fleet of worlds, with very mixed feelings.</p>
					<p>Now a part of this fleet of worlds, we meet the other alien races that have been "saved" by these aliens, and find there is much political strife among the different races which have been "saved". One of the first and oldest of those, only some of whom were picked up by the main aliens' early ships, and whose planet was left behind to disappear, are the main aliens' worst enemies: they are a scary-looking, beastly, somewhat insectoid race, much more disturbing to human sensibilities than the main aliens. But the human protagonists learn from them that the main aliens were actually the ones who caused the collapse - accidentally they claim, though some other factions suspect they even did it on purpose to give themselves carte blanch to save the universe by conquest. To keep us from siding with their enemies, the main aliens eventually admit to us that it is their fault, and claim that that is why they refuse to let anyone stay behind and die out of primitive mistrust like ours: they feel guilty enough already, they caused this catastrophe, and damnit the universe is going to be saved whether it likes it or not. They are even working on a final solution to the problem, something that will allow matter as we know it to exist within the lower-energy vacuum in a bubble of higher-energy vacuum, it's just... really hard to get working right. Even compared to moving thousands of entire solar systems at warp speed.</p>
					<p>Some factions suspect that the main aliens already have their final solution, and are keeping it to themselves: it's not like anybody else can go back into the destroyed universe to see what's going on there, so maybe the main aliens are using this all as a ploy to move everybody else out of the universe and take it all for their own. Others rightly ask those conspirators: why would anybody want to do that? If they could stay behind in the collapsed universe and get by just fine, why keep running along the edge of it, and bringing everybody else along? It turns out the main aliens aren't even really sure whether or not they did it on purpose or accident. There were many conspiracy theories within their own society early on about that, but so much from that time is lost that nobody really knows anymore, they just accept fault for it and go about "paying penance" for it by saving everybody whether they want to be saved or not.</p>
					<p>Different, more advanced factions occasionally try to move ahead of the main fleet and be the ones to make first contact and save other races, so as to win them to their faction's side. Some of these factions are willing to let other races stay behind to die if they so choose; many of those left behind are then conquered by the main aliens and brought along, although sometimes the aliens even go to war over whether or not to force a new race to come along or leave them behind to die. Eventually the human protagonists are recruited by such a faction, the one headed by the oldest enemies of the main aliens, to serve as ambassadors and we're-new-here-too guys, to convince the new aliens to join the fleet with the opposing faction. The new guys decline the offer, and the protagonists are torn over whether it's really right to let them die... they have to face their final moment of truth and choose sides on this issue. While they're wringing their hands, the main aliens show up and decide to force the new guys to come along, and the faction we've allied ourselves with goes to war with them over that. In the end, the wave of destruction arrives and it's too late; both the main aliens and the rebel faction clear off, and the planet is left behind to die, with our protagonists still on it...</p>
					<p>And then it turns out that the old rebel faction themselves already have the final solution, have had it for some time, and that's why they're willing to fight for a planet's right to "die": they've already installed their final solution there, and secretly told the leaders of the new aliens to choose not to come along, knowing they would survive. They aren't telling the main aliens, because they think those bastards deserve to be on the run forever for destroying the universe. But the rebel faction isn't big enough to save the entire universe like this, only those few they can reach first and successfully defend against the main aliens. Our protagonists don't think that this is OK, and with the help of the new aliens who just got saved, they hijack some of the rebel faction's warp ships to return to the main fleet and alert the main aliens.</p>
					<p>They proceed to wage war on the rebel faction to gain access to this technology, and humanity feels really awkward for starting this huge cosmic war. Then the moment of truth comes, the main aliens win, gain access to the technology... and decide to share it with Earth. Our solar system drops out of the main fleet and back into the now-mostly-empty old universe. We're promised that this tech will be installed all over and the whole universe will be safe now... but as Earth doesn't have our own warp tech, we're left behind with no way of confirming if they really made good on their promise, or if they just ditched us for being troublemakers and kept it all to themselves, continuing with the way they have done things for untold aeons.</p>

				</section>
	
<?php require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
