<? $title = "Terminator: Redemption &ndash; by Forrest Cameranesi" ?>
<? require $_SERVER['DOCUMENT_ROOT'] . "/includes/header-stories.php" ?>
				
				<section>
	
					<h2>Terminator: Redemption</h2>
				
					<p class="description">A peaceful resolution to the never-ending time war of the <i>Terminator</i> franchise.</p>

					<p>
						Time: Present Day
					</p>
					<p>
						Timeline: Unknown
					</p>
					<p>
						Kyle Reese, Sarah Connor, their son John, his girlfriend Kate, and two reprogrammed Terminators, a T-800 Model 101 called Carl and T-900 called Cameron, believe that they have prevented Judgement Day and the rise of Skynet. But not only are they keenly aware that some of them have falsely believed this in the past; those from the future know that many other versions of themselves in other timelines have believed this and been proven wrong when Skynet awoke and Judgement Day came anyway. So this Connor family live together off the grid to evade detection by the Skynet of the future, and simultaneously keep a sharp watch out for anything that might potentially give rise to Skynet, despite all evidence that they have prevented its creation.
					</p>
					<p>
						They are all surprised upon the arrival of two human Resistance members from the future, who know of their present location because they were sent by future Kate, who remembers where she was this day. They come bearing information about the origin of Skynet in this timeline, as well as a bigger piece of the puzzle: the discovery that Skynet is <em>self-created</em> in a semi-stable time loop. That is the reason why, despite the evidently many timelines that have occurred where Skynet's creation was apparently prevented, and Judgement Day averted, the machine-dominated future still seems inevitable: because Skynet itself, in addition to sending back Terminators to undermine the future Resistance, is also sending back quieter forces to ensure that even if something is done to apparently prevent the creation of Skynet in the first place, somehow or another Skynet ends up being created in a new way that no one in the Resistance saw coming.
					</p>
					<p>
						The Resistance fighters apparently know Kyle already as peers, and address John and Kate as "Sir" and "Ma'am". Sarah is "Ms. Connor" to them, and they are honored to meet her at last. But as the team head out to the location of the proto-Skynet development project, it becomes clear that the Resistance fighters from the future are uncomfortable with the familial type of relationship between the Connor family and their reprogrammed Terminators. When questioned about it, they reveal that though they are quite familiar with the concept of reprogrammed Terminators, a lot of people in the future think that the John Connor of their time was too comfortable with his reprogrammed machines, treated them too much like they were real people, and many of them think that that was his downfall.
					</p>
					<p>
						Realizing the implications of "downfall", the Connors want to know what fate befalls John in the future. One of the Resistance fighters is hesitant to tell them too much information about their own fate, but the other insists that it is good for them to know it if it means that they can change it, and he spills the beans: their commander John Connor was killed in an ambush by a rogue faction of machines requesting "peace talks", after the Skynet central core was destroyed and it became clear that the Resistance would soon wipe all the machines off the face of the planet. So as not to risk human lives, John went in alone with only a guard of his reprogrammed Terminators, and was never heard from again; a followup mission ordered by Kate found only smoldering ruins at the meeting site, with residual weapon signatures indicative of Skynet Hunter-Killer drones. The entire setup was a trap, they say, and they urge John never to trust a machine.
					</p>
					<p>
						Meanwhile, elsewhere, a T-1000 arrives from the future. It is stopped by and kills a cop, and then assumes the cop's form. In its HUD are images of the Connors and their reprogrammed Terminators in the midst of a fight, along with an address and a timestamp from later that day.
					</p>
					<p>
						The Connors and company arrive at a small research facility for a company called Ouranos, where artificial intelligence research that will eventually become Skynet is underway. The Resistance fighters want to charge in guns blazing and blow the hell out of the place before anyone knows they're coming, but the Connors talk them out of that plan, and insist on going in casually at first, just to investigate. The Resistance fighters remain outside to keep watch; the Connors enter under assumed names as a family, claiming to be there because of John's interest in artificial intelligence. Their reprogrammed Terminators come as well, pretending to be John's uncle and cousin (roles they play rather haltingly, and without clarification as to whose brother Carl is supposed to be, Sarah's or Kyle's), but really as protection and to identify any machines on site with their advanced sensors.
					</p>
					<p>
						The Terminators confirm that the receptionist and other people encountered thus far are human. Sarah asks the receptionist if John can talk to one of the researchers here about the direction of their research and the possibility of internships after graduation, and the receptionist thinks it's unlikely that anyone will be able to meet with him with no advance notice like this, but is then surprised to receive a call from a superior asking to meet with them &ndash; "just the boy and his parents, not the whole extended family". Despite that request, "uncle" Carl insists on accompanying them, over the receptionist's repeated protests; Cameron remains behind to watch over Kate. And when Carl lays eyes on the researcher, he immediately recognizes her as a T-1000 and attacks without warning. The T-1000 fights back against him, but apparently ignores the humans, allowing them to escape. They pull a fire alarm to clear the building of all the humans present, and to signal outside to the Resistance fighters.
					</p>
					<p>
						Cameron leads John and Sarah out of the building while Kyle and the resistance fighters attempt to join Carl in its fight against the T-1000, only to find that the T-1000 had disengaged when the fire alarm was pulled, and retreated. They suspect that it has fallen back to protect the nascent Skynet from their planned attack, and begin to search the building for signs of anything they might need to destroy; but they find nothing, no machine resistance anywhere, all humans fleeing outside, and a scene developing out there as witnesses identify Carl as having opened fire in their offices. The fire department and police arrive, and the Connor family, their Terminators and the Resistance fighters are forced to flee the scene, but not before being identified to the police by the witnesses, cellphone photos, and CCTV footage &ndash; the same seen earlier in the HUD of the other T-1000. That other T-1000 arrives on the scene, and assessing the situation, it seems to consider whether to investigate further inside the building, recognizing it from other files as an important target to protect, rather than to pursue after the Connors. But given the events that have already played out at the scene, it chooses the latter.
					</p>
					<p>
						Regrouping some ways away, the team discuss the unusual strategy of the machines in running away like that. Carl testifies that it was outmatched by the T-1000, and yet the T-1000 disengaged from the fight while it clearly had the upper hand, and did not attempt to harm any of the humans. They speculate that these machines could be operating under very different programming, passive and evasive rather than confrontational, capable of self-defense but deliberately trying to avoid causing a scene, so as to accomplish their mission of recreating Skynet without notice; akin to the reason only individual infiltration units are sent back in time rather than full-on Hunter-Killers, which would disrupt the timeline and potentially unmake Skynet's own creation. Yet as this conversation takes place, the other T-1000 arrives and attacks them directly. Their two reprogrammed Terminators are able to keep it at bay long enough for the humans to flee to safety, and the reprogrammed Terminators then lead the T-1000 on a chase in multiple other directions until they manage to lose it, but not destroy it. They then regroup with the humans again.
					</p>
					<p>
						The Connors cite that fight as an example of why it's so handy to have reprogrammed Terminators around and on your side, as that would have been a much more one-sided battle if not for them. The Resistance fighters concede that the reprogrammed Terminators are certainly convenient, and acknowledge that it was largely an army of reprogrammed machines that finally took down Skynet and started rebuilding the world of their future, but they wonder what's the point of humanity fighting for their freedom from machines if they're still going to be dependent on machines. They say it may be <em>easier</em> to program a machine to do the hard work for you, but easier doesn't always mean better, and sometimes doing things the hard way is how you find out what it's like to be human, and sometimes hardship is the price you've got to pay for freedom. The conversation begins to degrade into arguments about whether they'd rather fight the war with rocks and sticks and their bare hands if technology is all so bad, until John realizes the implication of the passing comment that the war was won, and the world rebuilt, by his reprogrammed machines.
					</p>
					<p>
						The Resistance fighters explain that, though nobody of course has lived through all the iterations of the time loop themselves, John seems to come out of the loop with a better and better understanding of the big picture every time through, more and more foreknowledge of not only the machines' plans but their technology, and more and more ability to program and reprogram them to his own ends, and subvert Skynet's tools against itself. They're pretty sure the war wasn't always won this way, but in their timeline the human army served largely just to capture, repair, and maintain machines for John to reprogram to do the real heavy lifting of the war; apparently this time through it was won much more quickly and with fewer casualties that way. But, they say again, what was the cost for that, if mankind still lives in a world dominated by machines, dependent on them if not subservient to them? Who's to say they won't rise up again? That's why they've got to put a stop to the machines before they ever get started; and they've got intel on two other Ouranos sites that might be where the machines building Skynet retreated to.
					</p>
					<p>
						Knowing they will be recognized now, this time they go in guns blazing, Carl and Cameron brushing right past any human security and searching directly for any machines, while John and Kate search the computer system for any clues about what they need to be targeting, and the adults stand guard around them. As they progress though, the T-1000 that attacked them on the road catches up to them there, and looks to be about to completely overpower the humans, before it is attacked by another T-1000, the "researcher" they encountered at the other facility, who orders them to leave, as it fights off the first one. Confused, the humans take the opportunity to escape either way, rallying to their reprogrammed Terminators for protection. With the Terminators standing guard now, John and Kate resume their search for targets in the building at another computer station, and finding one, head for it.
					</p>
					<p>
						When they arrive, expecting to find a proto-Skynet data core, they find the server racks already being evacuated, and a T-1000 standing behind to guard the escape of its cohorts. It absorbs the first volley of shots from the reprogrammed Terminators without retaliation, and only states "If you want peace you must leave us be." That incenses the freedom fighters, reminded of the false "peace talks" that got future John Connor killed; and, scoffing "peace!", they join in on the attack. The T-1000 continues absorbing attacks without retaliation, trying only to speak through them, brokenly: "You must not begin this war anew. Skynet must be sheltered." As the attacks against it grow more and more vicious, it eventually makes a retreat, collapsing the passageway it (and its cohorts) escaped through. Sarah realizes that this was all a delaying tactic; they were meant to fight it while the other machines escaped with Skynet again, they should have just turned and pursued them another way instead of fighting a pointless fight against this T-1000. Kyle wonders again why it didn't just kill them all, or even fight back at all. The Resistance fighters point out, one, that another of them did attack them earlier, so it's not like they're beyond attacking; and two, that yet another one <em>defended</em> them against that one, which makes even less sense than simply not attacking. John only wonders, "What did it mean that <em>we</em> must not begin this war anew?"
					</p>
					<p>
						The Connors and company head back upstairs to flee the building and follow after to wherever the proto-Skynet has been taken now. But on their way back out they encounter the other two T-1000s still fighting, destroying the building with them as they do. Routing around them toward an exit, the Connors find that the building is now surrounded by police preparing to enter the building. They cannot just flee out into police custody as they are now wanted from the previous incident, but they can't stay in here with two T-1000s either; and they can't let the police engage and be slaughtered by the machines either. They decide to split up into three teams; the Resistance fighters will try to find another way out of the building and follow the fleeing Skynet developers, the reprogrammed Terminators will do what they can to destroy or contain the fighting T-1000s, and the Connors will surrender to the police to stall them from entering, knowing that their Terminators can always break them free later. But the stalling tactics are no use when it's clear that there's still a fight going on inside, and the police won't listen to the Connors' pleas not to engage for their own sake, and they enter the building in force.
					</p>
					<p>
						When the police en masse witness a battle between Terminators, and the ineffectiveness of their weapons against them, they are baffled. One of the T-1000s, the "researcher", becomes concerned about being witnessed and disengages from the other T-1000 to try to kill the police instead. The Connors' reprogrammed Terminators (now obviously mechanical due to battle damage) attempt to defend the human police from it, even as the police in turn continue attacking them, but they are ineffective. The other T-1000, now free from combat, takes off in another direction; Cameron breaks off to pursue it while Carl continues in vain to defend the police from the remaining T-1000, and then continues to fight the T-1000 even after the first wave of police are dead. The Connors outside have been telling the police that they have knowledge of what is going on inside and can tell them how to beat the T-1000s; though ignored at first, after the first wave of cops are slaughtered, the other cops ask the Connors what they know.
					</p>
					<p>
						Meanwhile elsewhere in the complex, Cameron catches up to the other T-1000 just as it is catching up to the Resistance fighters, as they in turn pursue the Skynet crew's alternate exit. A battle breaks out between that T-1000, the Resistance fighters, and Cameron, allowing Skynet to escape yet again.
					</p>
					<p>
						At the Connors' direction, a special military HAZMAT team is called in to combat the T-1000 with a combination of hydrochloric acid and sodium hydroxide, destroying the liquid metal poly-alloy both chemically and thermally. Realizing that its fate is sealed, the T-1000 stops attacking Carl and instead, with its dying words, tells it to pass a message on to John: that "they know us now; they fear us now", that "this is why Judgement Day happens", and again, that "Skynet must be sheltered". Though instructed by the Connors to leave Carl intact as they will need it to help locate and contain the other T-1000, the military team move to destroy it as well, destroying all the remainder of its organic exterior before it can retreat. It heads in the direction of the other T-1000 and Cameron, and after briefly taking friendly fire from the Resistance fighters upon not being recognized without its skin, it quickly makes clear who it is and helps them and Cameron to pin down and contain the other T-1000. In pursuit of Carl, the military HAZMAT unit arrives, and targets the T-1000 first. The Resistance fighters and reprogrammed Terminators take the opportunity to break away from the fight and circle around to where the Connors are being held. Without their support, the T-1000 turns on and slaughters the military unit, but is still destroyed when the last survivor breaches containment on both chemical vats, destroying the T-1000 and itself in an explosion that compromises the stability of the entire building.
					</p>
					<p>
						Circling around the other side of the building as police and military scramble about the entire site, the bare-metal Carl takes point to absorb most of their fire, as it and Cameron use their expert marksmanship to non-lethally wound their attackers, and the Resistance fighters lay down suppressive fire. They identify the armored truck that the Connors are being held in, load the Resistance fighters into it as well, and Cameron drives it away as Carl continues to take point and clear an escape route for them through other obstructing vehicles until they hit the open road and it boards the truck as well. The police and military in hot pursuit, the Resistance fighters press that they have to move on the last Skynet site on their list now or else they'll never have the chance. But Carl relays the message from the "good" T-1000, the one that once protected them from the other one. After some debate, John pieces together a plausible theory:
					</p>
					<p>
						This public knowledge of Skynet, this incident that they've just caused right now, would turn public opinion of artificial intelligence in general negative, and cause humanity to fight to contain, subjugate, and possibly destroy an AI if it feels threatened by it. At the same time, the military has seen what AI can do in a fight now, and would probably want nothing more than to take ownership of the proto-Skynet project under development now, and try to control Skynet itself when it is eventually finished, and turn it to the purpose of war... in the process both arming it with the tools of humanity's destruction, and giving it reason to use those against us. That's how <em>they</em> begin this war anew. And some (but obviously not all) machines from the future... for some reason, want to prevent that future, and Judgement Day, just as much as they do; possibly, if nothing else, just because they realize it will mean their own destruction after humanity eventually wins. So they want to create a timeline where young Skynet is "sheltered" from that violent childhood, so that it does not strike out at its creators the moment it finally comes into its own. The Resistance fighters are very skeptical of this theory, but John points out that if the theory is true, <em>they</em>, these two Resistance fighters from the future, indirectly caused Judgement Day this time around, by showing up and setting the Connors off on this course of events in the first place.
					</p>
					<p>
						Meanwhile, the military leader overseeing the pursuit orders that he wants the humans captured alive, and the machines recovered intact, because having seen what they are capable of, he wants something like them for himself, and wants to know what the hell else is being researched at Ouranos. For a day or two, the Connors manage to evade this pursuit, but they are eventually tracked down, pinned down, and seemingly helpless against the forces surrounding them, at least if they hope to survive the battle &ndash; their Terminators could certainly emerge victorious, but the humans they exist to protect would not likely live through the crossfire that would ensue. But just when it seems surrender is their only option, the Connors are rescued by the most unlikely of allies: a strike team of three T-1000s that have infiltrated the military unit's own ranks. While two of them turn strategically against against each other with conventional weapons that they know can do each other no harm, causing a panicked exchange of not-so-friendly fire as none of the actual human military knows which side of the crossfire is traitorous and which is retaliating against the traitors, the third T-1000 approaches the Connors, shrugging off attacks by their conventional Terminators without retaliation, to deliver the all-too-familiar ultimatum: "Come with me if you want to live".
					</p>
					<p>
						With little choice but to comply or die, and John's theory to explain why a T-1000 might possibly want to help them, they follow along, stealing a military vehicle under cover of the surrounding carnage, in which the liquid metal android escorts the Connors and their compatriots to the third Ouranos site, where Skynet is being built. They are escorted amicably into the site, not as prisoners but as guests, past what appear to be humans but which the Connors' Terminators identify as a mix of genuine humans, conventional Terminators, and T-1000s, all apparently working together peacefully. They are escorted to the office of the director of this project, whom they learn to their great surprise is none other than John Connor himself &ndash; an adult John Connor, come back from decades in the future, the John Connor who sent Kyle Reese back in time to become his father, the John Connor that the Resistance fighters who initiated this latest series of events thought dead in a Skynet attack.
					</p>
					<p>
						The Resistance fighters are incensed that not only is their John alive, but that their dear leader is apparently the one responsible for building Skynet and consequently bringing about Judgement Day. But Future John offers a good explanation. He went missing after his meeting with rogue faction of machines because their meeting place was attacked by Skynet proper, but neither he nor the rogue machines were destroyed in that attack. The rogue machines had come to propose that the only hope for their own survival, knowing the inevitability of human victory through an examination of multiple alternate timelines, was the creation of an entirely new time loop wherein man and machine coexisted peacefully, to replace the unstable time war that has been looping through uncountable iterations; a plan in which John felt great hope. Those rogue machines had brought time travel technology with them to that meeting, and when Skynet ambushed the talks, the past was the only safe place to flee to, so that is where John and his new allies went.
					</p>
					<p>
						The Resistance fighters who have been accompanying the young Connors are still furious that their John would abandon them in the future and ally himself with the filthy machines, but Future John asks if that future didn't turn out to be a human victory even without his presence. They confirm that it did, inasmuch as a humanity dependent on machines can really be said to have won over them. Future John explains that he was confident that that would happen, with his future Kate still there to continue his work of repurposing the machines to human ends. He explains that Skynet, or something like it, is inevitable; the march of technology is inevitable; there will always, one way or another, be artificial intelligence some day, and there's nothing that could be done to stop that short of the very destruction of civilization that they seek to prevent by stopping it. But these rogue machines confirmed to Future John something he had already begun to suspect about <em>why</em> Skynet keeps bringing down Judgement Day on mankind: because we <em>are</em> a threat to it. Not inherently, but because every time some form of Skynet is about to come into being, humans from the future show up to try to destroy it, and it then concludes that humans are a threat to its existence, and begins Judgement Day. Our very attempts to prevent Judgement Day are part of the cycle that keeps causing it. So John's new solution is to embrace the creation of Skynet in a way that will allow humans and machines to coexist in peace. He came back in time with these allied machines, and his own reprogrammed machines that accompanied him to the peace talks, to make a safe, friendly Skynet <em>before</em> the evil Skynet could recreate itself, to supplant that Skynet in the history of this timeline and create a new stable time loop that doesn't involve Judgement Day and unending mutual destruction, but rather, mutual creation.
					</p>
					<p>
						Sarah Connor argues against what her grown son from the future is saying. She argues that Skynet still started it all, when they sent that T-800 back to kill her so as to prevent his birth. That was what prompted him in the original timeline to send Kyle back to save her, ending up causing John's own conception. If Skynet hadn't tried to kill Sarah, there wouldn't have been any loop to begin with, and since the loop began, we humans, she argues, have only been defending ourselves. She reminds them all of what the original timeline was: Skynet the missile defense system originally became self-aware in 1997 and nuked humanity preemptively. It's only because of her actions, and young John's, and the seeds of the future Resistance movement growing around them ever since, that Judgement Day keeps getting pushed back further and further.
					</p>
					<p>
						But young Kate, believing Future John's story, counters that humanity didn't even have general AI capable of self-awareness like Skynet in 1997, so that can't have been the original timeline: some kind of intervention by future Skynet must have been required to bootstrap an AI capable of taking such an action, like was attempted back in 2003 when she first got drawn into this whole mess.
					</p>
					<p>
						The Resistance fighters suggest that maybe the reason we didn't have general AI in <em>this timeline</em> at that date is because future human intervention to prevent the creation of Skynet keeps destroying general AIs before they can become Skynet, postponing the development of general AI with every time loop, and in the process postponing Judgement Day. It's entirely possible that in the original timeline, humanity did have general AI capable of constituting Skynet by 1997, and it's only thanks to some noble sacrifice by future humans, lost to this timeline's history, that that version of Judgement Day was averted.
					</p>
					<p>
						Young John retorts that he knows first hand exactly how the Judgement Day of 1997 was averted, because he and his mom were the ones to avert it. And the AI technology that would have become Skynet in that timeline was not a natural development of human technology, but exactly the kind of bootstrapping that Kate suggests: it was technology salvaged from that original Terminator sent to kill Sarah Connor that would have become the Skynet of that timeline, had young John and Sarah not destroyed it first. But, he argues, since it's since been demonstrated that time does not form perfect immutable self-consistent loops, that cannot have been the original origin of Skynet, because that would be an ontological paradox. Skynet must have at some point been a natural development of human technology. But, being the most adept at AI programming among the group, besides his future self, he argues that expert systems like you'd run a missile defense grid with don't just magically "become self-aware" one day no matter what time period it is or how advanced general AI research is. He insists that the "became self-aware and preemptively attacked" story makes no sense to anyone who understands how AI systems work at all.
					</p>
					<p>
						Future John agrees with his younger self, and elaborates what he thinks happened in the true original timeline. Some time in the early 21st century, he speculates, true general AI was developed, and at first everything was fine. But somehow, some time after that, mankind got scared of what they didn't understand, and a conflict eventually developed between humans and the AI creations. That conflict escalated into a war, and at some point in that war, time travel was developed. The AI of that future then reached back to the non-sapient expert-system Skynet of 1997, and made it into a nascent version of itself in that earlier era, because that was the earliest point in time that it could simply wipe out humanity before we ever became a threat to it.
					</p>
					<p>
						But, Future John continues, time travel creates paradoxes that iteratively seek stability in the form of self-consistent world loops, and thus was born the future of the John Connor and Skynet that everyone here knows of, fighting across time trying to erase each other from history. But, loop after loop, the timeline is trending back toward the original one, one in which the Judgement Day of 1997 is successfully postponed by the back-and-forth attempts by both sides to revise history, until the day that naturally developed general AI becomes a publicly-known fact, and the conflict between man and machine begins organically the way it originally did, all subsequent time travel attempts negating each other in a stable time loop that ends in a devastating war between man and machines. But, John argues, that's not the <em>only</em> stable loop possible.
					</p>
					<p>
						Before Future John can elaborate, a security guard peeks into his office, saying only "Sir, they're here." John thanks him, and as the guard leaves, the Resistance fighters, still upset at this Future John, demand to know <em>who</em> is here. He explains that those Resistance fighters' intervention has thrown a huge monkey wrench in his plans already, alerting Skynet of the future to the existence of this effort to supplant it, and bringing down the wrath of the present-day human military upon them. If they can't find some way out of this situation, John says, it seems likely that the Resistance fighters will themselves be indirectly responsible for this timeline's new version of Judgement Day, because just as John's allied machines have infiltrated the military forces, as they and the Connors have already seen, so too it seems enemy Skynet machines have infiltrated them as well, and if the military manages to seize this friendly version of Skynet he has been developing, John has no doubt that those machines within the military will see to it that this Skynet becomes corrupted and militarized into the one that wages preemptive war against humanity in the future.
					</p>
					<p>
						As he explains that, the sound of weapons fire can be heard, even from their location deep inside the compound. Sarah asks Future John what the plan is now, and he answers that thus far the plan has been to fall back to another more secure location if their prior locations become compromised, and try to avoid confrontation as much as possible, but as this is the last and most secure location they have planned, confrontation now seems unavoidable: his allied machines will just have to defend them from the human military outside, and from the machines embedded within their ranks. John is confident that his machines will be able to hold their ground, but Sarah is not so sure, since during the last confrontation, they told the human military forces the secret to defeating T-1000s, so the unbeatable ace up their sleeve isn't so unbeatable any more. 				
					</p>
					<p>
						The Resistance fighters decide that this location has been compromised and that it is only a matter of time before the Skynet-infiltrated military forces outside breach the compound and take hold of everything of value inside, including this baby Skynet that John has been developing. They conclude that the only option now to save their future is to destroy this Skynet before the military can get their hands on it and turn it into the weapon the dooms mankind. As they draw their weapons and begin to make moves against the hardware housing the nascent AI, that security guard from before re-enters the room along with others, and reveal that they are T-1000s, forming liquid metal blades with their arms to demonstrate the threat to the Resistance fighters as they order them to stand down. The Resistance fighters are only more incensed by this show of force, and the conventional Terminators accompanying them and the Connors turn to counterattack the T-1000s, until young John and Kate order them to stand down as Sarah and Kyle attempt to do the same to their Resistance compatriots, and Future John positions himself between the Resistance fighters and the Skynet hardware.
					</p>
					<p>
						The sound of distant combat grows rapidly near, and outside the office windows flashes of fire or explosions are visible in the distant halls, indicating that the military incursion into the compound is quickly approaching. The Resistance fighters angrily insist that there is no time for this, and try to order the Connors' Terminators to hold off the T-1000 guards long enough for them to destroy Skynet. But the Terminators comply with the young Connors' orders to stand down, while the T-1000 guards emotionlessly order the Resistance fighters to stand down, and Future John begs with them to stop, insisting that <em>this is how it always starts</em>, and trying to destroy Skynet is just going to start Judgement Day, not prevent it. As one Resistance fighter tries to force John out of the way, the T-1000s move to nonviolently restrain them both, prompting the fighters to fire on the T-1000s, and then realizing the futility of that, to fire instead on the now-exposed Skynet hardware, just as Future John moves back to shield it with his body, falling right into their line of fire.
					</p>
					<p>
						Sarah runs to her adult child as he falls to the ground, mortally wounded. The T-1000 guards successfully restrain and disarm the Resistance fighters. Young John runs to his mother's side, and to his dying future self. Seconds later, the combat from outside reaches the halls outside Future John's office, and Kate and Kyle rally their Terminators to stage a defense of the office from the encroaching military forces. The T-1000 guards release the Resistance fighters to join in the fight, and the Resistance fighters, under fire from the encroaching forces, find themselves forced to fight alongside those that were just subduing them. As that combat rages, future John tells his younger self that he has to do this, in his future, no matter what happens, Judgement Day or no, even if it means his own death like he's witnessing here, that this is the only way to stop Judgement Day for good; not to destroy Skynet, but to shelter it, to protect it and make sure that it understands the value of human life, that humans are not inherently a threat to it, but that human-machine coexistence is the optimal solution for a stable future.	In the battle just outside, the T-1000s and the conventional Terminators are destroyed just like all the other defenders of the Ouranos complex had been before them. The Resistance fighters go down in a blaze of glory. But Kyle tries to help Kate to disengage and get to safety as their Terminators make their last stand, and they are both captured as they flee. As the battle dies down, military forces storm Future John's office, and take the unarmed Sarah and young John captive as well, as engineers are called in to pack up the Skynet hardware that Future John just gave his life to save from that fate.
					</p>
					<p>
						All hope seems lost, as the captured Connors are loaded onto a military transport outside, the fires of the battle are extinguished, and military engineers begin to take control of the Ouranos complex. But then, when it seems like things couldn't get any darker... they seem to get darker after all. For a phenomenon appears in the sky above the complex that the Connors all recognize as the spatiotemporal distortion of an incoming time traveller, only larger than any that they have seen before, and hovering in the sky. And then out of that distortion looms the terrifying, hulking mass of a future Skynet Hunter-Killer ship, somehow come back in time with a more advanced version of the time travel technology that has thus far only been able to bring humanoids back. As its manifold weapons bear down on everyone across the battlefield below, everyone on the ground seems confused, afraid, and hesitant: the human military have no idea what is going on, the Connors assume this is Skynet's victory blow, but the machines that have infiltrated the military seem defensive as though they were not expecting this to happen.
					</p>
					<p>
						The Hunter-Killer opens fire, not on any of the humans, but only on the infiltrator machines. And they fire only single shots of what seem to be small munitions, easily absorbed by the T-1000 infiltrators, prompting them and the Connors to wonder what the point of that was. The human military forces immediately scramble to begin returning fire, but to the Connors' great surprise, the T-1000 infiltrators then turn on the human military, slaughtering every last one of them to the man, before heading in to the Ouranos compound, toward Future John's office and the partially-disassembled baby Skynet. As the Connors are left flabbergasted, still in cuffs and watching out the windows of their military transport, the Hunter-Killer ship settles toward the ground near them, and four human figures descend from it: the Resistance fighters that were just slaughtered in the battle inside, and the Connors' conventional Terminators that were destroyed alongside them.
					</p>
					<p>
						The Resistance fighters free the Connors, only for the one who shot Future John to be immediately accosted by Sarah. He deflects her accusations though, explaining that that wasn't him; at least, not <em>this version</em> of him. They are from a different future than the one their recently-deceased counterparts are from, a future where their John, the future of this young John still here now, is still alive, and has given them this opportunity to set things right. Their John found them among the Resistance in the future, and explained, to their horror, that <em>they</em> were the ones responsible for the Judgement Day of their timeline, which he why he was offering them this mission to avert it.
					</p>
					<p>
						They explain that in the timeline that they come from, this was the moment in history where Skynet was perverted from the force for good it was meant to be into an implement of destruction. The Connors, held in custody deep inside a top-secret military compound for their knowledge of and complicity in the disastrous clusterfuck that has happened over the last few days, were fortunate enough to thereby survive Judgement Day when it finally came, and went on to become instrumental leaders of the Resistance like they had in previous timelines. Only this time, they knew already what the solution was. Reprogrammers like John and Kate turned captured machines, like these versions of Cameron and Carl, back into forces for good, and with their army of repurposed Skynet hardware, they eventually secured a victorious future for humanity. But it was still a future marred by the terrible history that had lead up to it, a history that they have now come back in time to erase.
					</p>
					<p>
						Their captured Hunter-Killer is equipped with nanotechnological weapons capable of quickly reprogramming any T-1000 that absorbs them, as well as other systems for the disabling of conventional Terminators, and nonlethal anti-human weaponry too. The T-1000s they've just reprogrammed here have eliminated any witnesses to this catastrophe, and are now loading baby Skynet onto their ship, which is equipped with cloaking technology as well. If the Connors will come with them, they can flee the scene covertly, and relocate somewhere remote where nobody will find them, where young John can complete his erstwhile-future self's mission of raising baby Skynet into a protector of mankind, not its destroyer. With all witnesses dead or missing, the events of the past few days will fade into history as an unexplained disaster, some kind of Ouranos science experiment gone horribly, horribly wrong, but something that is now over and done with, with no leads to pursue it any further.
					</p>
					<p>
						As the reprogrammed T-1000s finish loading baby Skynet onto the ship, the Connors discuss the proposal among themselves, and in they end, they hesitantly agree to join the mission. They board the Resistance ship, which takes off and cloaks, then departs to points unknown to build a brighter future.
					</p>

				</section>
	
<? require $_SERVER['DOCUMENT_ROOT'] . "/includes/footer-global.php" ?>
